### ISSUE TITLE
Do we need section 2 on global language support in the Overview document?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1809]
The current Overview document has  separate [section on global language support](https://www.w3.org/TR/epub-overview-33/#sec-gls). However, there is only one subsection on [§3.1 EPUB metadata additions](https://www.w3.org/TR/epub-overview-33/#sec-gls-metadata) that is really EPUB specific. 

Wouldn't it be better (and cleaner) to have a general introductory text which says that EPUB, via the features provided by HTML, CSS, TTS, Fonts, and SVG, is fully relying on the i18n features developed for the Open Web Platform but it also defines some additional features that are specific to EPUB, keep §3.1 and remove all the other subsections?

**Comment by mattgarrish** [comment]
The only comment I have is that the overview was designed to sell EPUB 2 publishers on EPUB 3, not strictly overview what is specific to EPUB. That's why it highlights web features that are now available compared to what EPUB 2 offers.

That said, whether we still need to promote these features with separate sections or can generalize, I don't have a strong opinion on.

**Comment by murata2makoto** [comment]
Agree with @iherman 

The current wording is for historical reasons.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-09-30-epub#section2) on 2021-09-30

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-09-30-epub#resolution1):  Merge PR 1816, close issue 1809***

<details><summary><i>View the transcript</i></summary>

### 2. Global Language Support

_See github issue [#1809](https://github.com/w3c/epub-specs/issues/1809)._




_See github pull request [#1816](https://github.com/w3c/epub-specs/pull/1816)._




**Matt Garrish:** Global language support is talked about in EPUB3 overview... does it belong there?  

**Murata Makoto:** no strong opinion, but at that time global language support was important to promote EPUB3; this is no longer the case.  

**Wendy Reid:** change would make the overview more like a W3C document instead of a sales document  

**Matt Garrish:** I'm good either way  

> **Proposed resolution: Merge PR 1816, close issue 1809** *(Wendy Reid)*

> *Ben Schroeter:* +1

> *Toshiaki Koike:* +1

> *Brady Duga:* +1

> *Shinya Takami (高見真也):* +1

> *Murata Makoto:* +1

> *Wendy Reid:* +1

> *Matt Garrish:* +1

> *Masakazu Kitahara:* +1

> *Dan Lazin:* +1

> *Dave Cramer:* +1

> ***Resolution #1: Merge PR 1816, close issue 1809***

</details>

**Comment by iherman** [comment]
#1816 merged, closing
