### ISSUE TITLE
EPUB Accessibility 1.1 and FXL

### ISSUE THREAD

**Issue by gregoriopellegrino** [mattgarrish/epub-revision#1814]
In a [call earlier this year](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub-a11y#section5), I raised a question about EPUB Accessibility 1.1 and FXL.

My idea was was to add a note in EPUB Accessibility 1.1 stating that the spec covers reflowable EPUBs and that FXL a11y TF is working on guidelines for Fixed Layouts...

It seems to me that this has been on hold. How do we want to move this along?

**Comment by mattgarrish** [comment]
Could you explain what you mean by the specification covering reflowable and not fixed layouts? It covers all cases.

The task force isn't defining a new standard for fixed layout accessibility, only highlighting techniques for how to meet the existing requirements.

We can eventually mention the document in the [success techniques section](https://w3c.github.io/epub-specs/epub33/a11y/#sec-success-techniques), for example, but it would be best to wait for an FPWG-NOTE than make up a reference to the editor's draft.

**Comment by avneeshsingh** [comment]
Yes, we are not excluding FXL. If FXL can meet the requirements of EPUB Accessibility, it is good.

**Comment by gregoriopellegrino** [comment]
You are right. I expressed myself unclearly. It is true that technically an EPUB FXL can meet accessibility requirements, at the same time we know that in practice this is very difficult.

I'm afraid that for a content creator unfamiliar with accessibility issues (and EPUB specifications), looking for ways to make their publications accessible, may not be clear (as it is for us) that making an EPUB FXL accessible requires significantly more work than for a reflowable EPUB. And also that there is a work-in-progress in the field.

My proposal is to include a note or paragraph in EPUB Accessibility 1.1 that is useful to those who don't know all the WCAG 2 Success Criteria and EPUB 3.3 specifications.
