### ISSUE TITLE
A11y 1.1 - Scrolling in 2 dimensions caused by long metadata

### ISSUE THREAD

**Issue by anevins12** [mattgarrish/epub-revision#1822]
Zooming into the A11y 1.1 recommendation causes a horizontal scrollbar that persists at the same time as the vertical scrollbar. This issue will affect general users in small desktops and tablet devices, but more importantly people with low vision using browser zoom and screen magnifiers will experience difficulty navigating the content. Additionally, people modifying text properties may experience the same issue.

### Why is there a horizontal scrollbar?
The metadata code snippet contains lots of joining characters, which are conveyed to the user agent that this is one word. I appreciate this is only the symptom to the underlying problem that `<code>` tags aren't being styled with `white-space: break-spaces`.

### Expected results

- (Preferred) The `<code>` tag is styled to break spaces or break words, OR;
- The metadata is written in a way that takes little horizontal room, with each attribute on a new line. This might have readability improvements in general:
```
<meta 
  property="a11y:certifiedBy" 
  id="certifier">
    Accessibility Testers Group
</meta>
<link 
  rel="a11y:certifierReport" 
  refines="#certifier" 
  href="http://example.com/a11y/reports/9780000000001" />
```

**Comment by mattgarrish** [comment]
Thanks for the report. I'll take a look at the formatting as we usually do try to split long tags/attributes across lines whenever we can. I'll have to see how respec reformats the source when it pretty prints the markup to see what can be done about word breaking, though.

**Comment by anevins12** [comment]
Also hi from the APAWG
