### ISSUE TITLE
A11y 1.1 - Grammar improvements

### ISSUE THREAD

**Issue by anevins12** [mattgarrish/epub-revision#1823]
Note: This ticket is ongoing.
**Edit: This ticket is complete.**

I'm reviewing the A11y 1.1 Recommendation with JAWS to help spot grammatical issues. Here are some things I've noticed that don't sound right:

1. "It applicable" could be changed to "It is applicable";
2. "This specification applicable" could be changed to "This specification is applicable";
3. ...

**Comment by mattgarrish** [comment]
Thanks, I'll have a look at these later today.

**Comment by anevins12** [comment]
3. "but it is strongly RECOMMENDED that it **conform** to the" could be changed to "but it is strongly RECOMMENDED that it **conforms** to the"
4.  "but it is strongly RECOMMENDED that it **meet** Level AA" could be changed to "but it is strongly RECOMMENDED that it **meets** Level AA [WCAG2]."
5. "Development of WCAG 3 is currently ongoing **in W3C**" could be changed to "Development of WCAG 3 is currently ongoing **in the W3C**"
6. "Rather, EPUB Creators MUST evaluate their overall accessibility **as parts of a larger work.**" could be changed to "Rather, EPUB Creators MUST evaluate their overall accessibility **as part of larger work.**"
7. "The inclusion of these markers also simplifies the **creation a page list**" could be changed to "The inclusion of these markers also simplifies the **creation of a page list**"
8. "As a **reult** users have to have words repeated a" could be change to "As a **result** users have to have words repeated a"
9. "...EPUB Publication is good for **is complex question**" could be changed to "...EPUB Publication is good for **is a complex question**"
10. "Unlike web sites, which are continuously evolving, **an EPUB Creators**" could be changed to "Unlike web sites, which are continuously evolving, **EPUB Creators**"
11.  "...activating a feature **that that** would normally not be active." could be changed to ""...activating a feature **that** would normally not be active."

**Comment by mattgarrish** [comment]
Have you finished reviewing the document now @anevins12 ?

I don't want to merge the pull request to fix these until you're done.

**Comment by anevins12** [comment]
Yes Matt, I've finished now. Thank you for bearing with me when I logged issues before I was complete, apologies if that caused any frustration.

**Comment by mattgarrish** [comment]
Oh, no worries at all. I just didn't want to cut you off if you needed more time.

Very much appreciate the detailed review you did!
