### ISSUE TITLE
A11y 1.1 - Use of Color to Indicate Links

### ISSUE THREAD

**Issue by mbeganyi** [mattgarrish/epub-revision#1837]
Noticing the use of color to indicate links in the following sections. This occurs a lot in the spec and perhaps across multiple specs, so I'm not sure whether or not this has been raised before and closed due to something I'm unaware of. Just seems a bit too prevalent to have been missed until now.

> This specification takes an abstract approach to the accessibility requirements for EPUB Publications, similar to how WCAG [ WCAG2] separates its accessibility guidelines from the techniques to achieve them.

> This specification is also designed to address the accessibility needs of users independent of what languages they read. The same is true for the principles and success criteria defined in [ WCAG2].

> In addition, it uses the definition of assistive technology as defined in [ WCAG2].

> The primary source producing accessible web content is the W3C Web Content Accessibility Guidelines (WCAG) [WCAG2]. 

> WCAG [WCAG2] and its associated techniques provide extensive coverage...

> MUST meet the requirements of Level A, but it is strongly RECOMMENDED that it meet the requirements of Level AA [WCAG2].

> The WCAG principles [WCAG2] focus on the evaluation of individual web pages

WCAG2 is the link but the contrast ratio between it and the body text is 2.1:1. No other visual indication is given. Especially apparent when using high contrast mode.

> This specification is applicable to any EPUB Publication, even if the content conforms to an older version of EPUB that does not refer to this specification (e.g., EPUB 2 [ OPF-201]).

Same as above but [ OPF-201]). instead of [ WCAG2]

> This specification uses the following terminology defined in EPUB 3 [ EPUB-3]:

Same as above but [ EPUB-3]

> All EPUB Publications MUST include [ schema-org] accessibility metadata in the Package Document that exposes their accessible properties,

> EPUB Publications SHOULD include the following [ schema-org] accessibility metadata:

> EPUB Creators MAY include additional [ schema-org] accessibility metadata not specified in this section.

[ schema-org]

> See Discovery Metadata Techniques [EPUB-A11Y-TECH-11] for more information on these properties and how to include them in different versions of EPUB. See also DIST-002: Include accessibility metadata in distribution records [EPUB-A11Y-TECH-11] for more information on including accessibility metadata in other formats.

> The same is true of the techniques in the EPUB Accessibility Techniques document [EPUB-A11Y-TECH-11]. 

[EPUB-A11Y-TECH-11]

> Accessibility metadata can also be included in linked records [EPUB-3] 

[EPUB-3]

> MUST meet the requirements of WCAG 2.0 [WCAG20], but it is strongly RECOMMENDED

[WCAG20]

There are many more examples of this throughout the spec but I think I've noted enough already. For the sake of brevity (perhaps too late) I'll not report these any further. Looking forward to comments about this issue.

**Comment by mattgarrish** [comment]
> No other visual indication is given.

The visual indicator for normative and informative reference links are the square brackets that surround them. As far as I'm aware, that's sufficient to meet 1.4.1.

These are organizational styles and conventions, though, so you'll find them across W3C specifications. If you still believe it's an issue, I'd recommend opening this against the WCAG specification itself, since it's formatted the same way. You'll get an answer from the people directly responsible for creating the guidelines that way.

Their issue tracker is here: https://github.com/w3c/wcag/issues

**Comment by mbeganyi** [comment]
Will do, thanks Matt; appreciate your response.

**Comment by mattgarrish** [comment]
I'm going to close this issue as if changes are needed I'm expecting they'll come through the organization styles.
