### ISSUE TITLE
Add accessibility technique for publication language

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#1842]
I thought we had described the need to specify the language of the metadata in the package document and to specify the primary language of the publication in a dc:language element as part of covering SCs 3.1.1 and 3.1.2, but it appears I'm imaging things.

Should we add a new technique under the text section to reinforce this?

**Comment by murata2makoto** [comment]
I agree with the proposed addition and would like to go further.

JDC is now wondering if we can create another note "EPUB Accessibility Techniques: Japanese Langauge Support".  It is expected to be one of the many upcoming such specifications, just like JLreq is followed by many similar specifications.  Depending on the language specified in the package document, such language-dependent documents take effect.
