### ISSUE TITLE
Are epubcfi fragments legit when omitting step numbers for assertions? - Proposals included

### ISSUE THREAD

**Issue by P5music** [mattgarrish/epub-revision#1892]
I am using the epubcfi.js library from the epub.js project.
It includes the ids of HTML elements where they are found, so you can have this kind of cfi:
epubcfi(/6/4[chapter01ref]!/4/2[_preface]/8/3)

When a id is included, if assertions are implemented, what precedes the assertion, after the chapter redirection, is not useful.
/4/2 in the above example.

In the case that some modifications were made on the ePub publication, like some errata corrige with nodes or subnodes number changed, if the assertion is implemented, the right DOM position is still retrieved.
[When text itself is changed the offsets are changed. In principle text can be included along with offsets, so to have a text-assertions, but let's leave that aside]

The epubcfi library I am using does not implement assertions, so I wrote the assertion part myself. It is not difficult, I managed to assert with some string manipulation and the getElementById function.
I do not know if a more complete library is available. Please tell me in case it exists.

When the epubcfi is used as a fragment, it can be also used in URLs, and hyperlinks for example.
But if there are modifications, as above mentioned, the central part of the epubcfi is useless and it is also wrong.

1-I propose that a form of epubcfi is available, as syntactically correct and allowed (if not encouraged), where the steps are not provided if the id is provided, so that epubcfi strings have not to be changed by the reader system, and they are not "stale" for a broad range of possible modifications.
I do not know if this is just possible with the ! symbol like
epubcfi(/6/4[chapter01ref]![_preface]!/8/3)
but it seems that the numbers are mandatory.
This also could solve when the spine changes so numbers are wrong also for the chapter indirection.

In fact it is not necessary to change or update the epubcfis when they are stored as internal data, but when they are "visible", like in some document hyperlinks, they are misleading or just wrong, and unmatching if the assertion is not implemented.

2-Another proposal is that the id is mandatory on every element of the XHTML file (text, images, everything that can have char, spatial, temporal offsets) that is read from the RS, WebView, browser, and that it is mandatory to include it in the epubcfi string (this seems to be mandatory already).

If this is already available, and this question is silly, it's OK for me.
So if omitting the step numbers is possible right now, what is the correct syntax?
Is it 
epubcfi(/6/4[chapter01ref]![_preface]!/8/3)
or it is wrong?

If this form is already parsed it would be good, otherwise RS could give error when presented such a fragment.
The current form is said to have robustness and to allow detection of changes, but only if the assertions are processed, and a comparison is made.
But being that ids are unique inside a XHTML file, it is also robust not to have the step numbers at all.

Of course fragments from an app adopting the new form would be incompatible with older apps, but I think very few apps are publishing the epubcfi fragments so there is no harm to create instances of the new form nowadays.
I tested the epucfi.js with the new form and it works
epubcfi([_preface]/8/3:8)
Notice that It has not the ! symbol for the assertion of the element id.
Also
epubcfi(![_preface]/8/3:8)
epubcfi(/![_preface]/8/3:8)
work, I think, because the library can process them.
There is no chapter indirection because it is used inside Javascript code injected in the WebView displaying the chapter XHTML file itself in my app.

In the specification it seems that the step numbers are mandatory, so maybe the specification could be relaxed and explicitly mention that form as legit.

This is all IMHO, I hope this makes sense.

Regards

**Comment by bduga** [comment]
I believe all steps are required to enable sorting of CFIs, one of the reasons CFI was created. That is mentioned in the first section, though it is non-normative. Removing sortability from CFI is a fairly major change and loses one of its key features. Of course, CFI has been at risk pretty much forever since it is rarely used for data interchange and is typically implemented as an internal mechanism. If you don't plan to share the CFI with anyone and you have no need for sorting, then there is no reason to follow the spec, though in that case there isn't really any need to use CFI either.

**Comment by P5music** [comment]
>I believe all steps are required to enable sorting of CFIs, one of the reasons CFI was created. That is mentioned in the first section, though it is non-normative. Removing sortability from CFI is a fairly major change and loses one of its key features. 

I think that when sorting is necessary the redundant epubcfi can easily be recreated from the stepless one just finding the element (processing assertions) and recalculating the epubcfi on it (with a parameter like includeSteps=true) . In that case it also ensures that the right positions are compared and not the "stale" fragments.

>Of course, CFI has been at risk pretty much forever since it is rarely used for data interchange and is typically implemented as an internal mechanism. If you don't plan to share the CFI with anyone and you have no need for sorting, then there is no reason to follow the spec, though in that case there isn't really any need to use CFI either.

Well, the stepless form would help my app when modifications occurr to the publication. At present time my app do not use epubcfi, it just counts the nodes in an opinable manner but I introduced the epubcfi counting.
Yes, the epubcfi strings are going to be published, for the user to have a pointer to a position in the book, in certain cases.
This is also because I opened this issue:
https://github.com/w3c/epub-specs/issues/1887

Regards

**Comment by bduga** [comment]
CFI are designed to be sortable without inspection of the content. See the intro section, particularly:

`Comparison operations, including tests for sorting and comparison, should be able to be performed without accessing the referenced files.`

**Comment by P5music** [comment]
>CFI are designed to be sortable without inspection of the content. See the intro section, particularly:
Comparison operations, including tests for sorting and comparison, should be able to be performed without accessing the referenced files.

By the way, just some thoughts.

It seems that the epubcfi specifications are "internal" to an ePub publication, while I think they are "outside", or "from outside".
Or, better, there are two possible domains of use for them. 

I think RS developers see them as made for interoperability purposes and cross linking, even when not using them at all.

I also do not understand how fragments from different chapters could be compared. Better is to compare within a certain XHTML file.

Another idea would be saying that when epucfi is "from outside" it has not to comply the compare-without-accessing mandatory rule. Indeed in that case the system would know that the fragment is just for locating purposes, because it comes from outside.
Maybe that specification is too strict because it is not ideal for possible external uses, that are very likely at least. 

If epubcfi is at risk, maybe it has to be scaffolded with this kind of changes.

**Comment by mattgarrish** [comment]
I'm going to close this and #1887 and mark them as abandoned per established protocol for specifications that are not targeted for updating in W3C.

Note that it's not a comment on the merit of the issues, only that we are not actively tracking issues for these specifications. If we resurrect CFI, all abandoned issues will be reopened.

You're welcome to continue the discussions even if the issue is closed.
