### ISSUE TITLE
RS spec section on unique-identifier should talk about dc:identifier instead/as well

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#1894]
https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-pub-identifiers says:

> Reading Systems SHOULD NOT depend on the `unique-identifier` attribute being unique to one and only one EPUB Publication. 

This sounds like it's referring to `<package ... unique-identifier="pub-id">` , not `<dc:identifier id="pub-id">confreq-rs-pkg-unique-id</dc:identifier>`. But in practice, `unique-identifier` is basically never unique while `dc:identifier` usually is.

This is better in the format spec (https://w3c.github.io/epub-specs/epub33/core/#elemdef-opf-dcidentifier), which says:
> The EPUB Creator MUST provide an identifier that is unique to one and only one EPUB Publication — its Unique Identifier — in an `identifier` element. This `identifier` element MUST specify an `id` attribute whose value is referenced from the package element's `unique-identifier` attribute.

I think the RS spec should be edited to make clear that we're mostly talking about `dc:identifier`, not `unique-identifier`. Or maybe both of them.

**Comment by bduga** [comment]
I don't know which one we mean and clarifying would be useful, but Reading Systems shouldn't assume any unique identifier is unique, because they never are. So I support clarifying that we mean both of them, even if we didn't really mean that originally.

**Comment by mattgarrish** [comment]
It looks like the original wording was changed in https://github.com/w3c/epub-specs/issues/1310

But it doesn't make sense to have swapped out "Unique Identifier" with the attribute, as the attribute is just a pointer to where the value is defined.

Swapping back would restore the correct meaning.
