### ISSUE TITLE
Unclear note on the manifest element

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1917]
In the [§2.3.2.5.1 on manifest element](https://w3c.github.io/epub-specs/epub33/core/#sec-manifest-elem) not clear what the final note means. Is it still relevant?

Cc @rdeltour

**Comment by mattgarrish** [comment]
That's interesting. I'd forgotten we had a note about restricting file names to ascii, too.

That note was in 3.0, so I can only assume it's referring to compatibility with EPUB 2 reading systems.

**Comment by lordt4ever** [comment]
That's way I have a bank because the amount is to big:(
