### ISSUE TITLE
Remove a paragraph after 1898

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1918]
In a post #1898 world the first paragraph in [§3.4 Manifest in the RS document](https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-manifest) seems to be obsolete now. However, there is also a test assigned to it, and the corresponding test should be "reassigned"...

Cc @rdeltour @dlazin

**Comment by iherman** [comment]
In fact... the paragraph is correct (ie, not obsolete) just slightly redundant. I have added a PR (#1951) to bind the package file's URL to the correct reference in the content document and, I think, by doing that we can leave things as is.

**Comment by rdeltour** [comment]
I would have removed the paragraph altogether.

If we really want to be redundant for better clarity, I think informative prose or even a note would be preferable over a normative redundant MUST (which will have to be matched in tests, maintained in later versions, etc, etc).

**Comment by iherman** [comment]
I am reluctant removing it altogether, I think better clarity has a value here. If we keep it I would turn _MUST_ into  "must"  (and possibly refer to the new section that we were discussing), ie, no normative requirement in the text. The tests are actually to be changed anyway; they are also referred to from [the core spec](https://w3c.github.io/epub-specs/epub33/core/#sec-container-iri) (which is fine) but the test admins are not correct anyway (that should be a separate PR on the testing repository).

**Comment by iherman** [comment]
See https://github.com/w3c/epub-specs/pull/1951#issuecomment-985672020 : after some thoughts, I think you are right!
