### ISSUE TITLE
Declarative alternative to the file path definition

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1919]
Currently, the [File Path](https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-manifest) term is defined in a [separate section](https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-manifest) in an algorithmic fashion, which makes this a bit different from the rest of the document that favours declarative definitions. The question is whether there is a good alternative for the definition that would replace the algorithmic section.

@mattgarrish @rdeltour

**Comment by mattgarrish** [comment]
I assume you mean this section: https://www.w3.org/TR/epub-33/#sec-file-names-to-path-names ?

I agree it feels out of place, but I'm not sure it's critical to rewrite. I'd opt for clarity over form, but if you can write an equivalent declaratively that's easier to read I wouldn't object.

I find the introductory sentence kind of confusing in the way it uses "file" twice, though (three times if you count "File Path"):

> To derive the File Path of a file or directory _file_ in the OCF Abstract Container apply the following steps

I had to read a few times to parse out the meaning. Is it necessary to drop the variable in before the algorithm, or could this be more like:

> To derive a File Path in the OCF Abstract Container, apply the following steps:
>
> 1. Let _file_ be the directory or file to parse

**Comment by iherman** [comment]
The original issue may become moot soon. Indeed, the WG has agreed with the fundamental question in #1912, and the proposed changes follow the same "algorithmic" approach. I would think we should close this issue (modulo the editorial remarks of @mattgarrish).

**Comment by iherman** [comment]
> I find the introductory sentence kind of confusing in the way it uses "file" twice […]

Agreed. Actually, the change is even simpler; there is no need for the variable `file` at all: its only role is to give an initial value for `current` before the cycle. The simplest is to assign `current` with "the director or file to parse", and eliminate the `file` attribute from the section altogether.

**Comment by mattgarrish** [comment]
Just noting that the obfuscation algorithm has pseudo-code that is similar to this, too. It's formatted as an example right now (which is wrong).

**Comment by iherman** [comment]
> Just noting that the obfuscation algorithm has pseudo-code that is similar to this, too. It's formatted as an example right now (which is wrong).

O.k., that then makes the original issue moot. Should I add this as an automatically-closeable issue with #1927?

**Comment by rdeltour** [comment]
> Is it necessary to drop the variable in before the algorithm

Introducing the algorithm parameters in the declaration is recommended by [Infra](https://infra.spec.whatwg.org/#algorithm-declaration). I'd stick to this form if possible?

**Comment by mattgarrish** [comment]
> Introducing the algorithm parameters in the declaration is recommended by [Infra](https://infra.spec.whatwg.org/#algorithm-declaration).

Sure, but what confused me is that it's hard to figure out that's what's going on. There isn't an obvious name for the algorithm and there isn't a "given" to introduce the variable, just a lot of "file"s to read through.

It would still be clearer if it were formatted like:

> To **derive a File Path** given a file or directory _file_ in the OCF Abstract Container, apply the following steps ...
