### ISSUE TITLE
Reformulate the vocab. association mechanism in RS?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1920]
The RS [§10 Vocabulary Association Mechanism](https://w3c.github.io/epub-specs/epub33/rs/#sec-vocab-assoc) we may want to change how to expand property data types. We say that 

> [an expanded property value] MUST be a valid URL string]

 but that RS 

> do not have to parse the resulting URL.

 It sounds a bit odd, as the most simple way to check if a string is a valid URL string is to parse it. Also, it sounds more like an authoring requirement than a RS requirement. 

@rdeltour @mattgarrish

**Comment by mattgarrish** [comment]
> It sounds a bit odd, as the most simple way to check if a string is a valid URL string is to parse it.

Right, but it's not the only way. You could check it with the various regexes that people have come up with.

We can quibble over how reliable that is, of course, but this is only a check to weed out garbage. If you can verify the syntax without invoking a parser, we don't need to mandate a method.

**Comment by rdeltour** [comment]
> We can quibble over how reliable that is, of course, but this is only a check to weed out garbage. If you can verify the syntax without invoking a parser, we don't need to mandate a method.

Sure, I'm just not sure we need to say anything about it 😊.

**Comment by mattgarrish** [comment]
Can we close this @iherman?

**Comment by iherman** [comment]
Yep. I hereby close this!
