### ISSUE TITLE
Example 46 formatting

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#1923]
Looks like there's an example embedded in the example, so there are two example headings: https://www.w3.org/TR/epub-33/#example-46

It's also kind of strange to start the description with "for example".

**Comment by iherman** [comment]
Stupid me... I moved the example description text into the example by using an `<aside>` and forgot to change what was there.

**Comment by mattgarrish** [comment]
Closing as this was fixed in #1930 and I'll merge with #1927.
