### ISSUE TITLE
Do we need/want an extra constraint on the origin?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1925]
At the moment, there are two constraint settings on the origin in the RS spec:

> It MUST assign a unique origin [URL], shared by all spine-level scripts of the EPUB Publication. That origin [URL] MUST be unique for each EPUB Publication instance. ([§4.4 Scripting](https://www.w3.org/TR/epub-rs-33/#sec-scripted-content))

and 

> The origin of the container root URL is unique for each EPUB Publication instance. ([§7.1.1  URL of the Root Directory](https://www.w3.org/TR/epub-rs-33/#sec-container-iri))

During the discussion on #1898 an additional constraint was originally proposed in https://github.com/w3c/epub-specs/issues/1888#issuecomment-961502739:

> the origins of the container URLs of all the files in the OCF Abstract Container MUST be same origin one with another.

In the course of the discussion in #1898 problems were raised on the feasibility of this extra constraint. The concerns invoked were:

- RS systems may want to assign separate origin for content documents with and without scripting, respectively.
- All custom-scheme URLs (epub: and the likes, httpsr2:, ibooks-epub:) would be disallowed: the origin of each custom-scheme URL is a new opaque origin (see the "otherwise" clause of the [URL’s origin definition](https://url.spec.whatwg.org/#origin)). That could make a lot of RS non-conforming, for a requirement that is not necessarily backed by a strong use case.

This issue is just to check separately whether the (temporary) decision on dropping the extra constraint is fine or not.

@rdeltour @bduga

**Comment by rdeltour** [comment]
> * All custom-scheme URLs (epub: and the likes, httpsr2:, ibooks-epub:) would be disallowed: the origin of each custom-scheme URL is a new opaque origin (see the "otherwise" clause of the [URL’s origin definition](https://url.spec.whatwg.org/#origin)). That could make a lot of RS non-conforming, for a requirement that is not necessarily backed by a strong use case.

Just a little comment on this point: @danielweck and I had a look at the Thorium custom-scheme implementation. In fact, the Electron framework seems to willfully violates the URL standard here, as the origin returned for `httpsr2:` URLs is not opaque (not serialized to null), but instead an special-scheme-like tuple origin.

**Comment by iherman** [comment]
There hasn't been any discussion in the past three months, which could be translated as saying:

> That could make a lot of RS non-conforming, for a requirement that is not necessarily backed by a strong use case.

I would propose to close this issue without further action. It may come up later, then we could reopen it again, if needed. I set the label to propose closing.
