### ISSUE TITLE
Add example titles

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#1926]
What are now text descriptions below the example number used to be italicized headings for the examples in the IDPF output.

I find it takes more effort now to figure out what an example is about with only the number as the title. We should reformat the text back to titles and only keep the parts that describe the example as descriptions.

**Comment by iherman** [comment]
I'm not sure I understand what you mean. Can you give a specific example?

**Comment by mattgarrish** [comment]
Here's the very first:

> EXAMPLE 1
> The following example shows a reference to an audio file in an XHTML Content Document that is located inside the EPUB Container.

A title would make this a whole lot simpler to scan over:

> Example 1 - Referencing a local resource
> In this example, the audio file referenced from the XHTML `audio` element is located inside the EPUB Container.

In many cases, the descriptions don't add anything more than you could express as a title. I hate having to read the examples to find out what they're about, which I stumbled into as I was trying to make the fallback examples make more sense.

**Comment by mattgarrish** [comment]
I also remembered that we had to fix the formatting of the examples, as they flip between `div` and `aside`, but putting the example class on a `div` doesn't generate a heading. By the respec docs, you're only supposed to use on `aside` and `pre`.

**Comment by iherman** [comment]
> Here's the very first:
> 
> > EXAMPLE 1
> > The following example shows a reference to an audio file in an XHTML Content Document that is located inside the EPUB Container.
> 
> A title would make this a whole lot simpler to scan over:
> 
> > Example 1 - Referencing a local resource
> > In this example, the audio file referenced from the XHTML `audio` element is located inside the EPUB Container.
> 
> In many cases, the descriptions don't add anything more than you could express as a title. I hate having to read the examples to find out what they're about, which I stumbled into as I was trying to make the fallback examples make more sense.

Ah! I see what you mean and I agree. But that means changing a whole lot of examples (there are over 90 of them...). In any case, I have added a title to Example 47 in #1927, although in that specific case I did not really feel like shortening the description text...

When other things settle down, we can divide up the spec among the two of us to set the titles.

**Comment by mattgarrish** [comment]
> But that means changing a whole lot of examples (there are over 90 of them)

Ya, I realized that after I started. ☹️ 

I slowly cleaned them all up yesterday, as I wasn't sure if I'd have to go out of town today. Going to open a PR in a minute.
