### ISSUE TITLE
Do we want to keep the container root URL heuristics?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1933]
(This is an [editors' note in the spec](https://w3c.github.io/epub-specs/epub33/rs/#sec-container-iri) converted into a github issue.)

The definition for URL's of the Root directory in previous versions of the RS spec contained the following note:

> This specification does not mandate any particular implementation technique for the creation of a unique origin in the absence of a reliable Web origin (e.g., HTTP URL scheme + host + port). The necessary heuristics may include the combination of the Publication's Unique Identifier (although, in practice, these identifiers may in fact not guarantee globally-unique identification, that is why it is recommended to combine multiple techniques), filesystem path, OCF Zip Container checksum, etc.

The new, post #1898 version on the text has replaced the original [with a more precise definition](https://w3c.github.io/epub-specs/epub33/rs/#sec-container-iri) which relies on the RS to use a root URL that relies on some features it must adhere to. The question is whether that note should be still kept in the text, or it is o.k. to remove it.

(Note: in the current version, i.e., the one produced by #1898, that note has been removed.)

**Comment by iherman** [comment]
After some thoughts, my proposal is to keep that note removed (ie, no change on the spec as it stands today).

@rdeltour @mattgarrish wdyt?

**Comment by rdeltour** [comment]
OK for keeping the note removed 👍

**Comment by dauwhe** [comment]
Let's keep the note removed.
