### ISSUE TITLE
Should the RS spec include something about layout overrides?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1941]
The content document, in [§5.2.1.1](https://www.w3.org/TR/epub-33/#layout-overrides) includes the possibility to overide the global value for fixed layout (prepaginated or reflowable). However, nothing is said about RS requirements about this: is it a _MUST_, a _SHOULD_, or, possibly, a _MAY_ for RS-s to honor this request?

@dauwhe @mattgarrish @wareid

**Comment by mattgarrish** [comment]
Skimming through the FXL sections, it looks like support for the global property values are all "shoulds", so it's probably safe to match that.

**Comment by mattgarrish** [comment]
And arguably reading systems must support the layout overrides, since basic FXL support is required. But the other properties generally default to doing whatever the reading system supports, so short of changing that they can't be any higher than "should".

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-12-09-epub#section4) on 2021-12-09

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-12-09-epub#resolution3):  Merge PR 1947 and close issue 1941.***

<details><summary><i>View the transcript</i></summary>

### 4. Should the RS spec include something about layout overrides? (issue epub-specs#1941)

_See github issue [epub-specs#1941](https://github.com/w3c/epub-specs/issues/1941)._




_See github pull request [epub-specs#1947](https://github.com/w3c/epub-specs/pull/1947)._




**Wendy Reid:** we have a statement in content spec that it is possible to override the global layout value, but nothing is said about it in the RS requirements.  
… and some of the associated behaviours are SHOULD in the RS spec.  

> *Wendy Reid:* See [Statement in the content document](https://www.w3.org/TR/epub-33/#layout-overrides).

**Wendy Reid:** these overrides theoretically make mixed modality content (fixed + reflow) possible, but its underspecified.  

**Dave Cramer:** i'm aware of some uses, e.g. in educational content, there might be reflow text on one side, and fixed layout reference material on the other side.  

**Brady Duga:** i'd hate to lose this feature to a lack of implementations. We don't support it, but I think we should.  

**Wendy Reid:** mgarrish has made a PR where he he proposes language.  

**Shinya Takami (高見真也):** in Japan we do use partially fixed layout.  

**Dave Cramer:** does that give us enough implementations to get this feature through?.  

**Wendy Reid:** we might also have a partial implementation of this - specifically for covers for reflow books.  

**Dave Cramer:** we do seem to have consensus that its necessary to have an RS conformance statement for these overrides.  
… the fact that its missing might just be an artefact from when we split out RS requirements from core.  

> **Proposed resolution: Merge PR 1947 and close issue 1941.** *(Wendy Reid)*

> *Brady Duga:* +1.

> *Shinya Takami (高見真也):* +1.

> *Wendy Reid:* +1.

> *Matthew Chan:* +1.

> *Murata Makoto:* +1.

> *Toshiaki Koike:* +1.

> *Dave Cramer:* +1.

> *Masakazu Kitahara:* +1.

> ***Resolution #3: Merge PR 1947 and close issue 1941.***

</details>
