### ISSUE TITLE
Error in the <body> element definition?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1983]
The SMIL `<body>` element is defined as:

> **Usage**
> The `body` element is the REQUIRED second child of the [smil](https://www.w3.org/TR/epub-33/#elemdef-smil) element.

But that presupposes that the `head` element is also present, which is not required. Ie, the `body` element might very well be the **first** child of the `smil` element. (This is the case of all the examples for full Media Overlay documents.)

cc @marisademeglio @danielweck

**Comment by mattgarrish** [comment]
From a purely content model definition perspective it seems fine to refer to them ordinally, but I suppose it could be rewritten along these lines:

"The `body` element is a REQUIRED child of the [smil](https://www.w3.org/TR/epub-33/#elemdef-smil) element. It follows the `head` element, when that element is present."
