### ISSUE TITLE
Associating MO style information: only link?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1987]
Section [§7.3.4](https://w3c.github.io/epub-specs/epub33/core/#sec-docs-assoc-style) in the MO section of the spec says:

> EPUB Creators MAY define any CSS properties for the specified CSS classes, but must ensure that each EPUB Content Document with an associated Media Overlay Document includes a link to the CSS style sheet with the class definitions. Reading Systems might provide their own styling, or no styling at all, in the absence of a linked definition.

The way I read this paragraph is that an embedded style sheet to define the classes designated by `active-class` and the `playback-active-class` is not allowed. I would not think this restriction is intentional, is it?

@marisademeglio @mattgarrish @danielweck

**Comment by marisademeglio** [comment]
Yes I think you're right. How about this:

"EPUB Creators MAY define any CSS properties for the specified CSS classes, but must ensure that each EPUB Content Document with an associated Media Overlay Document includes CSS containing the class definitions. Reading Systems might provide their own styling, or no styling at all, in the absence of author-provided definitions."

To me, "includes CSS" can mean both embedded and linked.

**Comment by mattgarrish** [comment]
> To me, "includes CSS" can mean both embedded and linked.

Should we make that explicit "... includes CSS (either embedded or linked)" ?

Might head off a future issue saying it sounds too much like embedded... 😄

**Comment by iherman** [comment]
I am in favor or @mattgarrish's addition, just to be absolutely clear about it.
