### ISSUE TITLE
Redundant restriction on obfuscation

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#1996]
I noticed in the encryption element section it still says:

> EPUB Creators MUST NOT encrypt or obfuscate the following files:

https://w3c.github.io/epub-specs/epub33/core/#sec-encryption.xml-encryption

But obfuscation is restricted to fonts in 6.3.5:

> As the obfuscation algorithm is restricted to fonts, the URI attribute of the CipherReference element MUST reference a [Font Core Media Type](https://w3c.github.io/epub-specs/epub33/core/#cmt-grp-font).

https://w3c.github.io/epub-specs/epub33/core/#obfus-specifying

Suggest we delete "or obfuscate" from the first instance.

**Comment by iherman** [comment]
Created PR #1998 to get this one out of the way...
