### ISSUE TITLE
Fate of the prefixed CSS properties?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#2003]
There is a document under development to account for the implementation of various properties (see #2002). For the CR criteria we also have to do something about the [Prefixed CSS properties](https://w3c.github.io/epub-specs/epub33/core/#css-prefixes). Or should we/could we label them explicitly as deprecated?

@dauwhe

**Comment by dauwhe** [comment]
I would be very wary of deprecating these... my understanding is that they are still widely used in Japan. @murata2makoto @shiestyle

**Comment by bduga** [comment]
We might be able to deprecate most of these - CSS has moved on from this barbaric practice, right? It seems that most of these now have non-prefixed forms in modern browsers. There may be a problem with the [text combine properties](https://w3c.github.io/epub-specs/epub33/core/#sec-css-prefixed-writing-modes-text-combine) which have a more complex mapping to current CSS but I am not sure I see the harm in deprecating if we provide clear mappings to un-prefixed versions (which I think we do).

**Comment by iherman** [comment]
> I would be very wary of deprecating these... my understanding is that they are still widely used in Japan. @murata2makoto @shiestyle

If so, then we have to have tests for each of those and get feedbacks from implementers; ie, they should fall under the same category as the tests we have done for functional issues. Other than that being successful, they would all be flagged as 'under-implemented'...

**Comment by dauwhe** [comment]
> CSS has moved on from this barbaric practice, right?

Yeah, but there's likely lots of content out there that only uses the prefixed version.

**Comment by mattgarrish** [comment]
> Yeah, but there's likely lots of content out there that only uses the prefixed version.

epubcheck isn't going to report on these whether they're deprecated or not, right @rdeltour?

It only does some basic syntax checking and stuff for css.

**Comment by shiestyle** [comment]
If EPUBCheck will not mark these as errors, it's OK to move to deprecated or under-implemented.

**Comment by rdeltour** [comment]
> epubcheck isn't going to report on these whether they're deprecated or not, right @rdeltour?

Correct (as far as I remember). I can add some tests when this issue is resolved.

**Comment by toshiakikoike** [comment]
Some properties don't work well without -epub-prefix.
For very important example is 'text-emphasis-style'.
https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style
Chrome, Edge, Opera, WebView Android, Chrome Android, Opera Android, Samsung Internet reqire a vendor prefix or different name for use.
Then, RSs using WebView Android don't work well 'text-emphasis-style'.

I made a sample EPUB using,
writing-mode:vertical-rl
text-underline-position
text-orientation:sideways
text-combine-upright:all
text-emphasis-style: [value]

https://github.com/toshiakikoike/epub_file/tree/master/no-prefix-sample
(No error or warnings with EPUBCheck v5.0.0-beta-1))

Result;

Amazon Kindle(Kindle Previewer)
All OK.

Google Play Books(Android)
writing-mode:vertical-rl -- OK
text-underline-position -- OK
text-orientation:sideways -- OK
text-combine-uprigjt:all -- NG
text-emphasis-style: [value] -- NG
-epub-text-emphasis-style: [value] -- OK

Rakuten Kobo(Android)
writing-mode:vertical-rl -- NG
-epub-writing-mode:vertical-rl -- OK
text-underline-position -- OK
text-orientation:sideways -- NG
text-combine-uprigjt:all -- NG
text-emphasis-style: [value] -- NG
-epub-text-emphasis-style: [value] -- OK

Sony Reader(Android)
writing-mode:vertical-rl -- NG
-epub-writing-mode-vertical-rl -- OK
text-underline-position -- OK
text-orientation:sideways -- NG
text-combine-uprigjt:all -- NG
text-emphasis-style: [value] -- NG
-epub-text-emphasis-style: [value] -- OK

Apple Books(iPhone)
writing-mode:vertical-rl -- OK
text-underline-position -- OK
text-orientation:sideways -- OK
text-combine-uprigjt:all -- NG
text-emphasis-style: [value] -- OK

**Comment by bduga** [comment]
@toshiakikoike , it looks like there is a typo in one of your properties - `text-combine-uprigjt:all` should be `text-combine-upright:all`. That probably explains the failures.

**Comment by toshiakikoike** [comment]
@bduga 
Oh, it's typo on this issue.
But on EPUB, it's  "text-combine-upright:all;".

https://github.com/toshiakikoike/epub_file/blob/master/no-prefix-sample/OEBPS/text/book_0001.xhtml
`    .tcy {
      text-combine-upright:all;
    }`

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-02-25-epub#section1) on 2022-02-25

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 1. Fate of the prefixed CSS properties? (issue epub-specs#2003)

_See github issue [epub-specs#2003](https://github.com/w3c/epub-specs/issues/2003)._




**Dave Cramer:** ivan wondered if we should label these as deprecated.  
… i will remind the wg of the definition. Deprecated feature is one which is not recommended for use in this version of spec. Generally have no support in RS. Authors should not use in epubs, RS may support. Validators should alert when encountered in epubs..  
… i would argue that is not the case here.  
… these are widely used and somewhat widely supported. I'm also not sure what benefit we get from deprecating them..  
… also, the behaviour of prefixed properties in css is pretty well defined, and its common web dev practice to have both prefixed and non-prefixed version of property for widest compatibility.  

**Ivan Herman:** we have lets say 15 of those prefixed properties, quite a large number.  
… at the moment they are required features, i.e. every RS must implement.  
… if we agree with that, then we need to create tests for each of those.  

**Dave Cramer:** one way to phrase this is that these are epub specific features which don't yet have tests.  

**Ivan Herman:** yes.  
… and before we start making tests, we should ask whether it is worth the trouble of doing that work.  
… agree that the term 'deprecated' may not be correct here.  

**Dan Lazin:** is the reason that we want to deal with this that the testing status is unclear?.  
… this is motivated mostly by testing?.  

> *Murata Makoto:* I'm surprised to see "MUST support all prefixed properties defined".

**Ivan Herman:** there are appendices in testing for vocabs, including for this, and i'm not sure what to do with it.  

**Dan Lazin:** seems like we just need to write tests for this, rather than consider deprecation/under-implemented status.  

**Brady Duga:** might be embarrassing to include these in the spec, but we can't really get rid of them because there is content that uses these.  
… in reality, I see content that uses all possible prefixes, and other content that uses none of the prefixes.  
… toshiaki koike did essentially write some tests for these already, they are in the bug report.  

**Dave Cramer:** i'm not embarrassed by these, we needed them back in the day, there was no alternative.  

**Ivan Herman:** is it correct that each of those prefixed CSS attribute have now a regular CSS attribute?.  
… if 'yes', then having it as a required feature in Core seems not a good thing.  
… we could say 'for reasons of backwards compatibility, then RS should implement as well', but we can also say that new epubs created today should not use these.  
… they should use the CSS ones instead.  
… the same way that new content should not use mozilla and chrome specific prefixes today.  

**Dan Lazin:** yes, they all have non-prefixed versions. At least this is what the documentation currently implies.  

**Brady Duga:** they all have non-prefixed versions, but the function isn't 1-to-1.  

**Dave Cramer:** also, given the nature of epub RSes, we often need to author content that needs to work in RS that have not been updated in a while.  
… there might be cases where there are good reasons to do this.  
… CSS accounts for this by allowing authors to use both prefixed and non-prefixed.  

**Dan Lazin:** don't old RS implicitly not support epub 3.3?.  

**Wendy Reid:** no, because epub 3.3 is a valid epub 3.2, etc. etc. backwards compatibility.  

**Dave Cramer:** i think we just write some tests here.  

**Brady Duga:** do we point people to the right way to deal with pre-fixed properties (i.e. also state the non-prefixed properties)?.  

**Dave Cramer:** this is just an appendix, we're not necessarily calling attention to the right way to do things in this section.  

**Brady Duga:** i was thinking just a pointer, but okay, this is pretty easy to test.  

**Wendy Reid:** i think we might want to add text that says "we're in a different place now, these css properties are supported in modern web, we recommend that you use both prefixed and non-prefixed".  

> *Murata Makoto:* `-epub-text-combine: horizontal 3` cannot be rewritten without using prefixes.

**Ivan Herman:** the fact that it is an appendix does not mean that it is non-normative, let's not conflate these.  
… for the time being this is a normative section.  
… my proposal would be, in the content document, both entries should be marked 'should not be used', and in the RS doc, we say 'should implement'.  
… and if they are 'should', then we should write tests.  

**Matt Garrish:** it does strike me as strange that RS says you must support all of these properties, but we're also talking about how these are being phased out.  

**Dave Cramer:** we do have a note about this, but it's in the main section rather than the appendix.  
… i'll post a link.  

> *Dave Cramer:* See [Section on prefixed CSS properties in the core document](https://w3c.github.io/epub-specs/epub33/core/#sec-css-prefixed).

**Ivan Herman:** i propose to put this in the main text, as normative text.  

**Dave Cramer:** i'm opposed to that. I think what we have is good enough. Given how CSS works, and that people have legitimate reason to use these prefixes, I don't think we make a _SHOULD NOT_ statement.  

> *Bill Kasdorf:* Is "as the Working Group does not anticipate supporting them in the next major version of EPUB" still the case? Probably, because of "major version"?.

**Brady Duga:** i'm now worried that even the should in the note is too strong.  
… older RS exist that don't support the unprefixed properties, and we're telling authors not to use the prefixes. So are we asking authors to have knowledge of which RS will work with their epub, and which won't?.  
… are we telling authors that they need to do their own research, when they already have a way of making it work everywhere?.  

**Dave Cramer:** we say that they _SHOULD_ use the unprefixed ones, but we don't say they _SHOULD NOT_ use the prefixed one....  

**Charles LaPierre:** sounds like the unprefixed is a must, but authors may add in these prefixes for backwards compat with older RS, right?.  

**Dave Cramer:** right now RS spec says RS _MUST_ support these, right?.  

**Matt Garrish:** yes.  

**Dave Cramer:** and for the reasons we've mentioned I don't think this should change.  
… in general, stuff like this is easy. You're just aliasing something. Browsers know how to do this, do it all the time..  
… no real burden on RS.  
… and i'm uncomfortable saying RS must support, but authors must not use it.  

**Brady Duga:** i don't think that's the situation.  
… if i were to advise someone writing an epub now to get their epub to work on the widest range of RS, i would say include both prefixed and non-prefixed.  
… unless you really want to do the work to limit which RS your epub will be compatible with, or you want to do the analysis on different RS.  

**Ivan Herman:** i see the must support in RS, and grudgingly I agree. For content, we say you may use the prefixed properties..  
… right now I read the content doc to say that you MUST use the prefixes, and I think that is too much.  

**Dave Cramer:** so this would be a normative _MAY_?.  

**Ivan Herman:** yes.  
… you may use prefixed properties in so and so situation.  

**Brady Duga:** i almost feel like if we are giving advice to content authors, then we should make it a _SHOULD_.  

**Matt Garrish:** going back to the CSS section, we are saying that you _MUST_ support these properties, but you aren't required to support the CSS modules that they are part of?.  
… is this inconsistent?.  

**Ivan Herman:** ouch.  

**Dave Cramer:** looking at snapshot 2021, writing modes is in core.  
… i'd have a difficult time telling RS they don't have to support CSS text 3.  

**Brady Duga:** i know we cannot remove these properties, we need them to support vertical texts.  

**Dave Cramer:** okay, so consensus is that we need tests, that these aren't going away.  
… no consensus yet on what advice/statement should be in the core spec.  
… do we want to have someone propose different text for 3.3.1.3?.  
… can we do this working out of the language in the issue?.  

**Wendy Reid:** writing the tests will probably help.  
… if the person who writes the tests sees that the properties are more or less supported it will inform what we say.  

**Ivan Herman:** so do we have a test writer?.  

**Wendy Reid:** i can do it.  

**Dave Cramer:** okay, sounds like we have a plan to make progress.  

**Ivan Herman:** sorry to have raised this so late in the process.  

</details>
