### ISSUE TITLE
'duration' value in MO and TTS

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#2007]
[§ 7.3.5.2 of the content document](https://www.w3.org/TR/epub-33/#sec-mo-package-metadata) says that  each MO document _MUST_ have a duration value in the package document (via the [`media:duration`](https://www.w3.org/TR/epub-33/#sec-duration) property) and, furthermore, the duration for the whole EPUB Publication _MUST_ also be set.

On the other hand the [section on TTS in the RS document](https://www.w3.org/TR/epub-rs-33/#sec-text-to-speech) says:

> The Media Overlay text element's lifespan corresponds to the rendering time of the associated speech synthesis. The implicit duration of the text element (and by inference, of the parent par element) is therefore determined by the execution of the Text-to-Speech engine, and cannot be known at authoring time.

I.e., setting the (required) duration values in the package document sounds, in this case, quite meaningless.

Recognizing that the TTS is not a major usage of MO, I would not think we should change the aforementioned normative requirements at this point. Maybe we can just add some words in the TTS section, acknowledging that the duration values may be approximative. Ie, add something like this to the end of that paragraph:

> This also means that the `duration` values set in the package document at authoring time may be considered as approximative only, and should be considered as such by the Reading System.

cc @wareid @dauwhe @mattgarrish @dlazin @marisademeglio

**Comment by OriKuttner** [comment]
Why not declare it as SHOULD and not MUST?

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by dauwhe** [comment]
I think we should retain MUST for the duration of media overlays where pre-recorded audio is available. This is critical metadata for any sort of audio book. 

I guess the question is about media overlays WITHOUT pre-recorded audio? Is this a common-enough use case to worry about?

**Comment by iherman** [comment]
> I think we should retain MUST for the duration of media overlays where pre-recorded audio is available. This is critical metadata for any sort of audio book.
> 
> I guess the question is about media overlays WITHOUT pre-recorded audio? Is this a common-enough use case to worry about?

The feedback I got when creating TTS tests is that this is not a common use case. That is why I agree that we should not change the normative text, just put a minor explanation into the TTS section.

**Comment by marisademeglio** [comment]
> The feedback I got when creating TTS tests is that this is not a common use case. That is why I agree that we should not change the normative text, just put a minor explanation into the TTS section.

This makes sense to me, using your [proposed wording](https://github.com/w3c/epub-specs/issues/2007#issue-1148125572) above. 

I remember originally, `duration` was included as a reading system convenience, to save the trouble of calculating it at runtime (which I think would be equally prone to inaccuracy for TTS cases). As an aside, this is the same reasoning behind including it for the whole book as well as for each chapter -- it just makes less work for the RS.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-03-03-epub#section1) on 2022-03-03

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-03-03-epub#resolution1):  Merge PR 2027 after wording is confirmed, and close issue 2007.***

<details><summary><i>View the transcript</i></summary>

### 1. 'duration' value in MO and TTS (issue epub-specs#2007)

_See github issue [epub-specs#2007](https://github.com/w3c/epub-specs/issues/2007)._




**Dave Cramer:** Duration values in TTS.  

_See github pull request [epub-specs#2027](https://github.com/w3c/epub-specs/pull/2027)._




**Dave Cramer:** see issue and pull request.  
… historically we required a duration value for MO, but there is a question about what happens when there is no accompanying audio.  
… which means TTS will render the paragraph.  
… We are acknowledging it isn't common, but we need to cover it in the spec.  
… Matt, summary?.  

**Matt Garrish:** Not much to say, but the spec is a little wordy/redundant.  
… I suggest shortening, but overall am happy.  

**Dave Cramer:** Some comment about making the duration a 'should', but I am against that.  

**Matt Garrish:** agreed. I am not even sure how common TTS is.  

**Dave Cramer:** And you won't have MO if you are relying on TTS anyway.  

**Wendy Reid:** Using MO for TTS is pretty much overkill.  
… European A11y act requires TTS in RSes, so TTS will be more common.  

**Matt Garrish:** We did TTS previously, but not as MO. Seems like this is more theoretical than anything. Happy to leave as is.  

**Murata Makoto:** DAISY in Japan has MO always, but it is pre-recorded.  

**Dave Cramer:** We will clean up the PR and close the issue.  

> **Proposed resolution: Merge PR 2027 after wording is confirmed, and close issue 2007.** *(Wendy Reid)*

> *Matt Garrish:* +1.

> *Dave Cramer:* +1.

> *Toshiaki Koike:* +1.

> *Wendy Reid:* +1.

> *Shinya Takami (高見真也):* +1.

> *Masakazu Kitahara:* +1.

> *Zheng Xu (徐征):* +1.

> *Brady Duga:* +1.

> *Dan Lazin:* +1.

> *Murata Makoto:* +1.

> ***Resolution #1: Merge PR 2027 after wording is confirmed, and close issue 2007.***

</details>
