### ISSUE TITLE
Contradiction with fallback requirements

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2010]
In the manifest fallbacks section we say:

> EPUB Creators MAY reference Foreign Resources in contexts in which an intrinsic fallback cannot be provided (e.g., directly from [spine](https://w3c.github.io/epub-specs/epub33/core/#dfn-spine) [itemref elements](https://w3c.github.io/epub-specs/epub33/core/#elemdef-spine-itemref); from [[HTML](https://w3c.github.io/epub-specs/epub33/core/#bib-html)] img, iframe and link elements in [XHTML Content Documents](https://w3c.github.io/epub-specs/epub33/core/#dfn-xhtml-content-document); and from `@import` rules in CSS Style Sheets). EPUB Creators MUST provide manifest fallbacks in such cases.

https://w3c.github.io/epub-specs/epub33/core/#sec-foreign-restrictions-manifest

But in 3.1..4..4 we say that `link` is exempt from fallback requirements.

https://w3c.github.io/epub-specs/epub33/core/#sec-xhtml-fallbacks

And we also exempt fonts from fallback requirements. That doesn't cover all the uses of `@import`, but it makes the "must" not always applicable.

In any case, we should fix the parenthetical to better reflect the accommodations we allow elsewhere.

**Comment by iherman** [comment]
>
> But in 3.1..4..4 we say that `link` is exempt from fallback requirements.
> 

But this is listed in the quote above, isn't it? It says "img, iframe and link elements in XHTML..."

(by the way, I believe we should use Oxford commas, ie, it should be "iframe, and link elements" :-)

**Comment by mattgarrish** [comment]
> But this is listed in the quote above, isn't it? It says "img, iframe and link elements in XHTML..."

Right, but then it says in these cases you MUST provide a manifest fallback in the next sentence. That's what's false.

**Comment by mattgarrish** [comment]
We probably only need to fix the latter sentence, though, since the first statement is correct on its own.

But how do we avoid a vague "except where allowed by this specification"? Do we have to list where the exceptions are?

**Comment by iherman** [comment]
> > But this is listed in the quote above, isn't it? It says "img, iframe and link elements in XHTML..."
> 
> Right, but then it says in these cases you MUST provide a manifest fallback in the next sentence. That's what's false.

☹️
