### ISSUE TITLE
AccessModeSufficient Example

### ISSUE THREAD

**Issue by clapierre** [mattgarrish/epub-revision#2016]
In this Example

> 9.3 AccessModeSufficient Example 7
> 

> ```
>  <meta property="schema:accessModeSufficient">
>      textual
>  </meta>
> 
> ```

I think we also need to include, as it implies if a book with all images described is only “textual”.
Add:
```
<meta property="schema:accessModeSufficient">
    visual,textual
</meta>
```

**Comment by wareid** [comment]
@clapierre we have an example like this twice already in that section, if all three examples are the same access modes, should we not just re-write the entire section to simplify to that?
