### ISSUE TITLE
Adding a note to the section on OCF URL resolutions

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#2023]
The specification disallows, in the [section on URLs in OCF](https://w3c.github.io/epub-specs/epub33/core/#sec-container-iri) the usage of URLs like `/root/relative/urls` or `../../../crazy/path/urls`. This is done through the statement

> In the [OCF Abstract Container](https://w3c.github.io/epub-specs/epub33/core/#dfn-ocf-abstract-container), any URL string MUST be an [absolute-URL-with-fragment-string](https://url.spec.whatwg.org/#absolute-url-with-fragment-string) or a [valid-relative-container-URL-with-fragment string](https://w3c.github.io/epub-specs/epub33/core/#dfn-valid-relative-container-url-with-fragment-string).

The fact that this is restricted has been around for a while, and reflects the current status on RS implementations. However, to realize this is the case requires to either some links to the URL spec, or follow through the algorithm that precedes that statement. Both are a difficult read.

Maybe we should add an editorial note (or extend the note that follows this statement) making this restrictions explicit.

**Comment by rdeltour** [comment]
+1 on extending or rephrasing the note.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-03-03-epub#section2) on 2022-03-03

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 2. Adding a note to the section on OCF URL resolutions (issue epub-specs#2023)

_See github issue [epub-specs#2023](https://github.com/w3c/epub-specs/issues/2023)._




**Dave Cramer:** Major rewrite of OCF to clarify URLs.  
… Partly to help clarify where relative URLs could reach (that is, not out of the package).  
… First issue is to clarify in simple language what is legal now.  
… I am in favor of clarifying.  

**Dan Lazin:** Not sure what Ivan wants.  
… Is he asking for an example? Or something else?.  

**Dave Cramer:** I think an example of two explaining why these things are bad makes sense.  

**Matt Garrish:** I think Ivan wants some plain English explaining what all this means without having to understand the processing model.  

**Dave Cramer:** Maybe just "you can't use URLs like this and that", etc.  

**Murata Makoto:** I am concerned between discrepancies our spec and whatwg.  
… Which could change any time.  

**Dave Cramer:** This is a non-normative section.  

**Murata Makoto:** I am concerned with the entire section. Maybe a new issue is needed?.  

**Matt Garrish:** This is epub specific to handle the case of the virtual container.  

**Brady Duga:** I think when we were looking at this, I don't think we're changing anything the URL spec says.  
… we're putting some constraints on behaviours of types of URLs you can use as base.  
… it is still worth you going through it.  

**Dave Cramer:** It looks messy because it is a hard problem and it very tricky to fully explain (using formal language).  
… This is our best attempt to use the URL spec language and concepts to define what we want.  
… But please do review and file issues.  

**Murata Makoto:** And this issue would and non-normative language?.  

**Dave Cramer:** Yes.  

**Wendy Reid:** Yes.  

**Dave Cramer:** Not really ready to have a resolution - someone needs to add language.  

**Murata Makoto:** This is not the first time I have encountered this problem, and specifying it is very difficult.  

</details>
