### ISSUE TITLE
Remove unnecessary nesting in package doc section

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2032]
The [Package Document section](https://w3c.github.io/epub-specs/epub33/core/#sec-package-doc) currently consists of only two subsections: Overview and Package Document Definition.

But is it really necessary to have an extra subsection called "Package Document Definition" when there's only an overview along with it?

Removing it would help pull back the deep nesting in 2.3 at least a little (5 levels at the deepest instead of 6).

**Comment by iherman** [comment]
I presume what you mean is something like:

- 2.3 Package document definition
- introduction (non-normative)
- namespace (the current one paragraph in 2.3.2)
- parsing URLs in the package document (current 2.3.2.1)
- etc.

The structure would be roughly like the current 6.1.

Yes, that could work for me.
