### ISSUE TITLE
Allow NCX doctype external identifier?

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2045]
The doctype was allowed in EPUB 2:

> `<!DOCTYPE ncx PUBLIC "-//NISO//DTD ncx 2005-1//EN" "http://www.daisy.org/z3986/2005/ncx-2005-1.dtd">`

We don't have an exception for it in Appendix B, though, so it would still be invalid in EPUB 3 even after the loosening for SVG/MathML.

I don't know how much it was used in EPUB 2, but should we add to simplify any porting forward of content?

**Comment by dauwhe** [comment]
I'm a bit torn. I hope we make the NCX so inconvenient that it disappears. But allowing standard DTDs also makes sense.

**Comment by mattgarrish** [comment]
Ya, I don't think allowing the doctype will change much either way, though. Who's going to read an appendix on external identifiers? 😉 

The more likely outcome is we start getting issues in the epubcheck tracker complaining that epubcheck is allowing doctypes in svg but not in the ncx.
