### ISSUE TITLE
Are these statements about creators/contributors normative?

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2054]
Should these keywords be lowercase:

> The creator element SHOULD contain the name of the creator as EPUB Creators intend Reading Systems to display it to users.

> If an EPUB Publication has more than one creator, EPUB Creators SHOULD specify each in a separate creator element.

> EPUB Creators SHOULD represent secondary contributors using the [contributor element](http://localhost:120/core/#sec-opf-dccontributor).

They seem like best practices, as they can only ever be verified by the author.

**Comment by mattgarrish** [comment]
There's another statement like this for subjects:

> EPUB Creators SHOULD set the [value](http://localhost:120/core/#dfn-value) of the element to the human-readable heading or label, but MAY use a code value if the subject taxonomy does not provide a separate descriptive label.

Seems like more authoring best practice.

**Comment by dauwhe** [comment]
> > The creator element SHOULD contain the name of the creator as EPUB Creators intend Reading Systems to display it to users.
> 
> > If an EPUB Publication has more than one creator, EPUB Creators SHOULD specify each in a separate creator element.
> 
> >

These two statements often contradict one another. I might want the author byline to be displayed as "James Patterson with Ned Rust" or something like that. 

Agree on all of these that they should not be formal SHOULDs. These are suggestions for good practices.

**Comment by mattgarrish** [comment]
Ya, I'm trying to draw a line between what are technical requirements of the specification and what are authoring best practices (reviewing the spec now as part of mapping out what epubcheck verifies).

If we require a certain kind of value, that's fine to enforce, but these are all general recommendations. Ideally, they'd be an authoring guide for maximal interoperability, but in any case they shouldn't be normative statements.

**Comment by iherman** [comment]
I agree with the proposed changes...
