### ISSUE TITLE
Embedded resources in the spine

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2057]
This statement sounds convincingly normative on first read:

> Embedded Publication Resources (e.g., via the [[HTML](https://www.w3.org/TR/epub-33/#bib-html)] [iframe](https://html.spec.whatwg.org/multipage/#the-iframe-element) element) must not be listed in the spine.

I was going to suggest this should have a capital "MUST NOT", but why do we care? If you want to also put an iframed document into the spine as a non-linear document, that seems fine.

In older versions of the specification, this used to say "do not have to be listed". I think this passive advice is better than using either "must" or "should" here, even in their non-normative senses.

**Comment by iherman** [comment]
> I was going to suggest this should have a capital "MUST NOT", but why do we care? If you want to also put an iframed document into the spine as a non-linear document, that seems fine.

+1

> In older versions of the specification, this used to say "do not have to be listed". I think this passive advice is better than using either "must" or "should" here, even in their non-normative senses.

+1

**Comment by bduga** [comment]
I *think* we made this change intentionally, but a quick search isn't showing me any documentation to support that. I would like to understand the reasoning for the change before switching back. That said ... I have no idea what this is telling me. What are "Embedded Publication Resources"? Generally we use embedded to mean "not in a separate file".

**Comment by bduga** [comment]
I dug through the history some more (I really hate git) and it looks like the change was made in [2c19b77d0](https://github.com/w3c/epub-specs/commit/2c19b77d0) which is an editorial only pass in pull #1658. So I guess there was no explicit decision to make this a hard requirement. I still don't know what embedded publication resources are, but I support the change back.

**Comment by mattgarrish** [comment]
> So I guess there was no explicit decision to make this a hard requirement.

No, it was changed as part of cleaning up a lot of the "can", "cannot", "might" stuff now that we can use lowercase words without invoking the dreaded RFC2119.

I don't remember making that specific change, but I clearly mistook the "do not have to" for a "must not" workaround.

> I still don't know what embedded publication resources are, but I support the change back.

It's playing off [HTML embedded content](https://html.spec.whatwg.org/multipage/dom.html#embedded-content-2). I'm not sure why this matters for the spine, but I guess there's no harm in saying it. Sounds like we maybe thought people might get confused with the manifest all-in requirement?

But we drew a distinction for SVG between embedding by reference (what's meant here) and by inclusion (what you're describing), so it's not that far off. Just not as precise.

**Comment by bduga** [comment]
I think there was concern that since html content in an iframe is kind of in the primary reading order it would need to be listed in the spine?  ¯\_(ツ)_/¯

**Comment by mattgarrish** [comment]
I found the issue where it got added: https://github.com/w3c/epub-specs/issues/611

Unfortunately, it looks like the discussion around it went on in calls. I do remember the confusion around hyperlinked documents having to be in the spine, but not how that related to adding the final paragraph.

You can't link into an iframe, or was this maybe added back when that `seamless` attribute was still kicking around? Did it allow you to link into the dom of the embedded document? Still, that would be a very specialized case not warranting such a broad statement (and no long applicable since the attribute went the way of the dodo).

**Comment by mattgarrish** [comment]
Here's a little bit from the minutes:

> This is re: whether docs in iframe need to be in spine. This explicitly says that linking means hyperlinked docs, not another interpretation of link (e.g. src).
> Final point is that contents within iframes are not required to be in spine (but may be).

Looking back at 3.0.1, we said documents that are "linked to" have to be in the spine. That's what the confusion was about, but changing those to "hyperlinked to" probably solves the problem on its own. I don't think you can confuse a src attribute with hyperlinking a resource.

I'm fine either dropping the sentence entirely or reverting it back to its old wording.

If we keep the old wording, maybe the example in parentheses could link to the html definition of embedded content rather than just list `iframe`.

**Comment by iherman** [comment]
> I'm fine either dropping the sentence entirely or reverting it back to its old wording.

Re-reading the current section it is fairly clear that we are talking about hyperlinking, and the text actually refers to `<a>` element (and some other situation) to explain what they are. My impression is that this sentence is the source of more confusion than good. In my view: nuke it :-)
