### ISSUE TITLE
epub:type restriction that's outlived its usefulness

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2070]
These statements date from a time when we thought assistive technologies might use epub:type semantics like ARIA roles:

> The inflected semantic MUST express a subclass of the semantic of the carrying element. In the case of semantically neutral elements, such as the [HTML] [div](https://html.spec.whatwg.org/multipage/#the-div-element) and [span](https://html.spec.whatwg.org/multipage/#the-span-element) elements, the inflected semantic MUST NOT attach a meaning that is already conveyed by an existing element (e.g., that a div represents a paragraph or section).

We have recommendations on what elements to use the semantics on in the structure vocabulary, but these have never been enforced and were always meant as guidance. In other words, they don't even bear out these requirements.

I don't see the harm in making these statements informally, so switch these to lowercase should/should not.

**Comment by mattgarrish** [comment]
It might be worth adding to the end an extra clarification that the semantics don't do anything, so make it:

> The inflected semantic should express a subclass of the semantic of the carrying element. In the case of semantically neutral elements, such as the [HTML] [div](https://html.spec.whatwg.org/multipage/#the-div-element) and [span](https://html.spec.whatwg.org/multipage/#the-span-element) elements, the inflected semantic should not attach a meaning that is already conveyed by an existing element (e.g., that a div represents a paragraph or section), as these semantics are not substitutes for native markup and doing so may diminish the accessibility of EPUB Publications.

The latter sentence almost sounds like it could be normative, except if you use ARIA roles on the elements then also putting epub:types on them likely doesn't impact accessibility.

**Comment by iherman** [comment]
> It might be worth adding to the end an extra clarification that the semantics don't do anything, so make it:
> 
> > The inflected semantic should express a subclass of the semantic of the carrying element. In the case of semantically neutral elements, such as the [HTML] [div](https://html.spec.whatwg.org/multipage/#the-div-element) and [span](https://html.spec.whatwg.org/multipage/#the-span-element) elements, the inflected semantic should not attach a meaning that is already conveyed by an existing element (e.g., that a div represents a paragraph or section), as these semantics are not substitutes for native markup and doing so may diminish the accessibility of EPUB Publications.
> 
> The latter sentence almost sounds like it could be normative, except if you use ARIA roles on the elements then also putting epub:types on them likely doesn't impact accessibility.

I think this sentence, without normative elements, would be fine.

(We already have a note that says that `epub:type` is not for accessibility, actually, so I was not sure that the new clause is really necessary, but I guess it does not harm...)

**Comment by mattgarrish** [comment]
> We already have a note that says that `epub:type` is not for accessibility

Ya, I was getting pretty tired around the time I was logging these. Looking at it again this morning, I wonder if we can do without this paragraph entirely?

What might be better to do is add a bit more explanation to the note above about what it means that they are not roles -- that putting these semantics on elements does not change them in any way (e.g., using list or listitem will not magically make lists out of semantically neutral elements).

I'll see what I can do when I open a PR.

**Comment by iherman** [comment]
> > We already have a note that says that `epub:type` is not for accessibility
> 
> Ya, I was getting pretty tired around the time I was logging these. Looking at it again this morning, I wonder if we can do without this paragraph entirely?

Yes 😀


> 
> What might be better to do is add a bit more explanation to the note above about what it means that they are not roles -- that putting these semantics on elements does not change them in any way (e.g., using list or listitem will not magically make lists out of semantically neutral elements).
> 
> I'll see what I can do when I open a PR.

👍
