### ISSUE TITLE
Metadata property field explanations

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2073]
The meta properties vocabulary has this explanation at the beginning:

> In each property definition, the Allowed values field indicates the expected type of value (using [[XMLSCHEMA-2](https://w3c.github.io/epub-specs/epub33/core/#bib-xmlschema-2)] datatypes), the Cardinality field indicates the number of times the property MAY be attached to another property, and the Extends field identifies the properties it MAY be attached to.

This doesn't appear again until the manifest properties vocabulary, but in this one it confusingly says cardinality is the number of times a property MUST appear in the package document (can you have a must for 0?).

I'm wondering, though, if we should make this an informative explainer section for all the vocabularies, as it's odd how it comes and goes? (A relic of these all being in separate documents and the prose not getting copied around, undoubtedly.)

**Comment by iherman** [comment]
> I'm wondering, though, if we should make this an informative explainer section for all the vocabularies, as it's odd how it comes and goes? (A relic of these all being in separate documents and the prose not getting copied around, undoubtedly.)

That was also my reaction. This should go to the top, ie, [§D](https://w3c.github.io/epub-specs/epub33/core/#app-vocabs). It should be a 'union' of all these: some blocks used the 'Allowed' field, others "Applied to", but that is all right.

As for the _MUST_ or _MAY_ for the cardinality value: I think setting them with a single statement is awkward. Maybe we should be a bit more specific, something like:

> The Cardinality field expresses a constraint that the number of occurences of the propery MUST comply to.

(Or something along these lines).

**Comment by mattgarrish** [comment]
> some blocks used the 'Allowed' field, others "Applied to", but that is all right.

Ya, a quirk of the manifest properties is that they are applied to certain resources that meet their definitions, while the other more general metadata properties are allowed to "extend" properties through refinement (or apply to the publication if not refines attribute).

I don't think there's any way to harmonize these under a single field name, and definitely no way to avoid two explanations, so not worth the effort.

**Comment by iherman** [comment]
> I don't think there's any way to harmonize these under a single field name, and definitely no way to avoid two explanations, so not worth the effort.

Oh absolutely; sorry if it was unclear, I did not even think about creating a common term. I just said that both terms should be listed in the common set of explanations.
