### ISSUE TITLE
Another RS requirement in the authoring doc

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2074]
This one slipped through as it uses "user agent" instead of reading system:

> Previous versions of EPUB 3 used additional values of -epub-text-orientation. User agents MUST interpret these values according to the following table:

https://w3c.github.io/epub-specs/epub33/core/#sec-css-prefixed-writing-modes-text-orientation

This para and the table below should be in the other document.

(And I'm done my review! 😄)

**Comment by iherman** [comment]
This sentence, and the table underneath, is not _fundamentally_ different _semantically_ from the [table in §E.1.3](https://w3c.github.io/epub-specs/epub33/core/#sec-css-prefixed-writing-modes-text-combine). In both cases they define some sort of an equivalence of terms/values. On the other hand, the text in §E.1.3. says:

> The following table shows how to map from the prefixed versions to the current CSS versions.

For which I could have used a similar terminology like "User agent MUST interpret these properties according the following table"

Furthermore, most (all?) of the prefixed property values have a simple version of their equivalence saying

> This is a prefixed version of the @@@@ property.

What I try to say that if we move that statement and table into the RS document, for consistency's sake we would have to move/copy many more. I presume that would either mean creating a new appendix in the RS doc, or add the whole thing to [§E.4.3](https://w3c.github.io/epub-specs/epub33/rs/#sec-css) (which would bloat that section for that topic...)

So, if all this is true, I think reformulating the sentence and the table along the lines of §E.1.3, without using the term "User Agent" would work. That is the minimal and sufficient change imho...

**Comment by mattgarrish** [comment]
Ya, that's fine, too. The RS spec already has a requirement to support the prefixed properties, so if the statement can be reworded so it isn't requiring something of reading systems, but explaining what else exists, I don't see that being problematic.

**Comment by mattgarrish** [comment]
Since you already have a plan for this one, do you want to open a PR for it @iherman ? 😉

**Comment by iherman** [comment]
See #2110 for the PR
