### ISSUE TITLE
Two properties in 6.1.5 of EPUB 3.3 look like tautologies

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2075]
Two properties in [6.1.5 URLs in the OCF Abstract Container](https://w3c.github.io/epub-specs/epub33/core/#sec-container-iri) look like tautologies to me.

The result of [parsing](https://url.spec.whatwg.org/#concept-url-parser) "/" with the [container root URL](https://w3c.github.io/epub-specs/epub33/core/#dfn-container-root-url) as [base](https://url.spec.whatwg.org/#concept-base-url) is the [container root URL](https://w3c.github.io/epub-specs/epub33/core/#dfn-container-root-url).
The result of [parsing](https://url.spec.whatwg.org/#concept-url-parser) ".." with the [container root URL](https://w3c.github.io/epub-specs/epub33/core/#dfn-container-root-url) as [base](https://url.spec.whatwg.org/#concept-base-url) is the [container root URL](https://w3c.github.io/epub-specs/epub33/core/#dfn-container-root-url).

I learned from Romain that these do not always hold.  But I would like to see a note explaining why these properties do not always hold and what restrictions we are imposing by having these properties.

**Comment by iherman** [comment]
@murata2makoto can you look at #2082 to see if it answers to your issue?
