### ISSUE TITLE
valid-relative-container-URL-with-fragment string in EPUB 3.3

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2076]
The term "valid-relative-container-URL-with-fragment string" appears in [6.1.5](https://w3c.github.io/epub-specs/epub33/core/#sec-container-iri) in EPUB 3.3.  I did not immediately realize that this term is specific to EPUB.  I think that adding "ocf" somewhere in this term will make this point clearer.

**Comment by iherman** [comment]
Would "ocf-relative-container-URL-with-fragment string" work? @rdeltour ?

**Comment by rdeltour** [comment]
> Would "ocf-relative-container-URL-with-fragment string" work?

It sounds slightly redundant as "ocf" and "container" kinda mean the same thing. What about s/container/ocf/ in the current term, which would become: "valid-relative-ocf-URL-with-fragment string"?

**Comment by iherman** [comment]
> > Would "ocf-relative-container-URL-with-fragment string" work?
> 
> It sounds slightly redundant as "ocf" and "container" kinda mean the same thing. What about s/container/ocf/ in the current term, which would become: "valid-relative-ocf-URL-with-fragment string"?

That works for me.

**Comment by iherman** [comment]
@murata2makoto can you look at #2081 to see if it answers your issue?
