### ISSUE TITLE
Are percent-encoded code points allowed as part of file name? 

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2077]
SOLIDUS: / (U+002F) is not allowed to occur within a file name, for example.  But if it is percent-encoded, is it allowed?

**Comment by iherman** [comment]
[File names](https://w3c.github.io/epub-specs/epub33/core/#sec-container-filenames) are a series of UTF-8 encoded Unicode characters. [Percent encoding](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding) is only defined for URL-s.

You can, therefore, have a file name of the form `A%2FB`, but that does not mean what you expect; its conversion to a URL would yield `A%252FB` (`%25` is the percent encoded version of the `%` character).

**Comment by murata2makoto** [comment]
>its conversion to a URL would yield A%252FB (%25 is the percent encoded version of the % character).

Does the sentence "The [content URL](https://w3c.github.io/epub-specs/epub33/core/#dfn-content-url) of a file or directory in the [OCF Abstract Container](https://w3c.github.io/epub-specs/epub33/core/#dfn-ocf-abstract-container) is the result of [parsing](https://url.spec.whatwg.org/#concept-url-parser) the file's [File Path](https://w3c.github.io/epub-specs/epub33/core/#dfn-file-path) with the [container root URL](https://w3c.github.io/epub-specs/epub33/core/#dfn-container-root-url) as [base](https://url.spec.whatwg.org/#concept-base-url)." do the  conversion?

**Comment by iherman** [comment]
Yes. The parsing step does that, per the URL spec.
