### ISSUE TITLE
Misplaced example in FXL

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#2087]
[Example 50](https://w3c.github.io/epub-specs/epub33/core/#fxl-ex4) on overriding the global spread behaviour should be moved into the relevant section: [5.2.2.4 Spread placement](https://w3c.github.io/epub-specs/epub33/core/#page-spread).

**Comment by mattgarrish** [comment]
Are you sure about this? It looks exactly the same as Example 52, except that one's setting a plate placement, so would be redundant to have them together.

I never fully grok all these fxl properties, but doesn't page-spread-right override rendition:spread=auto and indicate to create a two page spread? That seems in keep with the section, although not clear it's happening from the text.

**Comment by iherman** [comment]
> Are you sure about this? It looks exactly the same as Example 52, except that one's setting a plate placement, so would be redundant to have them together.

I agree it would be redundant. 

The reason I have problems with the current setting of Example 50 is that it uses a feature (`page-spread-right`) which is not yet been defined, ie, the reader can be messed up hitting an unknown feature. 

Actually, the possibly better alternative is to keep the example where it is, but remove the `page-spread-right` property from the `itemref` (and modify the caption accordingly). The essence of the example is that the individual item can declare itself to be `pre-paginated` although the publication itself is, in general, reflowable (and that is editorially fine, because that feature is defined in the earlier section) and that it would automatically inherit the global setting for spread. As you say, example 51 may then state that the spread can also be controlled on a specific item.
