### ISSUE TITLE
"does not incorporate" the reserved strings (in custom attributes) is a bit vague

### ISSUE THREAD

**Issue by rdeltour** [mattgarrish/epub-revision#2095]
EPUB 3.3. RS section [4.1.17 Custom Attributes](https://www.w3.org/TR/2022/WD-epub-rs-33-20220317/#sec-xhtml-custom-attributes) says:

> vendors MAY define custom attributes for use in [XHTML Content Documents](https://www.w3.org/TR/epub-33/#dfn-xhtml-content-document) provided they are from a foreign namespace, which is defined as a namespace [[XML-NAMES](https://www.w3.org/TR/2022/WD-epub-rs-33-20220317/#bib-xml-names)] that does not incorporate either of the following strings in its [domain](https://url.spec.whatwg.org/#concept-domain) [[URL](https://www.w3.org/TR/2022/WD-epub-rs-33-20220317/#bib-url)]:
>
> * w3.org
> * idpf.org

This is a bit vague. Does it mean `foow3.orgbar.example.com` is disallowed? Or only subdomains of `w3.org`, or only things like `prefix.w3.org.suffix`?

Can we clarify this?

**Comment by mattgarrish** [comment]
> Does it mean `foow3.orgbar.example.com` is disallowed? Or only subdomains of `w3.org`, or only things like `prefix.w3.org.suffix`?

They're all invalid as far as I remember, even if it could theoretically capture some unintended cases. It was originally only to prevent trying to put idpf.org in to make the extension appear to have some sort of blessing of the organization, which would be really hard to find in an accidental example like your first.

w3.org is a little more generic, but I suspect the chances of this ever becoming an issue are in the infinitely small range. We allowed the attributes for one vendor and I believe that vendor is still the only one that's ever used this feature. I'm fine leaving it as broad as it's always been.

**Comment by rdeltour** [comment]
> I'm fine leaving it as broad as it's always been.

Infra doesn't seem to be helpful here as it does not include a a "string contains" definition.

I think using "contain" instead of "incorporate" might make it sound a bit less ambiguous (to me only perhaps 😅). It would be more obvious that it is to be interpreted with the well-known semantics of the "contains" methods found in most string APIs.

**Comment by mattgarrish** [comment]
> I think using "contain" instead of "incorporate" might make it sound a bit less ambiguous

Fine with me.

**Comment by iherman** [comment]
What about

> vendors MAY define custom attributes for use in [XHTML Content Documents](https://www.w3.org/TR/epub-33/#dfn-xhtml-content-document) provided they are from a foreign namespace, which is defined as a namespace [[XML-NAMES](https://www.w3.org/TR/2022/WD-epub-rs-33-20220317/#bib-xml-names)] whose [domain](https://url.spec.whatwg.org/#concept-domain) [[URL](https://www.w3.org/TR/2022/WD-epub-rs-33-20220317/#bib-url)] is not a [subdomain](https://datatracker.ietf.org/doc/html/rfc1034#section-3.1) [[rfc1034]] of:
>
> w3.org
> idpf.org

**Comment by rdeltour** [comment]
Well, "is a subdomain of" is definitely not the same as "is contained in string" 😁

**Comment by iherman** [comment]
> Well, "is a subdomain of" is definitely not the same as "is contained in string" 😁

It is not but... isn't it exactly the restriction that we want to impose?

**Comment by rdeltour** [comment]
> isn't it exactly the restriction that we want to impose?

I dunno, @mattgarrish said earlier the intent was more "is contained" (I guess to forbid fishy domains like `theidpf.org` and `epub-w3.org`).

**Comment by mattgarrish** [comment]
> I guess to forbid fishy domains like `theidpf.org` and `epub-w3.org`

Right, if we're trying to prevent people from making extensions with the veneer of being endorsed by either organization, we can't limit it to subdomains of only idpf.org and w3.org.

But I also don't get too worked up over this issue. Whatever is simplest to check is fine with me, as I don't see any evidence of uptake of this feature, let alone that allowing the attributes will fork epub (that was the big concern in even allowing these).

**Comment by iherman** [comment]
> But I also don't get too worked up over this issue. Whatever is simplest to check is fine with me, as I don't see any evidence of uptake of this feature, let alone that allowing the attributes will fork epub (that was the big concern in even allowing these).

Ok. If the intention always went beyond the subdomain restriction, then I guess the current text is fine, ie, and the original question in the issue has been answered...

**Comment by rdeltour** [comment]
> Whatever is simplest to check is fine with me

EPUBCheck checks if the string contains `idpf.org` or `w3.org`. So beyond `s/incorporate/contain/` for clarity, it seems we're all good 😊

**Comment by mattgarrish** [comment]
> If the intention always went beyond the subdomain restriction

That changed more recently. We originally only banned attributes in the XHTML and OPS namespaces, because those are already owned, but this prevents collisions with all the other W3C/IDPF namespaces, as well as any phishy/spoofy sort of stuff (though it seems like a stretch to use custom attributes for evil; the risk was in forking functionality on a per-Reading System basis).

But why layer complex restrictions on the namespaces when this seems destined for "under-implemented" status anyway? The likelihood of anyone getting upset by this restriction has to be infinitesimally small whatever we choose.

**Comment by iherman** [comment]
> But why layer complex restrictions on the namespaces when this seems destined for "under-implemented" status anyway? The likelihood of anyone getting upset by this restriction has to be infinitesimally small whatever we choose.

In this case, let us do the simplest thing on Earth: nothing :-) Leave things as is.
