### ISSUE TITLE
MO "Referencing Document Fragments" should probably not refer to HTML's "target element" concept

### ISSUE THREAD

**Issue by rdeltour** [mattgarrish/epub-revision#2096]
In section ["Referencing Document Fragments"](https://www.w3.org/TR/2022/WD-epub-33-20220317/#sec-media-overlays-fragids) EPUB 3.3 says (since #1663):

> For XHTML and SVG Content Documents, the fragment SHOULD be a reference to a [target element](https://html.spec.whatwg.org/multipage/#target-element) [[HTML](https://www.w3.org/TR/2022/WD-epub-33-20220317/#bib-html)] (…)

Referring to "target element" looks wrong to me. If I understand correctly, the _target element_ is a property of a Document, defined algorithmically. So speaking about **a** _target element_ is not appropriate IMO.

HTML calls the thing identified by the fragment "[the indicated part of the document](https://html.spec.whatwg.org/multipage/browsing-the-web.html#the-indicated-part-of-the-document)". It then says that the mapping semantics depends on the document's MIME type, and for XHTML (being XML), this is defined in RFC7303, which in turns refers to the XPointer Framework.

So it looks like if we want to be precise we're back to what we wanted to avoid in #1586? 🙃

Could we maybe simplify this by saying:
> the fragment SHOULD indicate an HTML element or be an SVG Fragment Identifier, respectively

🤔

**Comment by iherman** [comment]
To reinforce the proposal of @rdeltour:

> the fragment SHOULD indicate an HTML element or be an SVG Fragment Identifier, respectively

the current formulation of the SVG part isn't o.k. either. It says:

> SHOULD be a reference to a [...] or an [SVG Fragment Identifier](https://www.w3.org/TR/SVG/linking.html#SVGFragmentIdentifiers) [[SVG](https://www.w3.org/TR/2022/WD-epub-33-20220317/#bib-svg)], respectively.

The section referred to in the SVG spec does not define an element that one can referred to; it defines what a valid fragment identifier in SVG is, which can be 

- the good old XML id value (ie, `MyDrawing.svg#MyView`)
- svg view (ie, MyDrawing.svg#svgView(viewBox(0,200,1000,1000)))
- [Media Fragments URI 1.0 (basic)](https://www.w3.org/TR/SVG/refs.html#ref-media-frags)

Ie, as far as the SVG part goes, the correct text should indeed be

> SHOULD **be** a [...] or an [SVG Fragment Identifier](https://www.w3.org/TR/SVG/linking.html#SVGFragmentIdentifiers) [[SVG](https://www.w3.org/TR/2022/WD-epub-33-20220317/#bib-svg)], respectively


So +1 to @rdeltour's proposed text; maybe with the extra proviso of the HTML being a [palpable content](https://html.spec.whatwg.org/multipage/dom.html#palpable-content-2), ie,

> the fragment _SHOULD_ refer to an HTML [palpable content](https://html.spec.whatwg.org/multipage/dom.html#palpable-content-2) [[HTML](https://www.w3.org/TR/2022/WD-epub-33-20220317/#bib-html)] or should be an [SVG Fragment Identifier](https://www.w3.org/TR/SVG/linking.html#SVGFragmentIdentifiers) [[SVG](https://www.w3.org/TR/2022/WD-epub-33-20220317/#bib-svg)]

**Comment by mattgarrish** [comment]
> maybe with the extra proviso of the HTML being a [palpable content](https://html.spec.whatwg.org/multipage/dom.html#palpable-content-2)

I don't think this will work without also including the `body` element  itself. Do we want to add that much specificity?

The word "indicate" is a little too jargony absent the use that the HTML spec assigns to it. Maybe "resolve to"?
