### ISSUE TITLE
Section 14: Accessibility in EPUB RS 3.3

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2100]
I am puzzled by [Section 14](https://w3c.github.io/epub-specs/epub33/rs/#sec-accessibility) of EPUB 3.3 RS.

First, the first paragraph looks dangerous to me.  The current wording suggests that RS implementors should care about normative specifications and nothing else as far as content rendering is concerned.  But I strongly believe that even fully-conformant RSes can have A11Y issues in content rendering.  For example, ming fonts (明朝体) cause significant problems to some dyslexic Japanese.  Fully-conformant RSes having ming fonts thus have A11Y issues in content rendering.  I can go on and on.

Second, the second and third paragraphs appear to explain why normative requirements on RS behaviors do not work well for A11Y. They look apologetic to me.  Why do we need these paragraphs?

I would like to get rid of the first, second, and third paragraphs.  Then, this section is a collection of useful hints, which are fine.

**Comment by mattgarrish** [comment]
Ya, I'm a bit ambivalent about them. They were intended to help explain the focus of the specification to get us through the horizontal review. They don't really add anything for developers.

**Comment by iherman** [comment]
Thanks @murata2makoto to force me to re-read the section :-)

I would agree that the first and second paragraphs might be superfluous. I would keep the third paragraph in a somewhat modified form, something like:

> This specification does not mandate specific user interfaces that all Reading Systems must offer. Although focused on browser acccessibility, the W3C's [User Agent Accessibility Guidelines](https://www.w3.org/TR/UAAG20/#) [[UAAG20](https://w3c.github.io/epub-specs/epub33/rs/#bib-uaag20)] provides many useful practices developers should apply to improve their Reading Systems.  The following list outlines some additional, but common areas where a lack of accessibility impacts the reading experience for users, and which are specific to Reading Systems:

which would also make the fourth paragraph superfluous, as well as the very last paragraph of the section.

This would more firmly represent the line of thoughts that we always had in the A11y work, namely to rely on the WAI work of W3C and focus, primarily, on features that are unique to, in this case, RS-s compared to browsers at large.
