### ISSUE TITLE
"The EPUB Accessibility standard" in EPUB 3.3

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2113]
The phrase "the EPUB Accessibility standard" appears in [Clause 8](https://w3c.github.io/epub-specs/epub33/core/#sec-accessibility) of EPUB 3.3.  

But the preceding paragraph has another phrase "a separate specification, [EPUB Accessibility](https://www.w3.org/TR/epub-a11y-11/#) [[EPUB-A11Y-11](https://w3c.github.io/epub-specs/epub33/core/#bib-epub-a11y-11)]".

I first thought that they are different.  Moreover, in W3C, we do not say "standard".  I propose to replace "the EPUB Accessibility standard" by "EPUB-A11Y-11".

**Comment by iherman** [comment]
Thanks @murata2makoto. Please check #2114
