### ISSUE TITLE
Example in Orientation does not show how rendition:orientation should be used

### ISSUE THREAD

**Issue by Jeffxz** [mattgarrish/epub-revision#2115]
In [the Example](https://w3c.github.io/epub-specs/epub33/core/#fxl-ex2) of Orientation segment. It has title "Specifying global landscape orientation" but the statement is more related to `rendition:spread`.
```
In this example, the content should also render without synthetic spreads.
```
However I could not find any statement or explanation regarding to "rendition:orientation" in this example.

I also wonder how we should tell reading system about how to deal with `rendition:orientation"landscape"`

**Comment by iherman** [comment]
I think you are right with the example. I will propose a change.

> I also wonder how we should tell reading system about how to deal with rendition:orientation"landscape"

I am not sure what you mean.

**Comment by Jeffxz** [comment]
Thanks for fixing the example.

**Comment by Jeffxz** [comment]
> > I also wonder how we should tell reading system about how to deal with rendition:orientation"landscape"
> 
> I am not sure what you mean.

If an epub with rendition:orientation specified as "landscape" then how should a reading system display on mobile (which is portrait mode by default unless rotating phone)? It is expected to force phone to landscape mode (guess almost nobody would like phone automatically rotating when displaying different book)? Or say there is a web browser displayed in a portrait display (which I usually use to read book) then how should a reading system render when creator preferred as landscape mode would also be problematic.

**Comment by iherman** [comment]
I do not know whether this is something the spec has to define; I believe this is largely up to the Reading System.

Note that I have a number of applications (not necessarily reading systems) that do force a landscape mode on my iPad, even if the tablet is locked in portrait mode. In other words, this is not unheard of (interestingly, the same application may not impose a landscape mode on my iPhone).

But, again, I am not sure that this is something to be prescribed by the EPUB spec.

**Comment by Jeffxz** [comment]
> But, again, I am not sure that this is something to be prescribed by the EPUB spec.
Yes exactly, since it might not need to be prescribed by EPUB spec I wonder anyone is using that and if it should stay in spec. It will also add difficulty to write test because we don't have a definition of behavior.
