### ISSUE TITLE
Do we still need orientation?

### ISSUE THREAD

**Issue by Jeffxz** [mattgarrish/epub-revision#2119]
As Reading System vendor I am not sure how to follow this definition of [orientation](https://w3c.github.io/epub-specs/epub33/core/#orientation). Is there anyone (or any reading system) using creator specified orientation? Do we still need it?

Having orientation would introduce difficulty of:
1. As reading system we don't know how to implement this (what to do with if creator specified as landscape mode and user is using a phone?).
2. As reading system we don't know how to test implementation following this spec.
3. Even though some Reading System might have ability to force app to rotate 90 degree on portrait device it will be confusing for end user that when only reading some book it rotated but for others it does not.

**Comment by iherman** [comment]
I believe that setting the orientation may be important, mainly for FXL documents. I do not think it is a feature that we should deprecate.

**Comment by Jeffxz** [comment]
Do we have some reading app or user cases that is actually using the orientation?

If a RS is inside web browser (say a web app) and creator expected it to display in landscape mode then the implementation can not go anywhere because reading system can not force user's web browser to rotate.

**Comment by iherman** [comment]
@Jeffxz per our charter, this is a feature that we cannot remove (we have a strong restriction on not creating backward incompatibilities). Our current approach is to get relevant entries into the test suite (hint, hint, ...😀) and, if the feature is not implemented, it gets an 'under implemented' status.

That being said: landscape vs. portrait is all about aspect ratios, I guess. Ie, without seeing all the details, it is possible for an implementation to restrict the display area to a smaller part that has a landscape or portrait aspect ratio. It won't be nice in some cases, and authors should be careful how to use that, but that is another matter.

**Comment by Jeffxz** [comment]
Thanks @iherman. Yeah, don't need to deprecate but was wondering if any actual usecase of orientation. 'under implemented' status might be helpful for preventing creator from using it.

**Comment by mattgarrish** [comment]
I know this is closed, but for the record it's a terrible property from an accessibility perspective. Having a property that locks users into an orientation assumes the user can easily turn their device. But it's one of many problems with fxl and accessibility.
