### ISSUE TITLE
Can not find statement related to example of using media query

### ISSUE THREAD

**Issue by Jeffxz** [mattgarrish/epub-revision#2120]
[This example](https://w3c.github.io/epub-specs/epub33/core/#fxl-ex1) does not seem related to any statement in [layout section](https://w3c.github.io/epub-specs/epub33/core/#layout). We might need one sentence in the layout section then put example down below as support material.

**Comment by iherman** [comment]
It includes the statement in the OPF file:

```xml
      <meta
          property="rendition:layout">
         pre-paginated
      </meta>
```

which is the topic of the section itself. We may want to point it out in the example description, though.

**Comment by iherman** [comment]
@Jeffxz see PR #2127

**Comment by Jeffxz** [comment]
perfect
