### ISSUE TITLE
Suggested edits - 2. EPUB Publications

### ISSUE THREAD

**Issue by BenSchroeter** [mattgarrish/epub-revision#2125]
2.1 Conformance Criteria:
MUST contain an [EPUB Navigation Document](https://w3c.github.io/epub-specs/epub33/core/#dfn-epub-navigation-document) that conforms to [7.5 Navigation Document Overlays](https://w3c.github.io/epub-specs/epub33/core/#sec-nav-doc).
This could be understood to mean that an EPUB Navigation Document must have an associated audio Media Overlay.

2.1.1
Para 2
"prior to distributing it" s/b "prior to submitting their publications"

Para 5
"They" s/b "EPUB Creators"
"Not following" s/b "Failure to follow"
"may lead to interoperability" s/b "may lead to interoperability problems"

2.2.1.1
Para 4
"Reading Systems support" s/b "Reading System support"

2.2.2.1
Table
First row under Media Type "Other", column 3: Change "XHTML syntax" to "XML syntax" (retain the link); add the word "for" before [HTML]

2.3.1
"Metadata — mechanisms to include and/or reference metadata" s/b "Metadata — mechanisms to include and/or reference information about the publication"

2.3.4
In the blue element definition box, add "(DEPRECATED)" after "collection [0 or more]"

2.3.5.1
In the first list item under the blue box, change "bookshelf" to "catalog"

2.3.5.3 DCMES Required Elements: spell out or link to a definition for Dublin Core Metadata Element Set

2.3.5.5
Example 23: "an 13 digit ISBN" s/b " a 13-digit ISBN"

2.3.5.7
Example 29 references metadata (lowest level) not shown in the code snippet

2.3.7.2 Remove extra " after "yes" below the second NOTE

2.3.8 
Add (Deprecated) after "Collections"

**Comment by mattgarrish** [comment]
> MUST contain an [EPUB Navigation Document](https://w3c.github.io/epub-specs/epub33/core/#dfn-epub-navigation-document) that conforms to [7.5 Navigation Document Overlays](https://w3c.github.io/epub-specs/epub33/core/#sec-nav-doc).
> This could be understood to mean that an EPUB Navigation Document must have an associated audio Media Overlay.

Ya, this is clearly a case of the wrong ID being referenced. It should be `sec-nav` not `sec-nav-doc`.

The MO definition should really have a clearer ID than `sec-nav-doc`, though. Even `sec-mo-nav-doc` would avoid an accident like this.

**Comment by mattgarrish** [comment]
I'm going to open a pull request for these against #2101 as I'm going to have to crossreference the changes here against the rewrites that PR makes.

**Comment by mattgarrish** [comment]
> "prior to distributing it" s/b "prior to submitting their publications"

I'm going to strip this entirely. It's not saying anything that shouldn't be patently obvious.

**Comment by mattgarrish** [comment]
> In the blue element definition box, add "(DEPRECATED)" after "collection [0 or more]"

This is correct as is. It's not the element that is deprecated, only the creation of new types of collections. We're not invalidating any content that may use collections the way they were defined in the old IDPF specs.

**Comment by mattgarrish** [comment]
> 2.3.5.3 DCMES Required Elements: spell out or link to a definition for Dublin Core Metadata Element Set

We hardly use DCMES anywhere. I tend to think it's needlessly opaque.

These sections are probably more simply defined as "Dublin Core Required Elements" and "Dublin Core Optional Elements" and the few other instances similarly cleaned up.

**Comment by mattgarrish** [comment]
Closing this with #2130 as merging with another branch doesn't appear to close issues.
