### ISSUE TITLE
Suggested edits - EPUB 3 Overview

### ISSUE THREAD

**Issue by BenSchroeter** [mattgarrish/epub-revision#2126]
Working Group Notes: 
Bullet 3: make [EPUB-A11Y-11] a link

2.1
Para 3
remove comma after "processing and rendering features"

First NOTE
insert "is" after "element"
change "uncertain" to "deprecated"

Change link to (https://www.w3.org/TR/epub-33/#sec-package-doc) for "section" in
"The Package Document is specified in the dedicated [section](https://www.w3.org/TR/epub-33/#sec-nav-def-hidden) of [[EPUB-33](https://w3c.github.io/epub-specs/epub33/overview/#bib-epub-33)]."

2.2.2
Para 1
"table of content" s/b "table of contents"

Para 3
Awkward sentence is difficult to parse:
"However, authors may also include the navigation document in the [spine](https://www.w3.org/TR/epub-33/#sec-spine-elem) [[EPUB-33](https://w3c.github.io/epub-specs/epub33/overview/#bib-epub-33)], which then (also) rendered making use of all the rendering possibilities." 

"which then" s/b "which is then" perhaps?

Para 4:
hidden attribute link is broken (link also broken in 4.1 Introduction paragraph 4)

2.3
metadata section should link to the section, not the element

2.6
"Web" should be lowercase throughout the document (unless in a proper noun or org/document title) to align with treatment in the main spec. There are three instances in this paragraph but should be changed globally (14 instances).

2.9
"container constrained contexts" s/b "container-constrained contexts"

3
Para 1
"EPUB 3 leverages on the features " s/b EPUB 3 leverages the features"

"use different character sets, express bidirectional text, ruby annotations, or typography" s/b "use different character sets and express bidirectional text, ruby annotations, or typography"

3.2
Para 2
"The combination of CSS Speech and inline SSML phonemes also allows fine control over ruby." ...seems random and weird here

4.1
Para 2
hyphenate "highly structured"

insert "of the publication" after "body"

4.2
Para 1
"for representing" s/b "to represent"

Delete Para 2 and following Editor's Note

4.3
Para 1

"The design center of EPUB is dynamic layout: content is typically intended to be formatted on the fly rather than being typeset in a paginated manner in advance (i.e., expecting a particular sized "page"). This core capability is useful, for example, for optimizing rendering onto different sized device screens or window sizes, and it facilitates and simplifies content accessibility." 
s/b 
"At its core,EPUB is designed for dynamic layout: content is typically intended to be formatted on the fly rather than being typeset in a paginated manner in advance. This core capability is useful for optimizing rendering onto different-sized device screens or window sizes, and it facilitates and simplifies content accessibility."

Para 2
hyphenated "highly formatted"
"They" (beginning second sentence) s/b "These techniques"

Add reference to xxl accessibility and remove Editor's Note

4.4
Para 1
delete "other" from first sentence

Para 2
"Overlays transcend the accessibility domain in their usefulness: the synchronization of text and audio as a tool for learning to read, for example, being of benefit in many circumstances."
s/b
"Beyond benefiting accessibility, overlays have other applications, e.g., synchronizing text and audio as a tool for learning to read."

A.1
Para2
"Work on a 2.0 revision of OEBPS began in parallel which was approved as the renamed EPUB 2.0 in October 2007, consisting of a triumvirate of specifications: Open Package Format (OPF), Open Publication Format (OPF) together with OCF. EPUB 2.0.1, a maintenance update to the 2.0 specification set primarily intended clarify and correct errata in the specifications, was approved in September 2010."
s/b
"Work on a 2.0 revision of OEBPS began in parallel which was renamed EPUB 2.0 in October 2007 and approved in September 2010. This revision consisted of a triumvirate of specifications: Open Package Format (OPF), Open Publication Format (OPF), and OCF. EPUB 2.0.1, which was a maintenance update to the 2.0 specification set primarily intended clarify and correct errata in the specifications."

A.2
"bringing new," s/b "adding"

"A new specification, EPUB Media Overlays was also introduced, enabling text and audio synchronization in EPUB Publications."
s/b
"A new specification for EPUB Media Overlays was also introduced, allowing for text and audio synchronization in EPUB Publications."

A.5
"reading system" should have initial caps to align with the rest of the document.

delete "returns and"

**Comment by iherman** [comment]
@BenSchroeter thanks for this, I plan to take care of this on Tuesday.

cc @mattgarrish

**Comment by iherman** [comment]
@BenSchroeter see #2155
