### ISSUE TITLE
Should we add "rendigion" prefix to "layout-pre-paginated" for overriding global spread

### ISSUE THREAD

**Issue by Jeffxz** [mattgarrish/epub-revision#2128]
In [Example 50 ](https://w3c.github.io/epub-specs/epub33/core/#fxl-ex4) and the rendition:layout item in [Package Rendering Vocabulary](https://w3c.github.io/epub-specs/epub33/core/#app-rendering-vocab) it is said to use "rendition:layout-pre-paginated" to define override in spine item. However, in the definition of [Layout Overrides](https://w3c.github.io/epub-specs/epub33/core/#layout-overrides) it only defined  "layout-pre-paginated" and "layout-reflowable". Can we make it more specific that which one should be used or if both could be used (I don't think we can assume all the creators are XML expert so we will likely have both cases in book)?

**Comment by mattgarrish** [comment]
> However, in the definition of [Layout Overrides](https://w3c.github.io/epub-specs/epub33/core/#layout-overrides) it only defined "layout-pre-paginated" and "layout-reflowable"

Yes, to use them they still need to be expressed as compact URIs (not xml namespaces) so in the properties attribute they will all (not just layout) be rendition:*.

That used to be how they were defined in 3.0.1/3.1, but we dropped the prefixes in 3.2. Not sure if that was to make them more readable or just an oversight in adding fuller definitions, but it is confusing. Agree the prefixes should all be added back.
