### ISSUE TITLE
Reading Systems MUST process the Package Document [EPUB-33 RS]

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2132]
[This requirement](https://w3c.github.io/epub-specs/epub33/rs/#sec-package-doc) does not have any tests.  I think that we lose nothing by dropping this requirement.

**Comment by iherman** [comment]
> [This requirement](https://w3c.github.io/epub-specs/epub33/rs/#sec-package-doc) does not have any tests. I think that we lose nothing by dropping this requirement.

The test suite is not yet complete, nor is it required to be complete at the time when we enter CR. This is not the only MUST statement that do not have yet any test.

Ie, this is not an acceptable argument for dropping this requirement.

**Comment by murata2makoto** [comment]
> Ie, this is not an acceptable argument for dropping this requirement.

Understood.  I am not used to the style of always embedding tests for requirements.

**Comment by iherman** [comment]
> > Ie, this is not an acceptable argument for dropping this requirement.
> 
> Understood. I am not used to the style of always embedding tests for requirements.

To be honest, this is the first time I use it, too. Note that this embedding only works on the editors' draft, and not in the published, final recommendation. It is more of a signal for the editors as well as the reviewers of, e.g., the CR, to see where we are with the level of testing.
