### ISSUE TITLE
Terminology as proper nouns

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2135]
Maybe this is heresy, but do we really need to capitalize _every_ word from the terminology _every_ time it is used?

We've effectively made proper nouns out of all the terminology for reasons that mostly elude me as this practice goes back to at least EPUB 2. Considering that the first instance of a term in a section is already linked to its definition, what does capitalizing all the words add?

From a visual perspective I've always found this jarring to read, and from an editing perspective it's always been a pain to make sure they're all capitalized.

So, painful as it may be to do, should we drop the caps?

**Comment by mattgarrish** [comment]
Searching through various other W3C specs, I haven't yet found another one that follows this practice.

Even the few that capitalize the terms in the terminology don't in the body.

**Comment by iherman** [comment]
Whatever works for improving readability is good, but I'm worried from the work it involves to change at its point:-(

**Comment by mattgarrish** [comment]
> but I'm worried from the work it involves to change at its point:-(

Probably another to leave until after we publish a CR, but it may not be as hard as it seems.

A lot of the most used ones all start with "EPUB", so we can global those out without any worry about getting a lowercase letter in the wrong spot.

There may be a way to speed the rest up with a regex that skips any with a period immediately before, or certain opening tags like p or li since those are also likely the start of sentences.

**Comment by iherman** [comment]
> Probably another to leave until after we publish a CR, but it may not be as hard as it seems.

Let us indeed leave it at that.

Note that, even in the CR phase, we are authorized to re-publish CR drafts via echidna, so this type of change can be done without further ado. We are required to go through a more formal step only if substantial changes (ie, whatever may invalidate implementation reports and/or tests) are done.

**Comment by mattgarrish** [comment]
I made up a "Status-PostCRCleanup" label for this, but if there are other tasks, like sentence-casing the headings or whitespace cleanup, maybe we should start similarly logging them rather than keeping them in the back of our heads.

**Comment by mattgarrish** [comment]
Closing with the merge of #2250 / #2248
