### ISSUE TITLE
"Network access" or "internet access"?

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2148]
https://w3c.github.io/epub-specs/epub33/rs/#sec-epub-rs-conf-cmt refers to "network access."

~All uses I'm aware of are really "internet access" (not local network). Do we expect RSes (even just some RSes, maybe for enterprise use) to support local networks, or can/should we change this to "internet access" for clarity?

**Comment by mattgarrish** [comment]
Doesn't this come from "full network access" permissions with apps?

But internet isn't the only concern, is it? Isn't there a safeguard in knowing any network activity is occuring, and being able to block it, to prevent any possible unwanted access attempts to the local network/file system?

**Comment by dlazin** [comment]
The "network access" terminology *makes sense* (if that's what we intend), but what I'm suggesting is (perhaps!) that local network access, and perhaps filesystem access (less clear because certainly needed for sideloaded books) should never be allowed, and that this section should refer only to internet access.

Put another way:
* internet access: allowable but comes with risks
* local network access: RSes should never permit?
* filesystem access: generally a bad idea but necessary for RSes that allow sideloading?

Put another another way: this section is not specific as to whether it intends to apply to all networks or really just the internet. I think it could be more specific.

**Comment by mattgarrish** [comment]
> Put another another way: this section is not specific as to whether it intends to apply to all networks or really just the internet.

I'm not sure we want to get too deep into allowing or disallowing different types of network access.

What if you host a reading system on your company portal for your internal documentation? That could be on a local network.

And where does localhost slot into the restrictions, as the network activity could be confined to the device?

I think in this case we're better off leaving it to the reading system devs to determine what specific access makes sense for their applications and what controls to put on that access.

**Comment by iherman** [comment]
> Put another another way: this section is not specific as to whether it intends to apply to all networks or really just the internet. I think it could be more specific.

In my reading, the text does say "network", i.e., apply to all networks. And I believe we should not attempt to restrict it further...

Imho, this issue could be closed without further actions...

**Comment by dlazin** [comment]
OK, closing!
