### ISSUE TITLE
What does "Error" mean?

### ISSUE THREAD

**Issue by bduga** [mattgarrish/epub-revision#2151]
In the section on [CSS prefixed properties](https://w3c.github.io/epub-specs/epub33/core/#sec-css-prefixed-writing-modes-text-combine) we have this row:

`-epub-text-combine: horizontal <number> | Error`

It isn't clear what "Error" means. Perhaps it should be changed to something clearer, like "ignored" or "no effect".

**Comment by mattgarrish** [comment]
Ya, the result is an [illegal value](https://www.w3.org/TR/CSS22/syndata.html#illegalvalues), but you can't map a property to an error.

Maybe something like "no equivalent" would be better?

**Comment by bduga** [comment]
I like "no equivalent".
