### ISSUE TITLE
Clarify "SHOULD NOT use non-Publication Resources"

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2160]
https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-manifest says:

> Reading Systems SHOULD NOT use non-[Publication Resources](https://www.w3.org/TR/epub-33/#dfn-publication-resource) in the rendering of an EPUB Publication due to the inherent limitations and risks involved (e.g., lack of information about the resource and how to process it, security risks from remotely-hosted sources, lack of fallbacks, etc.).

My understanding is that remote resources *can* be publication resources if they are listed in the manifest; therefore, I believe this is saying that Reading Systems should only render resources listed in the manifest.

It kinda reads, though, like it's saying "don't use remote resources at all" (especially because of the examples; I don't think security risks are any less if a remote resource is listed in the manifest).

Can we clarify, and limit the parenthetical to things that are different between publication resources and non-publication resources?

**Comment by mattgarrish** [comment]
> SHOULD NOT use non-[Publication Resources](https://www.w3.org/TR/epub-33/#dfn-publication-resource)

This is a prime example of our lack of complete terminology leading to weird phrasings. A "non-Publication Resource", per #2101 is now formally a "Linked Resource". They can be local or remote, but neither case is particularly safe to render.

I'll check if I caught this one in #2101 and fix if not.
