### ISSUE TITLE
Encryption word salad!

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2171]
https://w3c.github.io/epub-specs/epub33/rs/#sec-container-metainf says:

> Reading Systems MUST only decrypt data encrypted after signing before computing the digest used to validate the signature.

I am entirely unable to interpret this sentence. decrypt ... encrypted? after ... before? I would send a PR to fix but I legitimately cannot parse.

**Comment by mattgarrish** [comment]
Ya, I spun my wheels on this earlier when I was adding the linking. I forgot to mention it in the PR (will update in a sec), but what I modified this to is:

> Before computing the digest used to validate the signature in the [encryption.xml file](https://www.w3.org/TR/epub-33/#sec-container-metainf-encryption.xml) [[EPUB-33](https://cdn.statically.io/gh/w3c/epub-specs/editorial/rs-refs-links/epub33/rs/index.html#bib-epub-33)], Reading Systems MUST decrypt any data encrypted after signing — data encrypted before signing MUST NOT be decrypted.

**Comment by dlazin** [comment]
That definitely turns it back into English! Much better. I don't know much about encryption, so I can't say if it makes *conceptual* sense; it seems weird to me that you can decrypt anything without validating the signature first. Shall we merge the PR, but keep this issue open so that we can double-check the meaning with other experts at the next meeting?

**Comment by murata2makoto** [comment]
If my understanding is correct, this sentence means that signing-then-encryption is good but encryption-then-signing is bad.  I wonder if this can be reformulated as a requirement on data rather than that on EPUB RSes.

**Comment by mattgarrish** [comment]
> this sentence means that signing-then-encryption is good but encryption-then-signing is bad

I don't think it's quite that simple. My understanding is that this is sort of code for drm handling. If DRM is applied after the author has generated the signature, the reading system has to remove that before being able to verify the signature.

But if the author obfuscated fonts or a format they used has its own internal encryption capabilities, the reading system has to leave those alone.

Although this appeared in the encryption.xml section, I think I put the wrong file into the description. This looks like it should be in the signature.xml description. Yes, it's about handling encrypted data, but it's not directly about encryption itself. I'll fix that.

**Comment by mattgarrish** [comment]
I found the immediate source of this in the core spec:

> Signed resources MAY subsequently be encrypted using the Decryption Transform for XML Signature [[XMLENC-DECRYPT](https://www.w3.org/publishing/epub3/epub-ocf.html#bib-xmlenc-decrypt)]. This feature enables an application such as an OCF agent to distinguish data that was encrypted before signing from data that was encrypted after signing.

I'm going to work this into the explanation.

**Comment by mattgarrish** [comment]
This is now:

> Signature File (signature.xml)
> Before computing the digest used to validate the signature in the [signature.xml file](https://www.w3.org/TR/epub-33/#sec-container-metainf-signature.xml) [[EPUB-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)], Reading Systems MUST decrypt any data encrypted after signing — data encrypted before signing MUST NOT be decrypted.

> 
> Refer to Decryption Transform for XML Signature [XMLENC-DECRYPT] for more information about identifying data encrypted after signing.

But leaving this issue open, as requested, in case we can improve this further.

**Comment by iherman** [comment]
I went through the text, also looked at the XML Signature and Decryption specs. I have only a limited understanding of signatures and such but, based on what I understood, I think the text is correct, and I do not see how we can improve it...

I propose to close the issue as solved.

**Comment by dlazin** [comment]
OK, if Ivan is satisfied, I'm OK with closing.
