### ISSUE TITLE
Link RS manifest.xml (etc) to core spec?

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2172]
https://w3c.github.io/epub-specs/epub33/rs/#sec-container-metainf has a smattering of requirements about various XML files; the first two make sense on their own, but the manifest.xml requirement seems basically to be saying "the RS should not parse a manifest.xml file at all."

a) If it's saying that, can we just say that explicitly?

b) I was only able to interpret this after reading https://w3c.github.io/epub-specs/epub33/core/#sec-container-metainf-manifest.xml, but the RS spec does not link there. Should we link all these files to their longer sections in the RS spec? In particular, I found `This feature exists only for compatibility with ODF` to be helpful.

**Comment by iherman** [comment]
I think your interpretation is correct, @dlazin and I agree that a set of links to the core spec would be useful. I will do a PR on this later today.

**Comment by mattgarrish** [comment]
> I agree that a set of links to the core spec would be useful. I will do a PR on this later today.

#2163 has added a lot of links, including to the meta-inf files, so if you branched to work on this before I got up, you might want to merge from main to get the latest changes. Hopefully there isn't too much more you need to add, but another review wouldn't hurt.

**Comment by iherman** [comment]
Ouch, @mattgarrish, I did not see the comment, and just created #2176...

Will look at it.

**Comment by iherman** [comment]
I have closed #2176 without merge; your #2163 covers this issue (and much more).

I mark this issue as to be closed; @dlazin, if you agree, you should close it!
