### ISSUE TITLE
EPUB 3.3 (Core Spec) Edits - 1. Introduction

### ISSUE THREAD

**Issue by BenSchroeter** [mattgarrish/epub-revision#2181]
This section is in great shape... only two minor suggested edits: 

Section 1.2, Para 9:
hyphenate "universally named"

Section 1.4, Package Document:
insert Oxford comma after "resources"

**Comment by mattgarrish** [comment]
> hyphenate "universally named"

FYI, I'm trying to keep the documents to the rule of not hyphenating adverbs ending in ly when the are followed by an adjective. See this CMoS faq: https://www.chicagomanualofstyle.org/qanda/data/faq/topics/HyphensEnDashesEmDashes/faq0010.html

(But growing up being told to hyphenate these, it's always my initial instinct to hyphenate them, too.)
