### ISSUE TITLE
EPUB Reading Systems 3.3 - Suggestion Edits: 13. Accessibility

### ISSUE THREAD

**Issue by BenSchroeter** [mattgarrish/epub-revision#2182]
Para 3:
"many browser accessibility issues have parallels in EPUB" s.b "many browser accessibility issues have parallels in EPUB-specific user agents"

Bookshelf bullet:
"announce the options" s/b "announce the content"

User Interface Controls bullet: 
"and their actions" should be "and that their actions"

Search bullet:
Does any Reading System allow Search capability to extend to alt attributes, or is this aspirational?

Reading Control:
Question the phrase "physical interaction" here... is manipulating a keyboard in order to open a new document not allowed?

Document Object Model (DOM) bullet:
change "used in the source" to "applied in the source content"

**Comment by iherman** [comment]
See #2186
