### ISSUE TITLE
EPUB Reading Systems 3.3 Edits - Introduction

### ISSUE THREAD

**Issue by BenSchroeter** [mattgarrish/epub-revision#2183]
Section 1.1
Para 3:
"As a result, there is no single set of rules that all Reading Systems must follow" s/b "Therefore, there is no single set of rules that applies to all Reading Systems"

"its supports" s/b "it supports"

Para 4:
Delete ", such as in their bookshelves"

"Moreover, this specification provides a great deal of flexibility to developers to create unique user interfaces, such as in their bookshelves. As a result, metadata processing requirements are often quite minimal, for example." s/b "Moreover, this specification allows for a great deal of flexibility for developers to create unique user interfaces, and requirements for things like metadata processing are intentionally minimal to allow for such flexibility."

Para 5: 
Change "read" to "understand"

"Developers should also familiarize themselves with the full content structure of an EPUB Publication to understand" s/b "Developers should also familiarize themselves with the full content structure of an EPUB Publication in order to understand"

Section 1.2
"as well as the terms defined in this section"... Did we intend to include more than one term (Content Display Area) in this section? Should we change to singular "term"?

Section 1.3
Para 1
"As well as" s/b "In addition to"

Para 3
"may" s/b "might"

Section 1.4.2
Para 2
"to ensure they keep" s/b "to ensure that they keep"

**Comment by iherman** [comment]
See #2185
