### ISSUE TITLE
Section C review: Expressing Structural Semantics

### ISSUE THREAD

**Issue by bkasdorf** [mattgarrish/epub-revision#2190]

**Comment by bkasdorf** [comment]
C. Expressing Structural Semantics
C.1 Introduction
This section is non-normative.

Structural semantics add additional meaning about the specific structural purpose an element plays. The [epub:type attribute](https://w3c.github.io/epub-specs/epub33/core/#sec-epub-type-attribute) is used to express domain-specific semantics in [EPUB Content Documents](https://w3c.github.io/epub-specs/epub33/core/#dfn-epub-content-document) and [Media Overlay Documents](https://w3c.github.io/epub-specs/epub33/core/#dfn-media-overlay-document), with the structural information it carries complementing the underlying vocabulary.

The applied semantics refine the meaning of their containing elements without changing their nature for assistive technologies, as happens when using the similar [role attribute](https://html.spec.whatwg.org/multipage/#attr-aria-role) [[HTML](https://w3c.github.io/epub-specs/epub33/core/#bib-html)]. The attribute does not enhance the accessibility of the content, in other words, **it** only provides hints about the purpose.

Semantic metadata enriches content for use in publishing workflows and for author-defined purposes. It also allows Reading Systems to learn more about the structure and content of a document (e.g., to enable [skippability and escapability](https://w3c.github.io/epub-specs/epub33/core/#sec-behaviors-skip-escape)[](https://w3c.github.io/epub-specs/epub33/core/#sec-epub-type-attribute) in Media Overlays).

This specification defines a method for adding structural semantics using the attribute axis: instead of adding new elements, EPUB Creators can append the epub:type attribute to existing elements to add the desired semantics.

C.2 The epub:type Attribute
Attribute Name
type

Namespace
http://www.idpf.org/2007/ops **[Is this URL still valid, and if so, should it be a W3C URL?]**

Usage
[Global attribute](https://html.spec.whatwg.org/multipage/#global-attributes). EPUB Creators MAY specify on all elements.

Value
A white space-separated list of [property](https://w3c.github.io/epub-specs/epub33/core/#sec-property-datatype) values, with restrictions as defined in [D.1 Vocabulary Association Mechanisms](https://w3c.github.io/epub-specs/epub33/core/#sec-vocab-assoc).

White space is the set of characters as defined in [[XML](https://w3c.github.io/epub-specs/epub33/core/#bib-xml)].

CAUTION
Although the epub:type attribute is similar in nature to the [role attribute](https://html.spec.whatwg.org/multipage/#attr-aria-role) [[HTML](https://w3c.github.io/epub-specs/epub33/core/#bib-html)], the attributes serve different purposes. The values of the epub:type attribute do not enhance access through assistive technologies like screen readers as they do not map to the accessibility APIs used by these technologies. This means that adding epub:type values to semantically neutral elements like [[HTML](https://w3c.github.io/epub-specs/epub33/core/#bib-html)] [div](https://html.spec.whatwg.org/multipage/#the-div-element) and [span](https://html.spec.whatwg.org/multipage/#the-span-element) does not make them any more accessible to assistive technologies. Only ARIA roles influence how assistive technologies understand such elements.

The epub:type attribute is consequently only intended for publishing semantics and Reading System enhancements. Reading Systems may use epub:type values to provide accessibility enhancements like built-in read aloud or Media Overlays functionality where interaction with assistive technologies is not essential.

Refer to [Digital Publishing WAI-ARIA Module 1.0](https://www.w3.org/TR/dpub-aria-1.0/#) [[DPUB-ARIA-1.0] **[I assume we have to keep this as 1.0 because 1.1 is still just a Working Draft, correct?]** (https://w3c.github.io/epub-specs/epub33/core/#bib-dpub-aria-1.0)] for more information about accessible publishing roles.

The epub:type attribute inflects semantics on the element on which it appears. Its value is one or more white space-separated terms stemming from external vocabularies associated with the document instance.

The [default vocabulary](https://w3c.github.io/epub-specs/epub33/core/#sec-default-vocab) for the epub:type attribute is the EPUB 3 Structural Semantics Vocabulary [[EPUB-SSV-11](https://w3c.github.io/epub-specs/epub33/core/#bib-epub-ssv-11)]. EPUB Creators MAY include unprefixed terms that are not part of this vocabulary, but the preferred method for adding custom semantics is to use [prefixes](https://w3c.github.io/epub-specs/epub33/core/#sec-prefix-attr) for them. Refer to [D.1 Vocabulary Association Mechanisms](https://w3c.github.io/epub-specs/epub33/core/#sec-vocab-assoc) for more information.

[EXAMPLE 76](https://w3c.github.io/epub-specs/epub33/core/#ex.epubtype.note): Identifying a preamble
<html
    …
    xmlns:epub="http://www.idpf.org/2007/ops">
   …
   <body>
      …
      <section epub:type="preamble">
         …    
      </section>
      …
   </body>
</html>
[EXAMPLE 77](https://w3c.github.io/epub-specs/epub33/core/#ex.epubtype.gloss): Identifying a glossary
<html
    …
    xmlns:epub="http://www.idpf.org/2007/ops">
   …
   <body>
      …
      <dl epub:type="glossary">
         …    
      </dl>        
      …
   </body>
</html>
[EXAMPLE 78](https://w3c.github.io/epub-specs/epub33/core/#ex.epubtype.pg): Adding page break semantics
<html
    …
    xmlns:epub="http://www.idpf.org/2007/ops">
   …
   <body>
      …
      <p>
         … 
         <span
            epub:type="pagebreak"
            id="p234"
            role="doc-pagebreak"
            aria-label="234"/>
         …
      </p>    
      …
   </body>
</html>

**Comment by iherman** [comment]
> Namespace
> http://www.idpf.org/2007/ops [Is this URL still valid, and if so, should it be a W3C URL?]

If we changed this to a W3C URL, we would invalidate older EPUBs, which is a big no-no in our charter. And unnecessary, I would say.

The URL still resolves and, because it is under the W3C's control, it is stable; consequently, there is no reason to change this.

**Comment by iherman** [comment]
> Refer to [Digital Publishing WAI-ARIA Module 1.0](https://www.w3.org/TR/dpub-aria-1.0/#) [[DPUB-ARIA-1.0] [I assume we have to keep this as 1.0 because 1.1 is still just a Working Draft, correct?] (https://w3c.github.io/epub-specs/epub33/core/#bib-dpub-aria-1.0)] for more information about accessible publishing roles.

I wonder whether we could refer to https://www.w3.org/TR/dpub-aria/ instead. @mattgarrish do you know whether that URL would refer to 1.1 once it is a standard? Because if so, we can be version neutral (it is not a normative statement anyway)

**Comment by mattgarrish** [comment]
> I wonder whether we could refer to https://www.w3.org/TR/dpub-aria/ instead. @mattgarrish do you know whether that URL would refer to 1.1 once it is a standard?

I defer to your knowledge of these things, but I assume that's how it always works. We'd have to add an unversioned "[[DPUB-ARIA]]" reference to the biblio, though, as I don't believe specref includes these by default.

**Comment by iherman** [comment]
> I defer to your knowledge of these things, 

I do not think it is automatic, it is up to the WG to agree with the webmaster afaik

> We'd have to add an unversioned "[[DPUB-ARIA]]" reference to the biblio, though, as I don't believe specref includes these by default.

I think that is a plan.
