### ISSUE TITLE
Section D.1.5 review

### ISSUE THREAD

**Issue by bkasdorf** [mattgarrish/epub-revision#2198]
D.1.5 Reserved Prefixes
CAUTION
Although reserved prefixes are an authoring convenience, EPUB Creators should avoid relying on them as they may cause interoperability issues. [EPUB Conformance Checkers](https://w3c.github.io/epub-specs/epub33/core/#dfn-epub-conformance-checker) will often reject new prefixes until their developers update the tools to the latest version of the specification, for example. [EPUB Creators](https://w3c.github.io/epub-specs/epub33/core/#dfn-epub-creator) should declare all prefixes they use to avoid such issues.

EPUB Creators MAY use reserved prefixes in attributes that expect a [property value](https://w3c.github.io/epub-specs/epub33/core/#sec-property-datatype) without declaring them in a [prefix attribute](https://w3c.github.io/epub-specs/epub33/core/#sec-prefix-attr).

EPUB Creators SHOULD NOT override reserved prefixes in the [prefix attribute](https://w3c.github.io/epub-specs/epub33/core/#sec-prefix-attr).

The reserved prefixes **delete an** EPUB Creators can use depends on the context:

[Package Document](https://w3c.github.io/epub-specs/epub33/core/#dfn-package-document)
EPUB Creators MAY use the following prefixes in Package Document attributes without having to declare them.

**[Check whether any of the IDPF urls can be updated to a W3C url.]**
Prefix	URL
a11y	http://www.idpf.org/epub/vocab/package/a11y/#
dcterms	http://purl.org/dc/terms/
marc	http://id.loc.gov/vocabulary/
media	http://www.idpf.org/epub/vocab/overlays/#
onix	http://www.editeur.org/ONIX/book/codelists/current.html#
rendition	http://www.idpf.org/vocab/rendition/#
schema	http://schema.org/
xsd	http://www.w3.org/2001/XMLSchema#
Structural Semantics
EPUB Creators MAY use the following reserved prefixes in the [epub:type attribute](https://w3c.github.io/epub-specs/epub33/core/#app-structural-semantics) without having to declare them.

Prefix	URL
msv	http://www.idpf.org/epub/vocab/structure/magazine/#
prism	http://www.prismstandard.org/specifications/3.0/PRISM_CV_Spec_3.0.htm# **[This gives a 404, as do the links to PRISM 3.0 and 3.1 on https://idealliance.org/specifications/prism-metadata/. Idealliance doesn't exist as an organization anymore. Matt, if you can't find a proper link I can check with Linda Burman or Dianne Kennedy to see if there is a referenceable spec for PRISM.]**

**Comment by iherman** [comment]
For

> [Check whether any of the IDPF urls can be updated to a W3C url.]

same remark as in https://github.com/w3c/epub-specs/issues/2190#issuecomment-1086036703 : these URLs should not change.

**Comment by iherman** [comment]
On PRISM:

PRISM has been parked at W3C as a Member submission exactly for the reason that you quote, @bkasdorf. The corresponding (and stable!) URL is now: https://www.w3.org/Submission/2020/SUBM-prism-20200910/prism-cvs.html

**Comment by iherman** [comment]
That being said... same problem as before. The _prefix_ as for prefix used in an XML vocabulary as a namespace, should probably _not_ change, because it would make old content invalid. In XML there is no _obligation_ that a prefix URL should not have a 404 response, it is just a kind of a no-no...

**Comment by iherman** [comment]
On both comments: I believe the spec should not change. Propose closing...

**Comment by mattgarrish** [comment]
> In XML there is no _obligation_ that a prefix URL should not have a 404 response

Technically these are compact URIs, not namespaces, but that distinction doesn't materially change the problem. If we modify the stem URLs, then the fully resolved URLs won't be the same as before.
