### ISSUE TITLE
Section D.3 intro review

### ISSUE THREAD

**Issue by bkasdorf** [mattgarrish/epub-revision#2199]
[](https://w3c.github.io/epub-specs/epub33/core/#app-meta-property-vocab)D.3 Meta Properties Vocabulary
The properties in this vocabulary are usable in the [meta element's](https://w3c.github.io/epub-specs/epub33/core/#sec-meta-elem) property attribute.

Unless indicated otherwise in its "Extends" field, the properties defined in this section are used to define [subexpressions](https://w3c.github.io/epub-specs/epub33/core/#subexpression): in other words, a [meta](https://w3c.github.io/epub-specs/epub33/core/#elemdef-meta) element carrying a property defined in this section MUST have a [refines](https://w3c.github.io/epub-specs/epub33/core/#attrdef-refines) attribute referencing a resource or expression being augmented.

The prefix URL for [referencing these properties](https://w3c.github.io/epub-specs/epub33/core/#sec-default-vocab) is http://idpf.org/epub/vocab/package/meta/#. **[This link goes to an Obsolete warning that redirects to Section C of this spec.]**

**Comment by iherman** [comment]
This is a namespace URL used as a prefix. The fact that it goes refers to this spec is fine; no change is required.

**Comment by mattgarrish** [comment]
We can't change these, I agree, but it would be nice if we could redirect them. We used to control the redirects through the .htaccess file on the idpf server. Can we still get that modified?

**Comment by mattgarrish** [comment]
Although I suppose we can put meta refresh redirects in the github pages to get people to the new spec, as those are the last places the idpf redirects went to...

Maybe we should open that as a separate cleanup task?

**Comment by mattgarrish** [comment]
Closing this issue as redirects will be covered in #2212
