### ISSUE TITLE
D.3.13 Example 96

### ISSUE THREAD

**Issue by bkasdorf** [mattgarrish/epub-revision#2204]
[EXAMPLE 96](https://w3c.github.io/epub-specs/epub33/core/#example-expressing-complex-titles): Expressing complex titles
This example shows how to classify the title "The Great Cookbooks of the World: Mon premier guide de cuisson, un Mémoire. The New French Cuisine Masters, Volume Two. Special Anniversary Edition".

<metadata …>

**[The other examples all have another ellipsis here. Is the omission here intentional?]**
   <dc:title
       id="t1"
       xml:lang="fr">
      Mon premier guide de cuisson, un Mémoire
   </dc:title>
   <meta
       refines="#t1"
       property="title-type">
      main
   </meta>
   <meta
       refines="#t1"
       property="display-seq">
      2
   </meta>

   <dc:title id="t2">
      The Great Cookbooks of the World
   </dc:title>
   <meta
       refines="#t2"
       property="title-type">
      collection
   </meta>
   <meta
       refines="#t2"
       property="display-seq">
      1
   </meta>

   <dc:title id="t3">
      The New French Cuisine Masters
   </dc:title>
   <meta
       refines="#t3"
       property="title-type">
      collection
   </meta>
   <meta
       refines="#t3"
       property="display-seq">
      3
   </meta>

   <dc:title id="t4">
      Special Anniversary Edition
   </dc:title>
   <meta
       refines="#t4"
       property="title-type">
      edition
   </meta>
   <meta
       refines="#t4"
       property="display-seq">
      4
   </meta>

   <dc:title id="t5">
      The Great Cookbooks of the World: 
      Mon premier guide de cuisson, un Mémoire. 
      The New French Cuisine Masters, Volume Two. 
      Special Anniversary Edition
   </dc:title>
   <meta
       refines="#t5"
       property="title-type">
      expanded
   </meta>
   …
</metadata>

**Comment by iherman** [comment]
It is not :-)
