### ISSUE TITLE
Redirect IDPF vocabularies

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2212]
We need to redirect the old vocabularies that are hosted in IDPF's github space forward to the new spec.

They are all hosted here: https://github.com/IDPF/epub-vocabs

A meta refresh could be used to push people to the top of each vocabulary, or we may want to create a small javascript that gets the specific term they were trying to reach and appends it to a scripted redirect.

**Comment by iherman** [comment]
Prepared a PR to settle these in https://github.com/IDPF/epub-vocabs/pull/12
