### ISSUE TITLE
3.4.1.3.1 Pagination Source in EPUB A11Y 1.1

### ISSUE THREAD

**Issue by t-kudou** [mattgarrish/epub-revision#2219]
https://www.w3.org/TR/epub-a11y-11/#sec-page-src

Right now, it is not explicitly stated which metadata is to be used as the pagenation source. EPUB A11Y 11 should specify the use of source-of in this section.
For example, how about the following modification?

EPUB Creators MUST identify that source in the Package Document metadata.
↓
EPUB MUST be identified that source with a source-of property in the Package Document metadata.

**Comment by mattgarrish** [comment]
Implementation details are typically defined in the techniques as, especially with metadata, you can't always express the same things between EPUB 2 and 3.

For example, the use of source-of is defined here: https://www.w3.org/TR/epub-a11y-tech-11/#page-004

We might want to link the objectives to their techniques, though. Thoughts @avneeshsingh @GeorgeKerscher @clapierre ?

**Comment by clapierre** [comment]
I agree, linking to the techniques document especially for this since there can be multiple "source" metadata statements within the EPUB.

**Comment by avneeshsingh** [comment]
+1 to linking to the techniques.

**Comment by mattgarrish** [comment]
Closing this with #2230
