### ISSUE TITLE
Level AAA conformance in EPUB A11Y 1.1

### ISSUE THREAD

**Issue by imagedrive** [mattgarrish/epub-revision#2223]
The following note in EPUB A11Y 1.1 appears to recommend Level AAA conformance.

> EPUB Creators should try to meet the AAA requirements if they can, but fully conforming at AAA is typically not possible

In WCAG 2.0,  Level AAA conformance for an entire site is not recommended, as it is sometimes impossible (see Note 2 in https://www.w3.org/TR/WCAG20/#conformance-reqs).
Level AAA conformance is difficult because it increases authoring and verifying costs.

**Comment by mattgarrish** [comment]
> The following note in EPUB A11Y 1.1 appears to recommend Level AAA conformance.

The intention wasn't to recommend trying to fully meet AAA, as I recall, but to encourage publishers not to ignore those success criteria. There are useful ones for publishing at that level that can be met, like section headings.

We could swap it around to emphasize that conformance at that level is not realistic, though:

> Although conforming at AAA is typically not possible, EPUB Creators are encouraged not to ignore AAA success criteria when producing accessible EPUB Publications.

It should also be a proper note and would better follow the normative level requirement bullet than be included in the discussion of legal frameworks. Parentheticals don't carry normative weight.
