### ISSUE TITLE
F.2.2 Schema for encryption.xml & F.2.3 Schema for signatures.xml

### ISSUE THREAD

**Issue by clapierre** [mattgarrish/epub-revision#2227]
Since we don't have any non-normative schema's to point to should we say anything here?  Just seems odd to just have

[F.2.2 Schema for encryption.xml](https://w3c.github.io/epub-specs/epub33/core/#app-schema-encryption)
The schema for encryption.xml files is included in [[XMLSEC-RNGSCHEMA-20130411](https://w3c.github.io/epub-specs/epub33/core/#bib-xmlsec-rngschema-20130411)].

and

[F.2.3 Schema for signatures.xml](https://w3c.github.io/epub-specs/epub33/core/#app-schema-signatures)
The schema for signatures.xml files is included in [[XMLSEC-RNGSCHEMA-20130411](https://w3c.github.io/epub-specs/epub33/core/#bib-xmlsec-rngschema-20130411)].

**Comment by mattgarrish** [comment]
Technically, it's better to have normative than non-normative, but these aren't normative, or at least I didn't think we could reference WG notes normatively. The references come out in the informative section despite not saying they are non-normative.

Should the whole section be informative and we drop the "non-normative" descriptor from the epubcheck shemas @iherman?

**Comment by iherman** [comment]
We do not have control over this. We refer to a [WG Note](https://www.w3.org/TR/2013/NOTE-xmlsec-rngschema-20130411/), created by the XML Security WG. As @mattgarrish said, we cannot refer normatively to a Note (e.g., for IPR reasons). We are stuck where we are now, and we cannot change that.

**Comment by mattgarrish** [comment]
> we cannot refer normatively to a Note

I missed that the appendix has an informative label on it. I still think it would be good if all the schema prose were the similar so we don't give the appearance that the epubcheck schemas are informative and the notes are not, when they all are informative.

What is the proper terminology now? It used to be normative/informative, but now the labels are "non-normative" while the references are still called "informative". I know we can't change the latter ourselves, but it seems like a confused mix. We also have some lingering uses of "informative" in the body from back when that's what "non-normative" stuff was called.

**Comment by mattgarrish** [comment]
And for extra fun, the css class to mark things "non-normative" is "informative"... 😄

**Comment by iherman** [comment]
> I know we can't change the latter ourselves

Actually, isn't the "non-normative" label also generated by respec? Ie, we cannot change any of the two :-)

I would use non-normative overall.

**Comment by mattgarrish** [comment]
> Actually, isn't the "non-normative" label also generated by respec?

Yes, but we've called things "informative" in various places (like the algorithm descriptions). Some may have come from IDPF.

I'm about to open a PR that swaps these for "non-normative" just to be consistent.
