### ISSUE TITLE
Terminology linking

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2241]
The first time a term from the terminology is used in a section, and only the first time, it's supposed to be linked to its definition.

After years of revisions, it's unlikely this practice is consistent anymore (if it ever was), particularly with the splitting off of the RS spec.

Adding a review to the post-CR cleanup chore list, in case we don't have enough things to do... 😄

**Comment by iherman** [comment]
@mattgarrish #2247 was merged; shouldn't this issue be closed?

**Comment by mattgarrish** [comment]
I wish, but no...

The merge only covered the accessibility specification. Even on that relatively tiny spec, it was a headache to do. You lose track of what is linked and not linked in each section when you see the terms over and over.
