### ISSUE TITLE
Requirement (MUST vs SHOULD) for Media Overlays is unclear

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2271]
https://w3c.github.io/epub-specs/epub33/rs/#confreq-rs-epub3-mo says:

> Reading systems with the capability to render prerecorded audio SHOULD support [media overlays](https://www.w3.org/TR/epub-33/#sec-media-overlays) [[epub-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)].

But then:

> When a reading system loads a [package document](https://www.w3.org/TR/epub-33/#dfn-package-document), it MUST refer to the [manifest](https://www.w3.org/TR/epub-33/#dfn-epub-manifest) [item](https://www.w3.org/TR/epub-33/#dfn-item) elements' [[epub-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)] media-overlay attributes to discover the corresponding media overlays for [EPUB content documents](https://www.w3.org/TR/epub-33/#dfn-epub-content-document).

> Reading systems MUST support playback for [XHTML content documents](https://www.w3.org/TR/epub-33/#dfn-xhtml-content-document), and MAY support [SVG content documents](https://www.w3.org/TR/epub-33/#dfn-svg-content-document).

> Playback MUST start...

This makes it sound like (full/proper) *support* for MOs is optional, but RSes still need to do all the processing. I don't think that's what's intended. I assume we mean "if you are going to support MOs, then here is what is a requirement for support." Elsewhere, we use language like "If a reading system supports scripting...". I think we should sprinkle such language throughout the MO section, assuming my interpretation is correct.

**Comment by iherman** [comment]
I agree with your second interpretation, ie, that "_If_ the reading system support scripting then..."

Instead of sprinkle such language all around (which may lead to fairly convoluted sentences) what about making this clear in the intro section? Eg, by changing the first paragraph right after the yellow box to something like:

> If a reading system does not support media overlays, all normative requirements in this section can be ignored. In particular, such a reading system MUST ignore both:

@mattgarrish ?

**Comment by mattgarrish** [comment]
I'm not sure I see the problem here. If you have to ignore the media-overlay attribute and all SMIL files if you don't support media overlays, which is what the following paragraph says, then by extension none of the processing and playback requirements for the SMIL files apply.

**Comment by mattgarrish** [comment]
Would it help if we added "Reading system conformance" as a new section 2 and briefly explained that the expected support requirements for each feature are defined at the beginning of each section? We jump right into indivudal features and support right now, but a clear explanation of why wouldn't hurt.

That would also provide the opportunity to say once that recommended support means that the processing requirements can be ignored when not supported.

**Comment by iherman** [comment]
@mattgarrish @dlazin isn't this issue solved, ie, can it be closed? @dlazin has changed the status of the relevant tests...

**Comment by dlazin** [comment]
Yes; this wasn't about the tests, but https://github.com/w3c/epub-specs/pull/2305 addresses the issue here.
