### ISSUE TITLE
Redundant structural semantics normative statements?

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2273]
https://w3c.github.io/epub-specs/epub33/rs/#sec-structural-semantics says:

> When processing the [epub:type](https://www.w3.org/TR/epub-33/#dfn-epub-type) attribute, a reading system:

> * ...

> * MUST [ignore structural semantics](https://w3c.github.io/epub-specs/epub33/rs/#confreq-rs-epubtype-prec) that conflict with the carrying element.

> When the Reading system behavior associated with a given epub:type value conflicts with an element's native behavior, the behavior associated with the element MUST be given precedence.

As far as I can tell, these are the same requirement. Can we either combine them or, if they're not the same, clarify how they're distinct?

**Comment by iherman** [comment]
I would agree that the two requirement are the same. What about exchanging the last bullet item to

> _MUST_ ignore the `epub:type` value if its semantics conflicts with the element's native behavior, which should take precedence.

and remove the last paragraph?

@mattgarrish

**Comment by dlazin** [comment]
Simple enough; I will send a PR for that.

**Comment by dlazin** [comment]
Oh, note that "ignore structural semantics" in the bullet links *to* that paragraph, which suggests we were trying to say something more here, but not clear what that would have been. I will still send a PR.

**Comment by dlazin** [comment]
Ah, at third look I think I understand how this is distinct from Ivan's suggestion.

We aren't actually trying to say "ignore the value" (pretend it's not there); we're saying "don't apply the behaviors *implied* by that value if they would conflict."

So, say, if someone does `<button epub:type="chapter">`, it's still a button, and it can be a chapter too (for semantic purposes; you shouldn't *ignore* that it's designated as a chapter), but you shouldn't apply "chapter behavior" to the button in a way that stops the button from being a button (like, don't just interpret it as a `<section>`; for example, among other things, it should still be an inline element, not a block-level element).

I will take another attempt at the PR to make that clear in one bullet.

**Comment by mattgarrish** [comment]
I'd probably drop the bullet and trailing paragraph entirely, but I'm just skimming issues to see what I've missed.

This goes back to epub:type being modeled on the [W3C role attribute specification](https://www.w3.org/TR/role-attribute/) and potentially influencing the rendering of content like ARIA role.

We never did the legwork to explain how that would work, so absent rules on what roles are disallowed on what elements, this is a hopelessly vague requirement. (Plus epub:type has no influence over how elements are represented in the DOM, so there's nothing more to ignore.)

**Comment by dlazin** [comment]
In https://github.com/w3c/epub-specs/pull/2277, I have now done what Matt suggests — delete both entirely. Please re-review.
