### ISSUE TITLE
Redundant spine overrides normative statements

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2279]
https://w3c.github.io/epub-specs/epub33/rs/#spine-overrides says:

> When a spine [itemref](https://www.w3.org/TR/epub-33/#dfn-itemref) element's [properties attribute](https://www.w3.org/TR/epub-33/#attrdef-properties) overrides a [global rendering property](https://www.w3.org/TR/epub-33/#app-rendering-vocab) [[epub-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)], reading systems MUST follow the requirements for the override's global value to display that spine item.

> For example, a spine item that contains the [layout-pre-paginated override](https://www.w3.org/TR/epub-33/#layout-overrides) [[epub-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)] is rendered following the requirements of the global [pre-paginated value](https://w3c.github.io/epub-specs/epub33/rs/#def-layout-pre-paginated).

And then much later https://w3c.github.io/epub-specs/epub33/rs/#layout says:

> When a spine itemref element's [properties attribute](https://www.w3.org/TR/epub-33/#attrdef-properties) contains an [override of the global rendition:layout property](https://www.w3.org/TR/epub-33/#layout-overrides) [[epub-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)], reading systems MUST follow the requirements for the override's global value when displaying that spine item (e.g., a spine item that specifies layout-prepaginated is rendered following the requirements of the global pre-paginated value).

  These are almost identical; we should cut one or the other and make one section link to the other. A good example of this is https://w3c.github.io/epub-specs/epub33/rs/#confreq-svg-rs-css, which simply says `a reading system MUST also conform to the constraints defined in...`.

**Comment by mattgarrish** [comment]
Yes, the second instance should have been removed in https://github.com/w3c/epub-specs/pull/1947

We don't need to refer back up to the first section, since it covers all overrides (otherwise, every property would need a reference).
