### ISSUE TITLE
Redundant Media Overlays escapability normative statements

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2284]
https://w3c.github.io/epub-specs/epub33/rs/#sec-escapability says (breaks and numerals mine):

> 1) Reading systems SHOULD allow escaping of nested structures.
> 2) Reading systems MUST determine the start of nested structures by the value of the [epub:type](https://www.w3.org/TR/epub-33/#dfn-epub-type) attribute and
> 3) SHOULD offer users the option to skip playback of that structure and resume with whatever content comes after it.

It seems to me that #1 and #3 are saying the same thing. It's also not clear if the MUST is dependent on the SHOULD (like #2271), or if the MUST applies even if the RS doesn't support escaping.

**Comment by iherman** [comment]
Well... I guess the key is actually the additional remark you had at the end of the question. Yes, imho, all this is dependent on the fact whether the RS implements that feature. Is it clearer if I reformulate it slightly as in:

> Reading systems SHOULD allow escaping of nested structures. Implementing escaping means that the reading systems MUST determine the start of nested structures by the value of the [epub:type](https://www.w3.org/TR/epub-33/#dfn-epub-type) attribute, and SHOULD offer users the option to skip playback of that structure and resume with whatever content comes after it.

(And I agree the current formulation is unclear.)

I would actually put an explicit reference to https://www.w3.org/TR/epub-33/#sec-escapability, which contains an elaborate example, too.

**Comment by dlazin** [comment]
Ivan's version of this is much better, but I'm still not clear on what escaping is *other* than the last phrase. Like, if you did the MUST, but not the last SHOULD, wouldn't that mean the user can't escape the content? It sounds to me like the last SHOULD is the definition of what escaping is, and therefore it should be a MUST. If I'm misunderstanding, then I think we need another MUST somewhere, because merely determining the start of nested structures — without any UI abilities — does not allow escaping.

**Comment by mattgarrish** [comment]
> Like, if you did the MUST, but not the last SHOULD, wouldn't that mean the user can't escape the content

Yes, it's still a bit redundant with providing the feature. I would formulate it more along these lines:

> Reading systems SHOULD allow escaping of nested structures. To escape a structure, reading systems MUST determine the start of the nested structure by the value of the [epub:type](https://www.w3.org/TR/epub-33/#dfn-epub-type) attribute on the nearest ancestor `seq` element and resume playback with whatever content comes after it.

Does this sound right to you, @marisademeglio ?

**Comment by mattgarrish** [comment]
Although, can an escapable structure be represented by a single `par` element? (i.e., can you escape from a list that is just one long `par` audio sequence?)

Maybe it's better not to say what element to look for and make it:

> Reading systems SHOULD allow escaping of nested structures. To escape a structure, reading systems MUST determine the start of the nested structure by the value of the [epub:type](https://www.w3.org/TR/epub-33/#dfn-epub-type) attribute on the nearest ancestor element, or self, and resume playback with the next `seq` or `par` element after it.

**Comment by marisademeglio** [comment]
What if we wrote something like:

> While playing Media Overlays, Reading Systems SHOULD offer users the option to leave ("escape") "escapable structures", which are determined by the presence of an [`epub:type`](https://www.w3.org/TR/epub-33/#dfn-epub-type) attribute with a value from the _escapable structures list_ (where is this?). If the currently-playing element or its parent is an escapable structure, and the user opts to escape out of it, then the Reading System MUST continue playback with the next sequential element after the escapable structure.

This puts MUSTs and SHOULDs on measurable RS behavior.

**Comment by mattgarrish** [comment]
> If the currently-playing element or its parent

I think we need to say "or an ancestor" here, as if you're in a table cell there could be a `seq` for the row between it and the `seq` for the table (same with deeply nested lists, complex figures, etc.).

Otherwise, sounds good to me.
