### ISSUE TITLE
Should media type registration be normative?

### ISSUE THREAD

**Issue by xfq** [mattgarrish/epub-revision#2313]
Per https://www.w3.org/2020/01/registering-mediatypes , media type registration should be a normative part of a specification, but [Media type registrations](https://w3c.github.io/epub-specs/epub33/core/#app-media-types) in EPUB is currently non-normative. Is that intentional?

**Comment by xfq** [comment]
As an example, https://www.w3.org/TR/2022/REC-WOFF2-20220310/#IMT is a normative section.

**Comment by iherman** [comment]
You may be right. I checked with some other recent specifications (JSON-LD, DID) and they are not marked as non-normative. I do not think there is any intentionality behind it...

**Comment by mattgarrish** [comment]
Isn't this related to whether we should update the registrations? The registrations in the specification don't currently match the IANA registrations, and haven't for some number of years now.

**Comment by iherman** [comment]
We can deal with that together. I have already inquired (not have an answer yet) on what exactly should be done to _update_ (as opposed to submit a new) registration. I will take the next steps when I know what exactly they are, and I will deal with that then.
