### ISSUE TITLE
Proposal: Metadata for alternate titles

### ISSUE THREAD

**Issue by acabal** [mattgarrish/epub-revision#2333]
At Standard Ebooks we occasionally come across books that historically have been published with various titles. For example, the novel _The Mark of Zorro_ was initially serialized under the title _The Curse of Capistrano_. But, the books are the same.

It would be helpful to have metadata available to denote these kinds of alternate titles. Catalogs like ours are likely to only host a single ebook under a single title, so having the alternate title exposed in the metadata can aid in returning correct results for search queries using  the alternate title. For example, someone who searches our catalog for `curse of capistrano` could be returned the result for _The Mark of Zorro_ because it has the alternate title listed in its metadata.

This could be represented in the metadata like so:

```xml
<dc:title id="title">The Mark of Zorro</dc:title>
<meta refines="#title" property="alternate-title">The Curse of Capistrano</meta>
```

or,

```xml
<dc:title id="title">The Mark of Zorro</dc:title>
<meta property="title-type" refines="#title">main</meta>
<dc:title id="title-alternate">The Curse of Capistrano</dc:title>
<meta property="title-type" refines="#title-alternate">alternate</meta>
```

`@title-type="short"` is one possible alternative to this proposal, but in this case, the alternate title isn't really "short" per se - it's totally different.

**Comment by iherman** [comment]
There is no problem using the Dublin Core [`alternative`](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/alternative) for what you describe; note that it stands for "alternative title" in the DCMI spec. We actually use this in our test cases, see for example the [OPF file for pkg-dir_rtl-root-ltr](https://github.com/w3c/epub-tests/blob/main/tests/pkg-dir_rtl-root-ltr/EPUB/package.opf). I think we should avoid re-defining terms that already exist.

Whether Reading System would use that term for something sensible is a different question, of course.

**Comment by acabal** [comment]
I wasn't aware of that, thanks! That should cover our needs.
