### ISSUE TITLE
Repetitive requirements for page-spread-* declarations

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2345]
While going over the terminology, I noticed the same requirement stated for reflowable and prepaginated spine items:

> Reading systems MUST honor rendition:page-spread-* properties on reflowable spine items (e.g., by inserting a blank page).
> ...
> Reading systems MUST honor rendition:page-spread-* properties on pre-paginated spine items (e.g., by inserting a blank page).

https://w3c.github.io/epub-specs/epub33/rs/#page-spread-flow

Given that there are only reflowable and prepaginated items, and there is no suggestion the behaviour differs, does this serve any purpose?

The test reference is even the same for both.

**Comment by iherman** [comment]
Oops...

There is a sentence earlier in the section

> The rendition:page-spread-left and rendition:page-spread-right properties apply to both pre-paginated and reflowable content, and they only apply when the reading system is creating [synthetic spreads](https://www.w3.org/TR/epub-33/#dfn-synthetic-spread).

I guess the two sentences on page-spread-* could be merged the same way somewhere at the start of the section.
