### ISSUE TITLE
Duplicate rights statements

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2353]
The second paragraph looks suspiciously like an artefact from a failed merge conflict resolution:

>When [EPUB creators](http://localhost:120/core/#dfn-epub-creator) do not include a rights.xml file, no part of the [OCF abstract container](http://localhost:120/core/#dfn-ocf-abstract-container) is rights governed at the container level. Rights expressions might exist within the EPUB publications.
>
> If EPUB creators do not include a rights.xml file, no part of the OCF abstract container is rights governed.

https://www.w3.org/TR/epub-33/#sec-container-metainf-rights.xml

**Comment by iherman** [comment]
That is clearly a bug. I believe the second statement must go.
