### ISSUE TITLE
Give example for rights.xml

### ISSUE THREAD

**Issue by OriKuttner** [mattgarrish/epub-revision#2359]
The spec. only states that an author my include rights.xml file but does not even give an example for such file.

**Comment by mattgarrish** [comment]
The file is reserved but its contents are not defined by the specification as drm schemes are out of scope. I'm not sure what an example would show that would be useful to authors.

There's arguably no point in reserving it given that we have no plans to define it, either. What file(s) and what scheme(s) people use to protect their publications isn't particularly relevant to their authoring, so whether we reserve it or not doesn't make much of a practical difference. It's not like we can enforce how it's used. Anyone can add any file they need to the meta-inf directory for this purpose.

**Comment by iherman** [comment]
I would be o.k. removing it altogether, but this may lead to backward incompatibilities issues; not in terms of epubcheck but more in terms of authors believing that they should not use this file any more (in case they did it).

I would propose to close this issue without any further action.
