### ISSUE TITLE
Does epub-tts-10 allow the use of PLS in EPUB 3.3 when PLS is not a core media type?

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2372]
PLS has been dropped from the list of core media types in EPUB 3.3.  Even if we have [epub-tts-10](https://www.w3.org/TR/epub-tts-10/), is PLS usable in EPUB 3.3?

**Comment by mattgarrish** [comment]
> Even if we have [epub-tts-10](https://www.w3.org/TR/epub-tts-10/), is PLS usable in EPUB 3.3?

Yes, you list them in an HTML `link` element, and resources listed from the link element do not require fallbacks. We didn't need to keep it as a CMT when we created the note.

To quote [section 3.4](https://w3c.github.io/epub-specs/epub33/core/#sec-exempt-resources):

> **Linked resources**
> 
> Any resource referenced from the [[html](https://w3c.github.io/epub-specs/epub33/core/#bib-html)] [link](https://html.spec.whatwg.org/multipage/#the-link-element) element that is not already a core media type resource (e.g., CSS style sheets) is an exempt resource.
