### ISSUE TITLE
Is this an error in the example?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#2387]
In [Example 40](https://www.w3.org/TR/epub-33/#example-manifest-flbk) it says:

```xml
        fallback="#page-001-svg"/>
```

I believe it should be

```xml
         fallback="page-001-svg"/>
```

(In any case, epubcheck flags the error...)

If that is correct, other occurrences may have to be looked for.

**Comment by mattgarrish** [comment]
Yup, per the spec:

> The fallback attribute's [IDREF](https://www.w3.org/TR/xml/#idref) [[xml](http://localhost:120/core/#bib-xml)] value MUST resolve to another item in the manifest.
