### ISSUE TITLE
Deprecate embedded audio or video as targets for Media Overlay <text> reference

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#2397]
My apologies for the verbose background below; I believe it is necessary to make an informed decision. This is not a widely known area of the spec…

This is the usual way of using Media Overlays (MO):

```xml
<html>
    …
    <p id="txt">...</p>
</html>

<smil>
    …
    <par>
        <text src="...#txt">
        <audio src="link_to_audio_file" clipBegin="…" clipEnd="…">
    </par>
    …
<smil>
```

On Reading Systems implementing MO, if read-aloud is switched on, the content of the audio file is read while the text in the XHTML content is rendered. 

However, what happens if we have, instead, the following:

```xml
<html>
    …
    <video id="movie">...</video>
</html>

<smil>
    …
    <par>
        <text src="...#movie">
        <audio src="link_to_audio_file" clipBegin="…" clipEnd="…">
    </par>
    …
<smil>
```

The answer is… it is complicated. There are indeed two time-dependent media rendering jobs in parallel (the movie and the audio clip), and the spec should be clear about which one has the upper hand in timing control. The problem is that it isn't ☹️: 

- [§9.2.2.4.1](https://www.w3.org/TR/epub-33/#sec-emb-audio-video) in the EPUB 3.3 content spec does _not_ talk about this case, only the case when there is _no_ audio element in the MO file. Specifying what is and isn't allowed would require further work.
- [§9.3.2](https://www.w3.org/TR/epub-rs-33/#sec-embedded-media) in the Reading System is a bit clearer; what it specifies is that the audio file's timing is in control: the video must be started by the RS when the audio starts, it must be stopped when the audio ends, the reader has no control over the video (only the RS has). But of course there are some other cases, see that section for details, which makes this specification _much_ more complicated. In my view that section requires further editorial work to make it clearer.

Some tests have been created for [§9.3.2](https://www.w3.org/TR/epub-rs-33/#sec-embedded-media) (see [`mol-embed`](https://github.com/w3c/epub-tests/tree/main/tests/mol-embed) or  [`mol-embed_deactivate_playback`](https://github.com/w3c/epub-tests/tree/main/tests/mol-embed_fxl)) but, at the moment, there are no known implementations around, and we may be looking at a problem at the end of the CR phase. Also: it is not clear what the use case may be for such a structure in the EPUB context. (If the goal is to add an audio track to a video as, say, background music, there are widely available video editing programs to do that more easily these days.)

(Note that this introduction only referred to video but, in fact, it could also be an audio track within the XHTML content document. The spec used the term "embedded media" as a general term, although that also includes still images.)

---

Sorry for the long introduction; here is the real issue I indent to raise. I think we should consider deprecating the feature of "embedded media" (maybe with the exception of still images). It is an overly complex part of the spec (mainly the RS spec) without known use cases and implementations; we can preempt the problems we will have at the end of the CR phase by doing so.

I can see several ways we could proceed:

1. declare the whole of [Content spec §9.2.2.4.1](https://www.w3.org/TR/epub-33/#sec-emb-audio-video) as well as [Reading System §9.3.2](https://www.w3.org/TR/epub-rs-33/#sec-embedded-media) a _SHOULD_ or _MAY_ (and avoid using _MUST_ statements in the text, much like the [§9.3.3 TTS](https://www.w3.org/TR/epub-rs-33/#sec-text-to-speech) section); or
2. we extract the use case whereby video or audio in a `<par>` without an accompanying `<audio>` means playing that media under the implementation control (without user control, that is), and we declare all other cases as deprecated; or
3. declare the whole feature as deprecated: the content document MO file disallows a reference to a video/audio from the `<text>` element (either directly or indirectly with a, say, video in the middle of a text flow with read loud) and the RS specification just says that handling those cases is implementation dependent.

I do not think we would create problems with existing EPUB deployment; indeed, I do not believe there is any out there... And it would make our spec cleaner.

**Comment by danielweck** [comment]
> Sorry for the long introduction

Ivan, thank you for your synthesis, the background information is very useful :)

>  I think we should consider deprecating the feature of "embedded media"

I would be in favour too, unless the necessity to preserve this functionality in the specification is backed-up by real-world uses cases + existing implementations.

In the original Readium SDK implementation we wanted to "tick that box" (from a "reference implementation" purist perspective) so we implemented audio/video play-pause control from SMIL, and we earned satisfaction from passing the tests.
However in the more recent (re)incarnation of Readium SDK (i.e. modernised architecture + complete rewrite) we decided to spend precious / expensive development time on other real-world aspects.

To a certain extent, the same rationale applies to TTS playback of targeted XHTML "textual" elements that do not have associated SMIL audio. I am personally not aware of many (any?) production-grade reading system that implements this feature, and of publishers / content creators that rely on this in their EPUB Media Overlays (it's not just a chicken/egg problem, there is also the issue of whether mixing carefully-recorded human narration with arbitrary synthetic voice makes sense from a content design perspective). But I digress! :)

UPDATE: see also https://github.com/w3c/epub-specs/issues/2007 ("Recognizing that the TTS is not a major usage of MO") and https://github.com/w3c/epub-specs/issues/1745 (" The features which have lack of support will be removed from normative specs when we go through the CR stage.") and https://github.com/edrlab/thorium-reader/issues/1515

**Comment by marisademeglio** [comment]
Diving into the spec editing that might happen if we do [option 3 in Ivan's comment](https://github.com/w3c/epub-specs/issues/2397#issue-1336935166)  -- 

For a long time, I've been uneasy with the embedded media section of the MO spec and I've advocated for removing it. Upon closer consideration, I think we should remove it but not disallow what we tried to define there.

So here is my editing suggestion; if this seems like a good route to take, I can submit a PR:

### Content spec

Deprecate [9.3.2.4](https://www.w3.org/TR/epub-33/#sec-embedded-media) entirely. Its two subsections are 

1. [embedded audio and video](https://www.w3.org/TR/epub-33/#sec-emb-audio-video) : This is primarily what we want to deprecate.
2. [embedded images](https://www.w3.org/TR/epub-33/#sec-emb-img), which says
> When a text element references an embedded image, the [audio](https://www.w3.org/TR/epub-33/#dfn-audio) sibling element is OPTIONAL. In the absence of an audio element, [reading systems](https://www.w3.org/TR/epub-33/#dfn-epub-reading-system) will voice the image using [text-to-speech rendering](https://www.w3.org/TR/epub-33/#sec-tts).

The above is redundant when compared with the [text element definition](https://www.w3.org/TR/epub-33/#sec-smil-text-elem)

and also says

>[EPUB creators](https://www.w3.org/TR/epub-33/#dfn-epub-creator) MUST ensure they provide fallback text for an image when an omitting an audio element (e.g., using the [[html](https://www.w3.org/TR/epub-33/#bib-html)] alt attribute).

This boils down to "you must make your content accessible", which as much as I agree, does not appear elsewhere in the spec, so why do it here? Further, the text element definition and the [TTS section](https://www.w3.org/TR/epub-33/#sec-tts) already discuss TTS.

So, I think we can remove both paragraphs of  [embedded images](https://www.w3.org/TR/epub-33/#sec-emb-img), at which point we have completely removed both of 9.3.4.2's subsections.

I would also add to the [text element definition](https://www.w3.org/TR/epub-33/#sec-smil-text-elem) a note that referring to embedded timed media is unspecified and may produce unpredictable results. So we're not disallowing it, we're just warning that it might not go well. 

### RS Spec
As for the RS spec, we can deprecate [9.3.2](https://www.w3.org/TR/epub-rs-33/#sec-embedded-media) entirely.

**Comment by iherman** [comment]
My only comment on @marisademeglio's proposal is about the RS Spec change. While I agree to remove [9.3.2](https://www.w3.org/TR/epub-rs-33/#sec-embedded-media) I think that, for consistency's sake, and some level of backward compatibility, we may want to add an editorial note at the start of [9.3](https://www.w3.org/TR/epub-rs-33/#sec-behaviors-interaction) containing something around the lines of:

> Earlier versions of this specification included some information about [embedded audio and video](https://www.w3.org/publishing/epub32/epub-mediaoverlays.html#sec-embedded-media) [epubmediaoverlays-32]. This feature has been **_deprecated_**.

Maybe a similar note can also be added to the content specification, but I am not sure about that one. The suggestion on adding a sentence to the text element definition may be enough.

**Comment by iherman** [comment]
Oh and, of course, these changes warrant a new item in the change logs of both specs.

**Comment by marisademeglio** [comment]
> Oh and, of course, these changes warrant a new item in the change logs of both specs.

@mattgarrish is this something you generate? Or should I make an edit somewhere as part of the PR?

**Comment by mattgarrish** [comment]
> @mattgarrish is this something you generate? Or should I make an edit somewhere as part of the PR?

The change logs have to be updated manually. You have to add a one or two sentence explanation of what's been changed and link back to this issue for reference. (I'd offer to add them, but I can't edit your fork.)

In this case, you should note the change in both the core and reading systems spec. The change logs are the last `section` in each document.

**Comment by brianagina** [comment]
My only concern is with @marisademeglio comment to deprecate embedding images as specified in [9.3.2.4.2](https://www.w3.org/TR/epub-33/#sec-emb-img). As an accessible EPUB developer, we had use cases where we have linked narrated audio with images through the smil files. It is a feature we use and have witnessed appreciation of by users in accessible EPUBs with Media Overlay implementation through text, images and audio. I agree on the deprecation of embedded audio and video as targets for Media Overlay but not images.

Does the new change logs deprecate 9.3.2.4.2](https://www.w3.org/TR/epub-33/#sec-emb-img)? If yes, how would that impact embedding images in EPUB and reading systems for developers and users that rely on it?

**Comment by mattgarrish** [comment]
I didn't notice any changes in the pull request that make referencing embedded images illegal (or even audio or video). Deprecation is probably the wrong way of phrasing what's happening with 9.3.2.4. It's more that it's become redundant to the `text` element's definition so it's simply been stripped out.

You can still reference images and include an audio description for them. Referencing audio and video is where things change, as if you do reference these now there's no expectation that reading systems will initiate playback (the playback behaviours are deprecated). They'd most likely be treated the same as any text element -- highlighted and the referenced audio played back.

**Comment by brianagina** [comment]
Thank you for the clarity @mattgarrish.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-08-26-epub#section1) on 2022-08-26

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-08-26-epub#resolution1):  Once the edits are finalized, merge PR 2402 and close issue 2397.***

<details><summary><i>View the transcript</i></summary>

### 1. Deprecate embedded audio or video as targets for Media Overlay `<text>` references.

_See github issue [epub-specs#2397](https://github.com/w3c/epub-specs/issues/2397)._




_See github pull request [epub-specs#2402](https://github.com/w3c/epub-specs/pull/2402)._




> *Ivan Herman:* See [Description of the issue background](https://github.com/w3c/epub-specs/pull/2402#issue-1340871554).

**Ivan Herman:** on a high level, what you can do with MO is associate a piece of time-stamped audio with a piece of text.  
… it is used in a bunch of a11y situations.  
… it is pretty well specified.  
… based on the tests I have made so far it is well implemented too.  
… however the specifications also try to allow association of an audio clip with a video (or several videos).  
… now you have two time related media side-by-side.  
… for that to work, the spec needs to define what is happening, considering that videos themselves often have UI controls themselves.  
… the spec tries to make some sense of this use-case, but this is really underspecified.  
… also, even for the cases which are relatively clear, we haven't found any implementations.  
… so we have a complicated case, underspecified in spec, and not implemented.  
… in side conversation with Avneesh, we did not find any important proper use case in a11y area.  
… the tests I created were trying to take a video and add a piece of background audio. But this is an artificial use case, as adding background audio to a video can be done much more easily in editing software rather than via MO.  
… so this lead to suggestion that we should just deprecate this type of video/audio MO from spec.  
… Marisa, mgarrish, and I opened #2397 to discuss.  
… based on this Marisa created PR #2402.  
… but we wanted to discuss with WG first.  

**Dave Cramer:** the fact that we don't have implementations of this weighs heavily to me.  
… reluctant to keep this in the spec for that reason.  

> *John Foliot:* is anyone aware of popcorn.js?.

**Ivan Herman:** is there any use-cases for this in the a11y area which requires this?.  
… MO has been included in the spec primarily for a11y reasons, although it is useful for other things.  

**George Kerscher:** i agree generally. Audio descriptions for the blind is implemented in TV as a second audio channel that can be turned on.  
… don't know the technology behind it (mixer behind the scenes that combines audio channels?).  
… don't know that we can break new ground here by adding that feature, but its something people would want.  
… what happens with descriptive audio is that the on-screen action is described for the blind person.  

> *John Foliot:* [http://ncamftp.wgbh.org/rd/hgp/hgp.html](http://ncamftp.wgbh.org/rd/hgp/hgp.html).

> *John Foliot:* watch the example at: [http://ncamftp.wgbh.org/rd/hgp/hgp.html](http://ncamftp.wgbh.org/rd/hgp/hgp.html).

**John Foliot:** there is a package called popcorn.js. Work done a while back by WGBH, where they were using this js library to use time-stamp markers to activate functions.  
… this is a demonstrated use-case, but i'm not aware of anyone who has taken this and run with it.  
… not sure that we need this in our spec, as long as we're not frustrating the use of it in epub.  

**Avneesh Singh:** this is removal of 9.3.2 from the RS spec. No one is blocking the creation of such MO files.  
… say you have a video going on, and you need description for it, MO doesn't seem like a good solution for this.  

**Ivan Herman:** the largest part of the MO concentrates on associating audio track with text.  
… this is not being touched.  
… the section that is affected is "embedded-media overlays", i.e. where HTML includes a video track.  
… to what John said, if there are js libraries that can do things in a website, they can do it in an epub as well. No problem..  
… what you described is a nice tool that can be used to get additional feature while a video is running. This can work in an epub as well.  

**Wendy Reid:** agreed. I think we're just removing something that is creating confusion/opening ourselves up to adding another unimplemented feature.  
… i haven't seen this in an epub or in any RS.  
… description of video of visually impaired is not done via MO.  
… RS would have to implement accessible media-player or epub would have to come with one, larger problem.  

> *John Foliot:* More info about accessible media requirements: [https://www.w3.org/TR/media-accessibility-reqs/](https://www.w3.org/TR/media-accessibility-reqs/).

**Ivan Herman:** can we pass a resolution that once editors are ready, that we can merge PR #2402?.  

> **Proposed resolution: Once the edits are finalized, merge PR 2402 and close issue 2397.** *(Wendy Reid)*

> *Matthew Chan:* +1.

> *Wendy Reid:* +1.

> *Dave Cramer:* +1.

> *GeorgeK:* +1.

> *Ivan Herman:* +1.

> *Brady Duga:* +1.

> *Masakazu Kitahara:* +1.

> *Avneesh Singh:* +1.

> *John Foliot:* +1.

> *Charles LaPierre:* +1.

> ***Resolution #1: Once the edits are finalized, merge PR 2402 and close issue 2397.***

</details>
