### ISSUE TITLE
EPUB 3.3 specs - Error in Example 53?

### ISSUE THREAD

**Issue by MyDK** [mattgarrish/epub-revision#2403]
[EXAMPLE 53](https://www.w3.org/TR/epub-33/#example-hiding-a-nav-element-in-spine): Hiding a nav element in spine
`<nav epub:type="page-list"  hidden="">`
Shouldn't 'hidden' be added? 
`<nav epub:type="page-list" hidden="hidden">`

**Comment by iherman** [comment]
See comment in PR #2404 which also adds the value to the example.

Thank you.
