### ISSUE TITLE
Clarify only publication resources are listed in the manifest

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2413]
I noticed that while we do explain that outbound hyperlinks are not publication resources in the term's definition, we don't say that the manifest is only for listing publication resources. Currently, we only say:

> EPUB creators MUST list all publication resources in the manifest, regardless of whether they are container resources or remote resources, using item elements.

But this doesn't make it invalid to list non-publication resources. It might be better to make the restriction explicit:

> EPUB creators MUST list all publication resources in the manifest regardless of whether they are container resources or remote resources. Moreover, the manifest MUST only list publication resources.

(I ran into this trying to place an epubcheck restriction on listing hyperlinked resources on the web.)

**Comment by rdeltour** [comment]
This issue slipped under my radar.

For the (late) record, EPUBCheck reports files present in the container but not listed in the manifest as a `WARNING`, it has done so for a long while.

In any case, I'm not convinced that making the restriction explicit is very useful:
- it is not enforceable by a conformance checker
- what constitutes a "publication resource" is not defined unambiguously enough to make that statement crystal clear
