### ISSUE TITLE
Should empty property data type references be valid?

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2417]
The question of whether a prefix-only property data type value is valid came up earlier, and we clarified that it is allowed (in keeping with CURIEs).

But how do we square this with requiring a `meta` element's `property` attribute to reference a property? By our current definition, the following is valid: `<meta property="foo:">bar</meta>`

The only place a "URL-only" prefix makes sense in a `scheme` attribute. Everything else requires a reference value (i.e., the property).

Do we have to go back through each attribute and clarify the ones that have to have a reference at least one character in length, or should we go back to the way things were when we expected all attribute values to be an optional prefix followed by a reference? (i.e., say that although an empty path-relative-scheme-less-URL string is valid, it is not a valid reference)

**Comment by iherman** [comment]
> Do we have to go back through each attribute and clarify the ones that have to have a reference at least one character in length, or should we go back to the way things were when we expected all attribute values to be an optional prefix followed by a reference? (i.e., say that although an empty path-relative-scheme-less-URL string is valid, it is not a valid reference)

Sigh... you are right.  I think the second option is the cleanest.
