### ISSUE TITLE
Is the requirement for links to reference resources by path clear enough?

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2420]
The link element's definition says:

> The [metadata element](https://www.w3.org/TR/2022/WD-epub-33-20220302/#sec-metadata-elem) MAY contain zero or more link elements, each of which identifies the location of a linked resource in its REQUIRED href attribute.

And the href attribute says:

>A [valid URL string](https://url.spec.whatwg.org/#valid-url-string) [url] that references a resource.

Is this sufficiently clear that, for example, `<link href="#item-001"/>` is invalid? Or should we be more explicit that referencing manifest items - or spine itemrefs or anything else in the package document - is invalid:

> A [valid URL string](https://url.spec.whatwg.org/#valid-url-string) [url] that references a resource. The URL string MUST NOT be a reference to an element in the package document (e.g., to a manifest `item` or spine `itemref`).

**Comment by iherman** [comment]
+1 to the additional explicit restriction. (Does epubcheck already checks that?)

**Comment by mattgarrish** [comment]
> (Does epubcheck already checks that?)

Yes, I'm double-checking all the tests and requirements as I go. Epubcheck has a test that disallows link references to manifest IDs, but the spec requirement wasn't completely clear which section bans this.
