### ISSUE TITLE
Explain legacy elements

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2423]
There still seems to be confusion about the purpose of the legacy elements. They exist only for allowing EPUB 3s to render, as much as possible, in EPUB 2 reading systems.

The spec doesn't introduce this purpose in the package document's legacy content section, so it requires users to follow the link on the word legacy in almost all cases to get to the definition (oddly, we explain the purpose for the meta element in a note).

I wonder if we should even bother having legacy elements described in the unsupported features section, since they only apply to those elements (plus the toc attribute for referencing the NCX). It would be clearer to move the prose up to the section.

**Comment by iherman** [comment]
> There still seems to be confusion about the purpose of the legacy elements. They exist only for allowing EPUB 3s to render, as much as possible, in EPUB 2 reading systems.

I did not realize this either... (and my slides were not explicit on this either)

> I wonder if we should even bother having legacy elements described in the unsupported features section, since they only apply to those elements (plus the toc attribute for referencing the NCX). It would be clearer to move the prose up to the section.

You mean moving §A3 into §5.9 and that would be all about legacy elements? Yes, I think it simplifies things.

**Comment by mattgarrish** [comment]
> You mean moving §A3 into §5.9 and that would be all about legacy elements?

Yes, this is where I'm thinking I'll end up, but I'm still toying with the arrangement in a PR to fix this and #2424.

The legacy features are solely in the package document, so it's not like we need a generic label to apply throughout the spec.
