### ISSUE TITLE
Reading system requirements in the authoring spec

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2424]
The requirements for how reading systems handle unsupported features would seemingly belong in the reading system specification now. It's the only case where we still have crossover requirements.

**Comment by iherman** [comment]
Do you mean moving §A to the RS spec altogether? Or only the bullet items in §A.1 and §A.2? I am not sure moving the whole appendix is a good idea, but moving the RS entries is indeed cleaner.

**Comment by mattgarrish** [comment]
> Or only the bullet items in §A.1 and §A.2?

Yes, I don't think we need anything more than to create an appendix that lists the support requirements for each type in the reading system spec. That list can link across to the core spec for more information. I'm working on a PR to clean this up.
