### ISSUE TITLE
ARIA support requirement

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2431]
Can we drop [6.1.1.1 ARIA](https://w3c.github.io/epub-specs/epub33/rs/#sec-xhtml-aria) of the Reading Systems specification?

I'm not sure this adds anything to [3.2.9 Requirements related to ARIA and to platform accessibility APIs](https://html.spec.whatwg.org/multipage/dom.html#wai-aria) of the HTML spec.

The HTML spec references HTML-AAM, which in itself makes it more specific than our section about what exposing ARIA means. Our section is not so much an extension as a less specific repetition.

Looking back at the old HTML 5.0 spec at the time we released EPUB 3, there wasn't a similar support section, only some of what became ARIA in HTML. That's no doubt why it was originally added, but it appears to have outlived its usefulness.

/cc @avneeshsingh @GeorgeKerscher @clapierre

**Comment by wareid** [comment]
As usual, I'm in full support of doing anything to make the spec clearer but also avoid redundancy within the W3C ecosystem.
