### ISSUE TITLE
Add error handling and reporting sections

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2454]
https://github.com/w3c/epub-specs/pull/2449#issuecomment-1269809452 and https://github.com/w3c/epub-specs/pull/2453#discussion_r992543790 raise the question of whether we should include some information about error handling and reporting.

The most logical place for these would probably be as subsections of "2. Reading system conformance".

The error handling section could use the text proposed in the referenced discussion:

> This specification does not require reading systems to load EPUB publications, or resources within them, when they violate content authoring or processing requirements (e.g., they define entities in an external DTD subset).

If we add an error reporting section, should we say that reading systems "SHOULD" provide a way for users to access any issues the RS encountered loading a publication? I know not every reading systems will implement an EPUB version of the browser dev tools, or will report every issue, but it would certainly make life easier for users if they did. Saying that they may provide reporting doesn't really move the needle much.

**Comment by iherman** [comment]
Personally, I believe I would favor a SHOULD for the error reporting, but the majority of participants, including RS manufacturers, were in favor of MAY.

**Comment by mattgarrish** [comment]
That's too bad. I fully understand not wanting users to have errors and warnings reported at them while reading, but having some way of finding out what is happening under the hood, even just a toggle from a settings menu, seems more helpful than harmful.
