### ISSUE TITLE
Editorial: `meta` points to the package doc element instead of HTML element in F.2

### ISSUE THREAD

**Issue by rdeltour** [mattgarrish/epub-revision#2456]
In [F.2 Syntax](https://www.w3.org/TR/2022/CRD-epub-33-20221003/#app-viewport-meta-syntax):

> A viewport [meta](https://www.w3.org/TR/2022/CRD-epub-33-20221003/#dfn-meta) tag [[html](https://www.w3.org/TR/2022/CRD-epub-33-20221003/#bib-html)] MUST have name and content attributes that conform to the following definition

`meta` refers to the package document element rather than the HTML element. I don't know ReSpec enough to submit a PR 😅.

**Comment by iherman** [comment]
Oops... thanks @rdeltour. For the sake of simplicity, and to avoid unnecessary PR-s, I have incorporated the fix in #2453
