### ISSUE TITLE
Spaces in file names

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2458]
While going through epubcheck's tests, I noticed that it throws an error if file names have spaces in them. We previously discussed whether these should be allowed in https://github.com/w3c/epub-specs/issues/808

But in this revision we've changed to referencing the URL standard, so should we revist this issue again? Otherwise, it's strange for epubcheck to ban them when that specification doesn't.

I'm not suggesting we have to allow spaces now, as suddenly allowing spaces may expose interoperability issues hidden by the previous ban, but perhaps we should add a recommendation/restriction against their use to the OCF file and path naming section? It would help to have epubcheck aligned with spec requirements so it's not seen as adding arbitrary restrictions.

**Comment by OriKuttner** [comment]
I think we should disallow spaces in the spec.
At least say that spaces SHOULD NOT be used in file names.
I'd even prefer MUST NOT.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by iherman** [comment]
> While going through epubcheck's tests, I noticed that it throws an error if file names have spaces in them. We previously discussed whether these should be allowed in #808
> 
> But in this revision we've changed to referencing the URL standard, so should we revist this issue again? Otherwise, it's strange for epubcheck to ban them when that specification doesn't.
> 
> I'm not suggesting we have to allow spaces now, as suddenly allowing spaces may expose interoperability issues hidden by the previous ban, but perhaps we should add a recommendation/restriction against their use to the OCF file and path naming section? It would help to have epubcheck aligned with spec requirements so it's not seen as adding arbitrary restrictions.

That sounds like a wise decision/approach to me. This is also in line with the _SHOULD NOT_ proposal of @OriIdan.

That being said, if it is a _SHOULD NOT_ then epubcheck should issue a warning instead of an error, shouldn't it?

**Comment by rdeltour** [comment]
> That being said, if it is a _SHOULD NOT_ then epubcheck should issue a warning instead of an error, shouldn't it?

Correct.

That said, if I'm not mistaken, this is already the case. EPUBCheck reports spaces in file names as PKG-010, which is a warning.

**Comment by mattgarrish** [comment]
> EPUBCheck reports spaces in file names as PKG-010, which is a warning.

Right, the error is if you leave the space unencoded, which should be illegal regardless of any change we make.

**Comment by rdeltour** [comment]
I just noticed that PR #2459 only recommends not to use SPACE (U+0020). Shouldn't other whitespace characters be included there too?

**Comment by OriKuttner** [comment]
I agree, all white space should not be used.

**Comment by mattgarrish** [comment]
> Shouldn't other whitespace characters be included there too?

Is it realistic anyone has or would use other whitespace in file names? I'd opt for simplicity and keep the recommendation to space characters since these are likely to be used.

I don't want to spend forever controlling file names! 😄 What characters you can use for optimum compatibility should really be authoring best practices, not spec enforced.
