### ISSUE TITLE
Character restrictions don't apply to file paths?

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2460]
Is it correct that you can use any characters you want in file paths with the only [restrictions on file names](https://w3c.github.io/epub-specs/epub33/core/#ocf-fn-chars)?

Seems odd, although we can't just add file paths without separating out solidus and reverse solidus.

**Comment by rdeltour** [comment]
FWIW, EPUBCheck currently enforces the restrictions on both paths and names…

**Comment by mattgarrish** [comment]
Looks like I should have checked the definitions closer. File name also encompasses directory name, so the path is covered by extension. Closing as invalid.
