### ISSUE TITLE
Encoding in the abstract container

### ISSUE THREAD

**Issue by rdeltour** [mattgarrish/epub-revision#2461]
It's mostly a detail, but something struck me as maybe out of place in the file paths and names restrictions.

The spec says:
> file names and paths MUST be UTF-8 [unicode] encoded

What does it mean to talk about encoding in the abstract container? Encoding is a concrete thing that happens when actually storing the info.

The ZIP section already requires:
> OCF ZIP containers MUST encode File System Names using UTF-8 [unicode].

**Comment by rdeltour** [comment]
I'm suggesting maybe referring to the Infra string type (or scalar value string?) in the definition of file path and file name.

**Comment by mattgarrish** [comment]
> OCF ZIP containers MUST encode File System Names

Is "file system names" in caps for a bit of imperiousness?

It seems to have been that way forever for no particular reason. The zip appnote makes no reference to it as a term.

**Comment by mattgarrish** [comment]
> maybe referring to the Infra string type (or scalar value string?) in the definition of file path and file name

What if the first sentence of the section incorporated it:

> In the context of the OCF abstract container, file paths and file names are case sensitive scalar value strings [infra].

**Comment by rdeltour** [comment]
> What if the first sentence of the section incorporated it:

>> In the context of the OCF abstract container, file paths and file names are case sensitive scalar value strings [infra].

Looks better to me!
To nitpick even more: case sensitiveness is implied (upper/lower case characters are two different code points), it could be moved to a note.

**Comment by mattgarrish** [comment]
> case sensitiveness is implied (upper/lower case characters are two different code points)

Sure, if all we're considering is code points, but isn't the issue here the virtual file system of the abstract container? If we remove this as a normative statement, doesn't that mean they can be handled case insensitively and it doesn't matter?
