### ISSUE TITLE
Inconsistency in description of linked resources

### ISSUE THREAD

**Issue by Jesse-Bakker** [mattgarrish/epub-revision#2467]
The description of linked  resources is inconsistent between the `1.4 Terminology` and `5.5.7 The link element` sections in the 3.3 spec.

In the "Terminology" section it is stated that "linked resources" are NOT "publication resources", whereas the "The link element" section states two exceptions to this.

https://github.com/w3c/epub-specs/blob/61af852e4ec1d377fb2c4238c6cae8d08bc7420b/epub33/core/index.html#L488-L497

https://github.com/w3c/epub-specs/blob/61af852e4ec1d377fb2c4238c6cae8d08bc7420b/epub33/core/index.html#L4553-L4574

To make these sections consistent, I see two resolutions:

 - 5.5.7: The link element identifies the location of a `publication resource` OR a `linked resource`
 - 1.4 uses the definition from 5.5.7

**Comment by mattgarrish** [comment]
The definition is correct. Linked resources are only referenced from `link` elements. Publication resources can also be referenced from the `link` element, but that doesn't make them linked resources.

But I agree that the line at 4557 makes the distinction confusing. It shouldn't reuse "Linked resource" to talk about publication resources. It should say something more like "Resources referenced from the `link` element are considered [=publication resources=], not linked resources, when they are: ..."

**Comment by Jesse-Bakker** [comment]
Thank you for the clarification. The reuse of the term "linked resource" is indeed what caused my confusion.

To make the 5.5.7 section internally consistent, a few more textual changes are needed. I can send a PR with a proposed rewording of the 5.5.7 section if you'd like
