### ISSUE TITLE
Spine properties vocabulary should mention mutual exclusivity of page spread properties

### ISSUE THREAD

**Issue by Jesse-Bakker** [mattgarrish/epub-revision#2468]
`itemref` + D.7 state that the default vocabulary for `itemref` elements consists of `page-spread-left` and `page-spread-right`. These are probably meant to be mutually exclusive, and I therefore propose the wording for these to be clarified, adding something like (for the page-spread-left property):

> This property is mutually exclusive with the `page-spread-right` property. EPUB creators MUST NOT include the `page-spread-right` property on elements carrying the `page-spread-left` property.

and vice versa on the page-spread-right property.

**Comment by Jesse-Bakker** [comment]
This is already mentioned in section "8.2.2.4 Spread placement", so linking to that section should also suffice

**Comment by iherman** [comment]
Although, indeed, the statement is in §8.2.2.4, putting a reference to that single paragraph would make the text unreadable. I'd propose to copy the statement from §8.2.2.4 to right after the definition of the two properties. See #2470.
