### ISSUE TITLE
Example of non-textual descendant concatenated label in nav elements

### ISSUE THREAD

**Issue by Jesse-Bakker** [mattgarrish/epub-revision#2477]
[Section 7.3 The nav element: restrictions](https://www.w3.org/TR/epub-33/#sec-nav-def-model) states:

> The child a or span element MUST provide a non-zero-length text label after concatenation of all child content and application of white space normalization rules. When determining compliance with this requirement, the concatenated label MUST include text content contained in title or alt attributes for non-textual descendant elements.

> If an a or span element contains instances of [HTML embedded content](https://html.spec.whatwg.org/multipage/dom.html#embedded-content-category) [[html](https://www.w3.org/TR/epub-33/#bib-html)] that do not provide intrinsic text alternatives, the element MUST also contain a title attribute with an alternate text rendering of the link label.

These rules could use an example to clarify what constitutes a valid text label in the presence of nested child elements and embedded content, like

```xml
<nav epub:type="…">
   <h1>…</h1>
   <ol>
      <li>
         <a href="chap1.xhtml">
            <audio src="..."/>
            <audio src="..." title="Chapter 1"/>
         </a>
      </li>
      <li>
         <span>
             <img src="..." alt="Chapter 2"/>
         </span>
         <ol>...</ol>
      </li>
   </ol>
</nav>
```

**Comment by mattgarrish** [comment]
Do any reading systems support images, audio, video, etc. in the table of contents? There isn't even a requirement in the reading system specification to make use of text alternatives, and none of the reading systems I've tried support images or use the label (sometimes you get the url in the src attribute, other times a generic text label, and one even had empty links).

Adding an `audio` element crashed one, and others incorrectly used the fallback text and ignored the label.

At this point, we might want to consider advising people not to use these kinds of elements in the nav document.

**Comment by iherman** [comment]
@mattgarrish do we have any tests for these, actually. It would be worthwhile doing at least one; we may then decide to declare these as under-implemented. (Adding a note that you refer to is worth doing in any case.)

**Comment by Jesse-Bakker** [comment]
Under-implementation of non-textual navigation elements by reading systems might be due to under-specification in the reading system spec. If EPUB creators do not know how their content might appear on reading systems and reading systems do not have guidance in how to fall back on textual content in navigational UI, this "feature" becomes very difficult to implement for both EPUB creators and reading system implementations.

It might be worth checking whether there is even any desire for non-textual navigation elements from publishers and specifying composition of textual fallback labels if there is, or restricting to textual content if there is not.

I am, however, not sure if that is in scope.

**Comment by mattgarrish** [comment]
> do we have any tests for these, actually.

I wouldn't expect so, since there isn't a requirement attached to using the text alternatives. It'd require something like: "If a reading system does not support embedded media within table of contents entries, it MUST use the text labels associated with these elements when generating the entries."

**Comment by mattgarrish** [comment]
> Under-implementation of non-textual navigation elements by reading systems might be due to under-specification in the reading system spec.

It's actually an old problem related to having HTML markup for display but reading systems creating navigation widgets that don't support the features of HTML. It's more commonly come up in the past when publishers realize that adding styling elements like bolding and italics have no effect in these widgets (and I recall someone had tried to put mathml in to no effect).

We've sort of informally capitulated on the ideal of the navigation document being usable both in spine and for machine processing, accepting you may have to make two separate tocs so the more advanced features are only in-spine, but the specification doesn't reflect that for the wider publishing community.

We're too late in the process of 3.3 for a major re-engineer of the nav element restrictions, so a note of authoring caution may be all we can add this time around.

**Comment by Jesse-Bakker** [comment]
> We're too late in the process of 3.3 for a major re-engineer of the nav element restrictions, so a note of authoring caution may be all we can add this time around.

This is what I suspected.

 > ... you may have to make two separate tocs so the more advanced features are only in-spine ...

It might be useful to add this to the note:

 > Support for HTML markup in dedicated navigation widgets is largely unsupported. If advanced markup is required, EPUB creators are recommended to create an additional content document including this advanced markup for use in the spine.

**Comment by iherman** [comment]
I am fine with just a note.

**Comment by Jesse-Bakker** [comment]
Thanks. The added example and reading system spec changes clarify the nav usage greatly.
