### ISSUE TITLE
`epub:type` restricted to palpable content may cause backward incompatibilities

### ISSUE THREAD

**Issue by rdeltour** [mattgarrish/epub-revision#2486]
In EPUB 3.3, [XHTML requirements](https://www.w3.org/TR/2022/CRD-epub-33-20221124/#sec-xhtml-structural-semantics) says the `epub:type` attribute MUST only be used on [palpable content](https://html.spec.whatwg.org/multipage/dom.html#palpable-content-2).

This list is restrictive and will likely cause a lot of existing material being rejected. Several HTML elements like `body` or `li` are not palpable content but are often associated an `epub:type` attribute (they're defined as relevant usage context in the [structural semantics vocabulary](https://www.w3.org/TR/epub-ssv-11/)).

Also, it means `epub:type` and `hidden` cannot co-exist, I'm not sure how that's relevant.

Was the idea was to not allow `epub:type` on some elements like `head` and `style`?

If yes, we could either:
- restrict `epub:type` to any element except [metadata content](https://html.spec.whatwg.org/multipage/dom.html#metadata-content) and the `html` element.
- restrict `epub:type` to [flow content](https://html.spec.whatwg.org/multipage/dom.html#flow-content) and the `body` element.

**Comment by mattgarrish** [comment]
epub:type is not supposed to be used on the head element or within it as the header doesn't contain structural content.

The restriction was previously only on reading systems to ignore the attribute in the `head` element, but an authoring restriction was added to match. Agree that palpable doesn't look right.

I'm fine switching it to "MUST NOT be used on the `head` element or on metadata content". This would also capture uses on `script`, `link`, etc. in the body, as these are not structural elements in the sense that the attribute was created for.
