### ISSUE TITLE
[editorial] fallback clarification for script data blocks might be confusing

### ISSUE THREAD

**Issue by rdeltour** [mattgarrish/epub-revision#2487]
The [fallback clarification for the HTML `script` element](https://www.w3.org/TR/2022/CRD-epub-33-20221124/#html-script-element) says:

> Although the script element lacks intrinsic fallback capabilities, it is not required that EPUB creators provide fallbacks for data blocks.

I find the "it is not required" part somewhat (slightly) confusing, since one could think it is still possible albeit optional. But in fact, script data blocks cannot be in a standalone file, so as such they cannot be listed in the manifest, and consequently have a manifest fallback.

So it's not only that "it is not required that EPUB creators provide fallbacks", but even more so "it is impossible that EPUB creators provide fallbacks".

I'm suggesting to reword the whole paragraph and first note to clarify this. Maybe something along these lines:

> Although the [[html](https://www.w3.org/TR/epub-33/#bib-html)] [script](https://html.spec.whatwg.org/multipage/scripting.html#script) element lacks intrinsic fallback capabilities, [data blocks](https://html.spec.whatwg.org/multipage/#data-block) [[html](https://www.w3.org/TR/epub-33/#bib-html)] cannot be listed in the manifest and consequently cannot be given a manifest fallback.
>> NOTE  
>> Data blocks do not directly represent user content; they are not rendered unless manipulated by script. As such, the impossibility to assign fallback to data blocks is aligned with the exemption made to [allow data files](https://www.w3.org/TR/2022/CRD-epub-33-20221124/#confreq-foreign-no-fallback) to travel in the [EPUB container](https://www.w3.org/TR/2022/CRD-epub-33-20221124/#dfn-epub-container).

**Comment by mattgarrish** [comment]
It is pretty clunky. Looks like the result of trying to shoehorn the exemption into a section on clarifying intrinsic fallback capabilities. I'd like to rewrite it even more drastically to:

> Although data blocks have a separate MIME media type [rfc2046] from their containing XHTML content document, it is not possible to provide intrinsic fallbacks as there are no mechanisms for the [html] [script](https://html.spec.whatwg.org/multipage/scripting.html#script) element. It is also not possible to provide manifest fallbacks because data blocks are always embedded in a script element.

> 
> But, as the script element does not represent user content — [data blocks](https://html.spec.whatwg.org/multipage/#data-block) are not rendered unless manipulated by script, and content rendered by scripts already has core media type requirements — requiring fallbacks for the raw data does not serve a useful purpose.

> 
> Consequently, to ensure that EPUB creators can include data blocks for scripting purposes, they are exempt from fallback requirements.

> 
> NOTE
> This exemption aligns data blocks with the exemption for data files.

(I'll open a PR with some additional linking to discuss further.)
