### ISSUE TITLE
Clarify intra-publication EPUB CFI leading step

### ISSUE THREAD

**Issue by Jesse-Bakker** [mattgarrish/epub-revision#2492]
> For a [standard EPUB CFI](https://w3c.github.io/epub-specs/epub33/epubcfi/#dfn-standard-epub-cfi), the leading step in the CFI MUST start with a slash (/) followed by an even number that references the spine child element of the package document's root package element. The package document traversed by the CFI MUST be the one specified as the Default Rendition in the EPUB publication's META-INF/container.xml file (i.e., the package document referenced by the first rootfile element in container.xml).

> For an [intra-publication EPUB CFI](https://w3c.github.io/epub-specs/epub33/epubcfi/#gloss-intra-publication-epub-cfi), the first step MUST start with a slash followed by a node number that references a position in package document starting from the root package element.

A "standard EPUB CFI" has to point to the spine, whereas an "intra-publication EPUB CFI" does not. It is however unclear from the specification what the purpose of this distinction is.
The only indirection in the package document that is resolvable is an itemref in the spine and I can see no use-cases for pointing into the package document without indirection.

**Comment by mattgarrish** [comment]
Closing this issue because we're not working on the CFI specification in W3C at this time. Please feel free to keep discussing the issue even while closed, as the abandoned label is so we can resurrect these issues if the specification is picked up in the future.
