### ISSUE TITLE
Clarify meaning of "form elements"

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2497]
The definition of the scripted property says:

> The scripted property indicates that the described [publication resource](https://www.w3.org/TR/epub-33/#dfn-publication-resource) is a [scripted content document](https://www.w3.org/TR/epub-33/#dfn-scripted-content-document) (i.e., contains scripted content and/or HTML form elements).

It's not clear whether "form elements" should be a reference specifically to the `form` element or whether it encompasses all the [forms elements](https://html.spec.whatwg.org/multipage/forms.html#forms).

The reading system spec isn't a lot more helpful:

> This specification does not require EPUB reading systems to support scripting, HTML forms or the HTML DOM.

But we addressed this in https://github.com/w3c/epub-specs/pull/1060 by adding a section that it's support for form submission that is optional.

Suggest we fix the reading system spec to point to the form submission section and make the scripted property reference the `form` element specifically because HTML has a whole section on form elements (input, button, etc.). Since form elements don't have to appear in a `form` anymore, I don't expect it was ever the intention that the presence of any of these should require a `scripted` property setting.

**Comment by iherman** [comment]
I certainly only understood this to refer to the `<form>` element only. So +1 to what you propose.
