### ISSUE TITLE
Missing <p> ids in security recommendations

### ISSUE THREAD

**Issue by GJFR** [mattgarrish/epub-revision#2533]
Paragraphs containing normative statements in the [Recommendations section](https://www.w3.org/TR/epub-rs-33/#security-privacy-recommendations) concerning security and privacy seem to be missing id attributes.

I suspect id attributes should be added if these statements are to be tested, such that each test's `package.opf` file can refer to the specific statement by using the id as an anchor tag?

**Comment by iherman** [comment]
@GJFR, the practice we have is to add an ID (and a reference to the test) when a test is added to the test suite itself. Ie, a separate Pull Request will be necessary on the recommendation spec, adding not only an ID but also a reference to the test.

If it is a hurdle, do not worry about it now. If you have a proper test (thanks for it!) then I am happy to make the necessary adjustments.

**Comment by GJFR** [comment]
OK, thanks for the clarification @iherman! Was not sure whether normative statements without such an ID were intended to be tested.

**Comment by iherman** [comment]
Closing as resolved via several PR-s on the matter (e.g., #2527 and friends)
