### ISSUE TITLE
deprecated `navigator.epubReadingSystem.name` used in example

### ISSUE THREAD

**Issue by npdoty** [mattgarrish/epub-revision#2543]
I believe `navigator.epubReadingSystem.name` has been deprecated, and replaced with feature detection, but there is still an example that uses it in "H.2 Scripting contexts".

**Comment by mattgarrish** [comment]
The script element with the reference can be removed without affecting anything about the example itself. Not sure why it was put in there.

**Comment by iherman** [comment]
I think having the script element kept there is better; good to have an example for such a construction just to show. I simply exchanged the usage of the `name` attribute to `hasFeature` and slightly reformulated the script content.

Thanks @npdoty. See #2544
