### ISSUE TITLE
Variable Fonts 

### ISSUE THREAD

**Issue by davelab6** [mattgarrish/epub-revision#2545]
https://twitter.com/KyriosityTweets/status/1636896943162142720?t=8BX4CnPRWTTrDroqNPKeAw&s=19 prompted me to check the epub spec and indeed it seems variable fonts are not supported.

Apologies that I'm a big ol' newbie to this, but what would the process be to develop support?🥳

VF has been a standardized and widely implemented font technology since 2016, so I was pretty surprised to hear that epub doesn't support it, given it's web platform basis 😅

**Comment by mattgarrish** [comment]
The link you posted seems to go to a missing page so I'm not sure why you're saying they're not supported. EPUB supports [OpenType fonts](https://w3c.github.io/epub-specs/epub33/core/#cmt-grp-font), although that doesn't necessarily mean that reading systems will render variable fonts as intended.

If the problem is support in reading systems, then maybe this is an issue for testing.

**Comment by davelab6** [comment]
That's odd, here's a screenshot I just took :)

![Screenshot_20230320-222858](https://user-images.githubusercontent.com/261579/226517398-56e1e52f-f3e5-4a80-a6e1-81291b086ce5.png)

Where would I set the equivalent of font-variation-settings CSS property, and font-optical-sizing?

**Comment by mattgarrish** [comment]
> Where would I set the equivalent of font-variation-settings CSS property, and font-optical-sizing?

In a CSS style sheet for the xhtml page, or any other way you would for the web generally. EPUBs are just packaged web content.

There aren't any restrictions on what CSS properties you can use, but, again, there could very likely be support issues in the wild, just like with browser support for anything new(-ish). I've never personally tried using variable fonts, so I don't have any insight into which reading systems do or do not support their rendering.

But unless there's something specifically that epubcheck flags as an error (unable to link to/import the fonts, unable to list them in the manifest, invalid CSS, etc.), it doesn't sound like the EPUB specification needs to be changed to allow their use.

As for how to improve support, EPUB is currently going through the W3C standardization process so there's a testing group checking support for features. I'm not sure if this is in scope (they're not testing every aspect of every technology that can be used), but it would be one way to expose support issues. The other, of course, is to test manually and open bugs against the major reading systems that don't support rendering.

There was an idea of creating a bug tracker for logging issues against all reading systems but it [doesn't look like it panned out](https://github.com/w3c/epub-rs-bugs/issues). Maybe someone involved can speak to it.

**Comment by dauwhe** [comment]
The EPUB spec uses the [CSS Snapshot](https://www.w3.org/TR/css-2023/) as a guide to what CSS should be supported by reading systems. This allows EPUB to evolve as the underlying web standards evolve. 

This snapshot includes [CSS Fonts Level 3](https://www.w3.org/TR/css-fonts-3/), which does not include variable fonts. Those are defined in [Level 4](https://drafts.csswg.org/css-fonts-4/), which is still under development.

**Comment by davelab6** [comment]
That explains it! Any ballpark timeline for L4?

**Comment by mattgarrish** [comment]
It sounds like we can close this issue with no action required. You can include OpenType variable fonts in an EPUB and reference the CSS properties, so nothing needs fixing from an authoring perspective. And because we reference the latest CSS snapshot, it will automatically be recommended to support Level 4 Fonts when that spec becomes stable.

**Comment by davelab6** [comment]
Excellent, thank you for explaining
