### ISSUE TITLE
Clarify epub:type use with embedded SVG

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2555]
As reported in https://github.com/w3c/epubcheck/issues/1497#issuecomment-1518634823, the specification is not clear that the restriction on where `epub:type` can be used with svg content documents also applies to embedded svg. The restriction should either be in the referenced restrictions section or there should be a separate section for semantics that embedded svg definition can reference.

**Comment by iherman** [comment]
A valid erratum, I believe, and it should be marked as such. Clearly a [class 2](https://www.w3.org/2023/Process-20230612/#class-2)...

@shiestyle @TzviyaSiegman @dauwhe @wareid

**Comment by mattgarrish** [comment]
I'm starting to think the embedded SVG definition is muddled in other ways than this issue has gotten into.

For one, the XHTML content document definition already allows the use of epub:type and the vocabulary association mechanisms. Since embedded SVG are part of the XHTML grammar, wouldn't it be redundant to say that the same is true for them?

But why are SVG files referenced by `img` and `object` even considered embedded? If you use those elements, you're referencing SVG documents (i.e., standalone SVGs in a separate file). That requires them to be valid SVG core media types which in turn means they have to meet the definition of an SVG content document.

I was going to say this is a class 3 change, since we'd be allowing epub:type and the vocabulary mechanisms where they technically weren't before, but I don't think anything normative needs changing. We probably just need to make clear that embedded SVG refers to the `svg` element in an XHTML file and that the same content restrictions apply to them.

**Comment by mattgarrish** [comment]
Or if it helps, when you embed an XHTML document via an `iframe` that document doesn't become exempt from the xhtml content document rules, so there's no reason why referencing SVGs from `img` or `object` would require a different definition of SVG.

The only unique case is when an `svg` element is directly embedded in the HTML. The restrictions need to be the same as standalone SVGs, but the vocabulary stuff is already handled by the HTML requirements (e.g., the `prefix` attribute should only be on the root `html` element, while `epub:type` is still allowed anywhere).

**Comment by iherman** [comment]
> I'm starting to think the embedded SVG definition is muddled in other ways than this issue has gotten into.
> […]
> 
> But why are SVG files referenced by `img` and `object` even considered embedded? If you use those elements, you're referencing SVG documents (i.e., standalone SVGs in a separate file). That requires them to be valid SVG core media types which in turn means they have to meet the definition of an SVG content document.
> 

To be honest... for me, "embedded" meant the case when the `<svg>` element is _within_ the HTML markup. In other words, `img` or `object` is not really "embedded", at least to me.  However... if one looks at the HTML standard, then the [`<img>` element specification](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) is part of a [section](https://html.spec.whatwg.org/multipage/embedded-content.html#embedded-content) entitled… "4.8 Embedded content". (The same terminology is used on MDN, b.t.w.)

I.e., if we want to keep to the official terminology then yes, these are "embedded" content (in spite of my expectations...)

> I was going to say this is a class 3 change, since we'd be allowing epub:type and the vocabulary mechanisms where they technically weren't before, but I don't think anything normative needs changing. We probably just need to make clear that embedded SVG refers to the `svg` element in an XHTML file and that the same content restrictions apply to them.

I am fine with the underlying technical intention, but then the word "embedded" should be changed. Not sure whether this becomes an editorial nightmare, though...

**Comment by mattgarrish** [comment]
> if one looks at the HTML standard, then the [`<img>` element specification](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) is part of a [section](https://html.spec.whatwg.org/multipage/embedded-content.html#embedded-content) entitled… "4.8 Embedded content"

Right, this is why the section makes the distinction between embedded by reference and by direct inclusion, but then we lump both together and say that the svg content restrictions apply to both without clarifying any of the other details.

I'd like to see the section changed along these lines:

> [XHTML content documents](https://www.w3.org/TR/epub-33/#dfn-xhtml-content-document) support the embedding of SVG by _reference_ (embedding via reference, for example, from an `img` or `object` element) and by _inclusion_ (embedding via direct inclusion of the `svg` element in the XHTML content document).
> 
> SVGs embedded by reference are SVG core media types so their requirements are already defined in [6.2 SVG content documents](https://www.w3.org/TR/epub-33/#sec-svg).
> 
> SVGs embedded by inclusion MUST meet the content conformance constraints for [SVG content documents](https://www.w3.org/TR/epub-33/#dfn-svg-content-document) in [6.2.3 Restrictions on SVG](https://www.w3.org/TR/epub-33/#sec-svg-restrictions). Although the `epub:type` attribute is allowed on [HTML] embedded content, its [use is restricted](https://www.w3.org/TR/epub-33/#confreq-svg-structural-semantics) in the same way as for SVG content documents. 
>
> NOTE:
> The `prefix` attribute is only allowed on the root `html` element for SVG embedded by inclusion.

**Comment by mattgarrish** [comment]
Or, sorry, I forgot we limited where epub:type is allowed in SVG. That can be modified to reference the existing bullet.

**Comment by iherman** [comment]
I think I agree this means class 2 changes.
