### ISSUE TITLE
Restriction on epub:type in svg is too strict

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2556]
As reported in https://github.com/w3c/epubcheck/issues/1497, the current [restriction on epub:type in svg content documents](https://www.w3.org/TR/epub-33/#confreq-svg-structural-semantics) does not allow the attribute on `a` elements.

The definition of [renderable elements](https://www.w3.org/TR/SVG2/render.html#TermRenderableElement) is probably a better alternative than the three categories listed.

(If the current three categories are kept, however, note that they link to the svg 1.1 specification so should be updated.)

**Comment by iherman** [comment]
This, imho, a valid erratum, and could be marked as such. Definitely a [class 3](https://www.w3.org/2023/Process-20230612/#class-3)...

@TzviyaSiegman @shiestyle @dauwhe @wareid
