### ISSUE TITLE
Clarify that viewport meta allows decimal values

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2557]
As raised in https://github.com/w3c/epubcheck/issues/1481, there are rare occurrences where the value of the viewport meta is expressed with a fractional part.  The current definition, however, says the value must be a positive number, suggesting only positive integers are allowed.

We should probably make clear that decimal values are allowed but reading systems may ignore the fractional part.

**Comment by iherman** [comment]
I would think that is a valid erratum and should be marked as such. Definitely a [class 3](https://www.w3.org/2023/Process-20230612/#class-3) in my view.

@dauwhe @shiestyle @wareid @TzviyaSiegman

**Comment by bduga** [comment]
I am not sure there is a bug here. Decimal seems to imply the base, not that fractions are allowed (decimal vs hexadecimal, etc). "Number" is typically used to mean a whole number or one with a fractional part, "integer" typically means no fraction. For instance, see https://developer.mozilla.org/en-US/docs/Web/CSS/number, but it is pretty common for number to mean whole or fractional.

**Comment by mattgarrish** [comment]
I don't think it's a bug as much as a minor clarification. Positive number was interpreted for epubcheck as whole numbers absent any other explanation of what we meant there.

I like the idea of just linking/citing the CSS number definition, though. That might also push this down to a class 2 change.

I'll update the pull request, at any rate, and if we decide not to do anything we can just close it off.

**Comment by iherman** [comment]
With the explicit reference to CSS as the only change, is this really a class-3 change? It smells class-2 change to me...

**Comment by mattgarrish** [comment]
> It smells class-2 change to me...

That's my take now, too. We're just making clearer the connection to the already referenced ICB immediately above the list items.
