### ISSUE TITLE
Minor issue in editors draft: Broken link to latest published

### ISSUE THREAD

**Issue by plannero** [mattgarrish/epub-revision#2582]
In the GitHub editors draft version of the ePub-EAA mapping (https://w3c.github.io/epub-specs/epub33/epub-a11y-eaa-mapping/) dated September 12 2023, the very first link on the page (to "Latest published version") has a URL ("https://www.w3.org/epub-a11y-eaa-mapping/") that leads to a 404 error message.

I guess it should be changed to "https://www.w3.org/TR/epub-a11y-eaa-mapping/".

**Comment by mattgarrish** [comment]
Yes, the editor drafts for all the notes still have "epub" as the working group in the respec initialization metadata, but it's now "pm" (publishing maintenance working group). That's causing respec to default to its base profile and break the links.

Should we republish all the notes to update the group contact info, etc.? (Or turn off echinda and fix the editor drafts but leave republishing until we have more significant changes?)

Thoughts @iherman @wareid @dauwhe @shiestyle ?

**Comment by iherman** [comment]
> 
> Should we republish all the notes to update the group contact info, etc.? (Or turn off echinda and fix the editor drafts but leave republishing until we have more significant changes?)
> 
> Thoughts @iherman @wareid @dauwhe @shiestyle ?

I believe this is painless, and mostly invisible to everyone, so it could be done.

That being said: I am surprised. The original issue, as raised by @plannero claims that the 'latest version' link did not include the '/TR/' in the URL, but I do not see this error. It looks good to me.

**Comment by plannero** [comment]
That's odd. "/TR/" is still missing for me. Not that it's a big problem, but I just wanted to document it when I stumbled on it.

<img width="649" alt="image" src="https://github.com/w3c/epub-specs/assets/2157085/a537caf9-b771-42cb-a6c6-dd258e4e3a30">

**Comment by mattgarrish** [comment]
It seems to depend on the browser. When I tried it in Edge yesterday I was going to post the same comment about it being fine, but when I tried in Firefox and Chrome the link was broken. In Edge I don't get the errors about respec defaulting to the base profile. Maybe we should report the issue in the respec tracker, too.

**Comment by mattgarrish** [comment]
I'm going to close this issue as we fixed the problem when we republished all the notes in https://github.com/w3c/epub-specs/pull/2599.
