### ISSUE TITLE
URI mention without reference

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2594]
[Section 5.5.3.1](https://www.w3.org/TR/epub-33/#sec-opf-dcidentifier) says:

> EPUB creators MAY specify additional identifiers. The identifiers should be fully qualified URIs.

But we dropped URI references during 3.3 in favour of URL.

I think this could be rewritten as:

> EPUB creators MAY specify additional identifiers. The identifiers should be [absolute-url strings](https://url.spec.whatwg.org/#absolute-url-string) [url].

Since it's an informative recommendation, this change shouldn't rise above class 2, at least.

**Comment by iherman** [comment]
Ouch. Good catch...

**Comment by mattgarrish** [comment]
If we really want to nitpick, shouldn't this also be modified to: "All identifiers should be..."

Right now, it sounds like it's saying only any additional identifiers should be absolute-url strings. The original 3.0 wording was "It is strongly recommended that all identifiers be...".

**Comment by iherman** [comment]
> If we really want to nitpick, shouldn't this also be modified to: "All identifiers should be..."
> 
> Right now, it sounds like it's saying only any additional identifiers should be absolute-url strings. The original 3.0 wording was "It is strongly recommended that all identifiers be...".

Hm. You are right but if I was very, very picky I would say that this change could be considered as class 3 change, because there is (albeit infinitesimal) chance that there are implementations that have passed the bar with the current version and would not with the new one!😀  But let us not be _that_ picky, right?

**Comment by mattgarrish** [comment]
> I would say that this change could be considered as class 3 change

But it's still only informative advice, so all or some or none can be absolute-url strings and it technically changes nothing. I think we're safe at 2 even with the extra change.

**Comment by mattgarrish** [comment]
If we want to avoid changing that wording, though, I'd be equally fine with just splitting the sentence into a new paragraph. So long as it doesn't immediately follow the text about additional identifiers, like it does now, it should be fine as is.

**Comment by iherman** [comment]
Actually, putting it into a separate paragraph is probably better.

**Comment by mattgarrish** [comment]
Ya, not to belabour the discussion of this, but part of me really wants to put the text in a note. It sounds too much like a normative recommendation, plus there's no explanation given why we're recommending this practice. If we move it to a note, we could add a bit more text that domain-specific urls tend to be more reliably unique and urns allow the type of identifier to be specified. That was why we added this guidance in the first place.
