### ISSUE TITLE
Broken reference to rfc 7230

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2595]
[Section 3.6](https://www.w3.org/TR/epub-33/#sec-resource-locations) has a broken reference to RFC 7230:

> When resources have to be located outside the EPUB container, EPUB creators are RECOMMENDED to reference them via the secure https URI scheme [rfc7230] 

Looks like double brackets weren't used on this one.

(The use of URI looks fine here since it's defined in the rfc.)

**Comment by iherman** [comment]
Sigh... :-)

**Comment by iherman** [comment]
Actually, it should be replaced by 9110 (see also #2596)

**Comment by iherman** [comment]
The reference should also be changed in the RS (see https://www.w3.org/TR/epub-rs-33/#sec-epub-rs-conf-remote-res)
