### ISSUE TITLE
Duplicate text in section 2.1 of 'EPUB Reading Systems 3.3 (25 May 2023)'

### ISSUE THREAD

**Issue by koalie** [mattgarrish/epub-revision#2606]
(Relaying feedback sent to me personally)

In 'EPUB Reading Systems 3.3 (25 May 2023)', Section 2.1 "Requirements", this line is repeated twice:

> When supporting recommended and optional features, reading systems MUST meet all normative requirements as defined in their respective sections.

**Comment by iherman** [comment]
Oops.... Thanks Coralie
