### ISSUE TITLE
Recommendation to use epub:type for page breaks

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2621]
The techniques document for page breaks says:

> It is recommended that both semantics be applied to EPUB 3 content to ensure maximum compatibility with [reading systems](https://www.w3.org/TR/epub/#dfn-epub-reading-system) and [assistive technologies](https://www.w3.org/TR/epub-a11y-11/#dfn-assistive-technology).

https://www.w3.org/TR/epub-a11y-tech-11/#page-001

But as raised in https://github.com/daisy/ace/issues/414, is there a specific reason for this advice? I can't remember anymore if we put this in to deal with a known reading system or if we just weren't sure if some reading system somewhere might be making use of the semantic. As mentioned in the other issue, I don't know of any reading systems that do anything with the epub:type semantic.

Should we change this advice to require the aria role and make the epub:type optional for reading system compatibility? That would be more in keeping with not using epub:type for accessibility.

**Comment by GeorgeKerscher** [comment]
I think the emphasis would be on the role doc-pagebreak. We are in process of asking the screen readers to announce this and even to provide single letter navigation. I don't think the EPUB type is used for much of anything.

**Comment by gregoriopellegrino** [comment]
I would suggest checking with some developers to make sure they are not using epub:type for managing UX. From some tests on other semantic elements, I have noticed, for example, that some logic in Thorium and Apple Books is based on epub:type attribute.

**Comment by mattgarrish** [comment]
> to make sure they are not using epub:type for managing UX

But this isn't a reason to link it to an accessibility issue and have ace reporting it. We can still suggest keeping both for reading system interop, which is what we do elsewhere, but the accessibility techniques shouldn't be recommending UX requirements.
