### ISSUE TITLE
Nav doc semantics aren't required by the specification

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2623]
One of the things you stop seeing after a while, I guess, but despite calling the sections "The toc nav element" and "The page-list nav element", we don't appear to require any specific semantic be used on these nav elements. An epub:type attribute is required, but not a specific value.

The semantics are implied by the sections and the obviousness of the semantic names, of course, but that's not exactly sound spec writing. And the structure vocab mentions their intended uses in the usage details section for each, but that's also not normative.

It would be better if each of the toc, page-list, and, landmarks nav sections required those semantics in their respective epub:type attributes.

(On a side note, there's a typo in the first sentence of the page-list nav section. It says "The `page-list` element provides ..." but it should be "The `page-list nav` element provides ")

**Comment by iherman** [comment]
+1.

Thankfully, the `toc`, `landmarks`, and `page-list` values are defined in the [separate note](https://www.w3.org/TR/epub-ssv-11/), so it is only a question of an (almost) editorial change in the document. Note that some examples (Nos. [51](https://www.w3.org/TR/epub-33/#example-a-basic-landmarks-nav) or [53](https://www.w3.org/TR/epub-33/#example-hiding-a-nav-element-in-spine)) actually use these values already.

**Comment by mattgarrish** [comment]
> so it is only a question of an (almost) editorial change in the document

Ya, the requirements are all essentially implied by the section naming, and the introduction explains the correlation between the epub:type values and what they define, but if you just land at one of the definitions there's nothing there that makes clear what a `toc nav` is or that we're talking about the epub:type attribute value.

I think maybe all we need is to rewrite the first sentence of each section. For example, instead of:

> The toc nav element defines the primary navigational hierarchy.

We be more explicit what we're talking about and link everything up:

> A [^nav^] element [[html]] with its [^epub:type^] attribute set to the value [toc](https://www.w3.org/TR/epub-ssv-11/#toc-1) [[epub-ssv-11]] defines the primary navigational hierarchy.

(Edit: removed redundant "value" from proposal.)

**Comment by mattgarrish** [comment]
Or maybe it would be clearer to rearrange a bit, too:

> The primary navigational hierarchy for the [=EPUB publication=] is defined in a [^nav^] element [[html]] with its [^epub:type^] attribute set to the value [toc](https://www.w3.org/TR/epub-ssv-11/#toc-1) [[epub-ssv-11]].
