### ISSUE TITLE
Update conformance list to include wcag 2.2

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2629]
While updating the techniques document, it occurred to me that all our undated wcag2 references now point people to 2.2. Our list of conformance strings in the accessibility spec only shows values for 2.0 and 2.1, however.

Although the conformance strings adapt to new values, should we make 2.2 conformance explicit in the specification? It should only count as a category 2 change since we'd only be adding examples of the strings.

**Comment by GeorgeKerscher** [comment]
Yes, we should update this. It will make APA happy.
