### ISSUE TITLE
Consistent spelling of whitespace

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2636]
Minor nit, but I noticed we alternate between "whitespace" and "white space", sometimes having both spellings within the same section.

Since we're always talking about the characters, we should standardize on whitespace.

I was only looking at the epub 3 spec, but probably worth searching them out across all the docs.

**Comment by GeorgeKerscher** [comment]
As an fyi, screen readers pronounce whitespace incorrectly.  They do pronounce whiteSpace and white space and white-space correctly.

**Comment by mattgarrish** [comment]
I just found an issue on the same thing in the mdn repository: https://github.com/orgs/mdn/discussions/382

The whitespace spelling seems to be predominantly used for characters, even in CSS, while "white space" is about layout, at least by their review of web standards. We reference whitespace from the infra spec, and it uses the no-space spelling, so it seems like we should be consistent with it.

But then the XML spec uses "white space" for characters, and we oddly mix references to its definition of whitespace and normalization even though it doesn't include Form Feed as the infra definition does.

It's starting to make my head ache that maybe our definitions and processing of whitespace are not consistent. We use infra's definition in some places and XML's in others (at least with the epub:type definition). We use the infra processing of leading and trailing whitespace in the package document metadata but xml's whitespace normalization for the viewport meta tag definition. I'm not sure that makes a lot of sense.

I wonder if the mispronunciation is something we should report to the screenreader makers rather than try to work around it, and then try to figure out what inconsistencies we might have in the spec beyond the naming.

**Comment by GeorgeKerscher** [comment]
It is easy enough for a screen reader user to add this to an exception dictionary to get the  pronunciation they want. Having TTS speak it as two words  would create problems in normal writing, so I do not think it should be reported. Screen reader users working on specs should be informed how to write it as one word and when.

**Comment by iherman** [comment]
I did a quick check, and here is what I got:

- a11y: 
    - whitespace 1;  white space: 0
- rs:
    -  whitespace 6 ; white space: 1
- tts:
    -  whitespace 2; white space: 0

None are used in the other documents.

This means, in practice, there is a single change to be made in the RS spec, and we are fine if we use "whitespace" (if my numbers are correct)

**Comment by mattgarrish** [comment]
That's good, at least.

I think we need to take another look at why we reference the infra spec for the whitespace definition, though. It's not the authority for xml grammars like the package document, and even with xhtml I'm not sure it's relevant since xhtml uses an xml parser, too.

It may be fine to reference the whitespace processing functions, since the addition of FF in those wouldn't matter if we don't allow it in authoring.
