### ISSUE TITLE
Wrong link to technique in EPUB Accessibility 1.1 note

### ISSUE THREAD

**Issue by gregoriopellegrino** [mattgarrish/epub-revision#2645]
I realized that in the note in [3.4.2.3.1 Completeness](https://www.w3.org/TR/epub-a11y-11/#sec-sync-complete) the name of the link is **Ensuring complete text coverage**, but the link leads to **5.2.4 Identifying escapable structures**, the correct link should be https://www.w3.org/TR/epub-a11y-tech-11/#sync-coverage

**Comment by iherman** [comment]
Will you provide a PR, @gregoriopellegrino, or should I do it?

**Comment by gregoriopellegrino** [comment]
I'll do it

**Comment by mattgarrish** [comment]
Closing this with https://github.com/w3c/epub-specs/pull/2646
