### ISSUE TITLE
Update reference to iso 8601

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2658]
## Issue on the [EPUB 3.3](https://www.w3.org/TR/epub-33/) Recommendation

Section 5.5.3.2.4 The dc:date element

## Describe the problem 

I noticed we have a reference in that section to iso8601:2004 which in turn links to the withdrawn standard page: https://www.iso.org/standard/40874.html

## Describe the fix or new feature you propose

Change the reference to 8601-1:2019

We might also want to look at why we say dcterms:modified must be an xmlschema-2 conformant dateTime, even though it uses a pattern that also conforms to iso 8601. My guess is that reference was meant to match the package document schemas and the dc:date reference came later. It would probably be better to have both date formats reference the same standard.

**Comment by iherman** [comment]
For the last part, just to see if I understand it properly: you propose to change, in https://www.w3.org/TR/epub-33/#sec-metadata-last-modified, the reference to xmlschema-2 to iso 8601? I would be fine with this.

B.t.w. (but you may have already chased this down) we need then to use `[[iso8601-1]]` in the source, per https://www.specref.org/?q=iso8601

**Comment by mattgarrish** [comment]
> you propose to change, in https://www.w3.org/TR/epub-33/#sec-metadata-last-modified, the reference to xmlschema-2 to iso 8601

Right, it's kind of odd that we use two different standards to refer to date/time formats when one will do. And unlike dc:date, the dcterms:modified definition is strictly controlled, so it's not like the date standard we use has any real influence over what is valid. Last modified dates are always iso 8601 conformant, so let's just consistently use that standard.

**Comment by iherman** [comment]
Luckily, this will be a class 2 change, so it is no problem incorporating this in the upcoming proposed correction version...
