### ISSUE TITLE
I have fixed horizontal pages ebook with small images on background (flattened to one page background graphic and instructional text frames on the right while small images on the left size, created by ppt. Will there text reflow issues on EPUB 3.3?

### ISSUE THREAD

**Issue by CC1628** [mattgarrish/epub-revision#2663]
## Issue on the [EPUB 3.3](https://www.w3.org/TR/epub-33/) Recommendation

If appropriate, include the relevant section.

## Describe the problem 

What is not working? What would you like to see improved? For bug reports, cite the relevant text from the specification.

**Comment by iherman** [comment]
Please, answer the question/issues on the issue comment, @CC1628; and also give a proper, succinct title. It is impossible to act upon the two sentences in the title.

**Comment by mattgarrish** [comment]
Should this be closed? It sounds like an authoring help question, not an issue with the specification.
